### ISSUE TITLE
No output [purchase_history] shortcode when wp user id and edd customer id does not match. 

### ISSUE THREAD

**Issue by abushoaib** [easydigitaldownloads/easy-digital-downloads#5735] opened 2017-05-12 12:19 UTC
Edd [purchase_history] short code throws wrong information when edd customer id and wp user id does not match. It displays " 'You have not made any purchases " but customer has made payment already. 

After checking i see user purchase called using current logged in user id which does not match with edd customer id both ids are different https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/history-purchases.php#L11 

Which causes empty payment list.  Please use email address instead of using wp user id . E-mail address will work fine if wordpress user id and edd customer id does not match.

**Comment by cklosowski** [comment] 2017-05-15 14:48
We've started doing this, and I think it's caused by a bug that's hopefully fixed in another issue we've slated for 2.8. I think relying on email might be the more consistent way to go until we can get those conflicts resolved.

**Comment by cklosowski** [comment] 2017-08-21 21:38
@easydigitaldownloads/core-devs Could we get some testing on this? I'd like to see if the work we did in EDD 2.8 helped resolve some of this.

**Comment by pippinsplugins** [comment] 2017-08-24 19:38
I don't see any reason to not go ahead and change it to use an email instead of user ID.

**Comment by chriscct7** [comment] 2017-08-28 20:03
I could be wrong on this, but if you instantiate an EDD_Customer (which edd_get_users_purchases() uses) by the non-primary email of a customer, it won't find the customer, right. So potentially if the user's account's email is an email that is not the primary email of the EDD customer, the lookup will fail, and the shortcode won't work

**Comment by chriscct7** [comment] 2017-08-28 20:04
That being said I think user email lookup is safer, but should we consider a new ticket that EDD Customer should try to find a user in the additional email fields or something if the email passed in is not the primary email of a EDD customer?

**Comment by pippinsplugins** [comment] 2017-08-29 02:27
>>>I could be wrong on this, but if you instantiate an EDD_Customer (which edd_get_users_purchases() uses) by the non-primary email of a customer, it won't find the customer, right.

That is incorrect. Customer look up works with any email registered on the customer.

**Comment by sunnyratilal** [comment] 2017-08-31 13:04
Just tested on `master` with a user ID: 3 and EDD customer ID: 2 and the `[purchase_history]` shortcode was displaying the correct purchases.

**Comment by sunnyratilal** [comment] 2017-09-27 10:02
@cklosowski are we good to close this? I tested it once again and can't replicate the bug.

**Comment by cklosowski** [comment] 2017-09-27 23:45
I'd like to just punt it down the road until we can get a more solidified hold on it. I'm actually working with the ApproveMe team ( @abushoaib ) on getting some legacy EDD stuff implemented on their end that's just needing some refreshing over time, so this might end up getting resolved there in their implementation.

Let's keep an eye on it though.

**Comment by sunnyratilal** [comment] 2017-10-30 06:20
Still unable to replicate this.

**Comment by sunnyratilal** [comment] 2017-11-03 00:07
Punting to 2.9.

**Comment by pippinsplugins** [comment] 2018-03-05 00:59
Closing as fixed.

**Closed by pippinsplugins** 2018-03-05 00:59 UTC
Labels: Needs Replication
