### ISSUE TITLE
CSV files reported invalid erroneously 

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/easy-digital-downloads#4769] opened 2016-07-06 13:40 UTC
With some computers a CSV file will report as invalid. That same file will work fine when uploaded from other computers.

https://secure.helpscout.net/conversation/223263060/37423/?folderId=454023

**Comment by pippinsplugins** [comment] 2016-07-06 13:47
Another instance of this: https://secure.helpscout.net/conversation/222395560/37310/?folderId=180504

**Comment by cklosowski** [comment] 2016-07-29 17:06
From duplciate issue:
```
A number of users have experienced issues when uploading CSV files for import. Instead of accepting the CSV file, EDD gives an error that The file you uploaded does not appear to be a CSV file. This error is occurring even when the file is definitely a proper CSV.

It happens intermittently and appears to be browser or computer specific. The same file that fails on one computer succeeds fine on another.

Example ticket: https://secure.helpscout.net/conversation/230558279/38684/?folderId=180499
```

**Comment by cklosowski** [comment] 2016-07-29 19:17
@pippinsplugins I've pulled down the examples that have CSV files can I cannot replicate any issues here. I've even gone through and installed a CSV Linter locally and everything returns as valid, so there's not some weird standards issue we're seeing (which would have possibly explained the different browser behavior).

The only thing I can think is something on the computers is setting a different mimetype for `text/csv` than the standard `text/csv`. There are a few cases where people have described having Excel installed has caused CSV files to have a mime type other than `text/csv`. By downloading the .csv file on a different computer, the MIME is maintained however, so that's why it usually doesn't' affect on every computer even for the same user.

It's possible we just need to account for all possible states of a CSV mimetype (taken from a mimetype Database):
```
application/csv - Description for mime application/csv is coming soon...
application/excel - Description for mime application/excel is coming soon...
application/vnd.msexcel - Description for mime application/vnd.msexcel is coming soon...
application/vnd.ms-excel - The MIME type application/vnd.ms-excel is used to denote the presence...
text/anytext - Description for mime text/anytext is coming soon...
text/comma-separated-values - Description for mime text/comma-separated-values is coming soon...
text/csv - The MIME type text/csv is used to...
```

**Comment by pippinsplugins** [comment] 2016-07-30 01:03
That seems like a good first approach!

**Comment by SDavisMedia** [comment] 2016-08-23 19:40
I've asked a user to test `issue4769`. https://secure.helpscout.net/conversation/242036126/0/?folderId=180504

**Comment by pippinsplugins** [comment] 2016-08-31 01:58
PR confirmed to _not_ fix the problem for the ticket above. :(

**Comment by shazahm1** [comment] 2016-08-31 13:25
Apologies for jumping in the middle...

 I use the same CSV library as EDD and I've run into this issue myself in one of my plugins.

This issue was, for me, was definitely the MIME type detected by the server.

I found that telling the user to rename the file from `.csv` to `.txt` allowed the file to be uploaded. Not a great solution, but it worked. I eventually had a user give me access to the server which had the issue and I was able to come up with a MIME type list that seems to always "just work". Here's what I use:

``` php
					$args = array(
						'mimes'  => array(
							'csv' => 'text/csv',
							'csv' => 'text/comma-separated-values',
							'csv' => 'text/csv', 'application/csv',
							'csv' => 'application/excel',
							'csv' => 'application/vnd.ms-excel',
							'csv' => 'application/vnd.msexcel',
							'csv' => 'text/plain',
							'csv' => 'text/anytext',
							'csv' => 'text/*',
							'txt' => 'text/plain',
							'txt' => 'text/anytext',
							'txt' => 'text/*',
							),
						);
```

I pass that array to `wp_handle_upload()` and seems to work well, as in no more support tickets for not being to upload.

Any thought I'd share. Hope it helps!

**Comment by pippinsplugins** [comment] 2016-08-31 13:53
Thanks @shazahm1!

**Comment by shazahm1** [comment] 2016-08-31 14:20
Ugh! I need more coffee apparently, that is an old array from very old code which obviously will not work because of the duplicate array keys. This is the array of mimes I pass to `wp_handle_upload()`

``` php
$args = array(
	'mimes' => array(
		'csv' => 'text/csv',
		'txt' => 'text/plain',
	)
);
```

**Comment by pippinsplugins** [comment] 2016-08-31 15:46
The customer mentioned above is seeing it fail because her mimetype is coming in as `application/vnd.ms-excel`

**Comment by pippinsplugins** [comment] 2016-08-31 15:49
Expanded the list:
```php
$accepted_mime_types = array(
	'text/csv',
	'text/comma-separated-values',
	'text/plain',
	'text/anytext',
	'text/*',
	'text/plain',
	'text/anytext',
	'text/*',
	'application/csv',
	'application/excel',
	'application/vnd.ms-excel',
	'application/vnd.msexcel',
);
```

**Comment by pippinsplugins** [comment] 2016-08-31 15:50
Having the customer try it again.

**Comment by shazahm1** [comment] 2016-08-31 16:07
Just a curiosity question...

Wouldn't this still fail to upload?

If it passes your mime check, it would not pass the mime check done in `wp_handle_upload()`. Well at least it shouldn't. It'll be interesting to see the result of your customer's test.

**Comment by pippinsplugins** [comment] 2016-08-31 16:32
Good question . . . we filter the mimetypes in core like this:
```php
/**
 * Allowed Mime Types
 *
 * @since 1.0
 *
 * @param array $existing_mimes A list of all the existing MIME types
 * @return array A list of all the new MIME types appended
 */
function edd_allowed_mime_types( $existing_mimes = array() ) {
	$existing_mimes['zip']  = 'application/zip';
	$existing_mimes['epub'] = 'application/epub+zip';
	$existing_mimes['mobi'] = 'application/x-mobipocket-ebook';
	$existing_mimes['m4r']  = 'audio/aac';
	$existing_mimes['aif']  = 'audio/x-aiff';
	$existing_mimes['aiff'] = 'audio/aiff';
	$existing_mimes['psd']  = 'image/photoshop';
	$existing_mimes['exe']  = 'application/octet-stream';
	$existing_mimes['apk']  = 'application/vnd.android.package-archive';
	$existing_mimes['msi']  = 'application/x-ole-storage';
	$existing_mimes['csv']  = 'text/csv';

	return $existing_mimes;
}
add_filter( 'upload_mimes', 'edd_allowed_mime_types' );
```
Some of those types are not registered. I'm not 100% sure how the checking works in WP core.

**Comment by pippinsplugins** [comment] 2016-08-31 17:15
Customer reported the change fixes it for IE but not Firefox.

**Comment by cklosowski** [comment] 2016-09-01 23:14
That's a start! Do we know what the MIME type was on Firefox? I'm assuming their are reading them slightly differently as they upload it or something.

**Comment by cklosowski** [comment] 2016-09-01 23:15
The other option, like @shazahm1 said, what if we, after uploading just save the temp file as a `.txt` instead of `.csv`. The functions we use don't really care about the extension, just the content.

**Comment by pippinsplugins** [comment] 2016-09-02 02:40
@cklosowski I don't know what the mimetype is, unfortunately.

**Comment by cklosowski** [comment] 2016-09-14 20:49
Closing this for now, as it should resolve most cases we run into

**Closed by cklosowski** 2016-09-14 20:49 UTC
Labels: Bug
