### ISSUE TITLE
Custom checkout fields empty on version 2.6.12

### ISSUE THREAD

**Issue by tomasvilda** [easydigitaldownloads/easy-digital-downloads#5228] opened 2016-11-20 17:00 UTC
Custom checkout fields empty on 2.6.12 version. All previous versions register custom fields OK.

Here is snippet that I use:

```php
function pippin_edd_custom_checkout_fields() {
?>
    <p id="edd-phone-wrap">
    <label class="edd-label" for="edd-phone"><?php _e('Phone number', 'pippin_edd'); ?></label>
    <span class="edd-description"><?php _e( 'Enter phone number', 'pippin_edd' ); ?></span>
    <input class="edd-input" type="text" name="edd_phone" id="edd-phone" placeholder="<?php _e('Phone number', 'pippin_edd'); ?>" value=""/>
    </p>
<?php
}
add_action('edd_purchase_form_user_info', 'pippin_edd_custom_checkout_fields');

function pippin_edd_store_custom_fields($payment_meta) {
    $payment_meta['phone'] = isset( $_POST['edd_phone'] ) ? sanitize_text_field( $_POST['edd_phone'] ) : '';
    return $payment_meta;
}
add_filter('edd_payment_meta', 'pippin_edd_store_custom_fields');

function pippin_edd_purchase_details($payment_meta, $user_info) {
    $phone   = isset( $payment_meta['phone'] ) ? $payment_meta['phone'] : 'none';
?>
<li><?php echo __('Phone:', 'pippin_edd') . ' ' . $phone; ?></li>
<?php
}
add_action('edd_payment_personal_details_list', 'pippin_edd_purchase_details', 10, 2);
```

**Comment by upsellpl** [comment] 2016-11-21 15:21
I confirm. In _edd_payment_meta was:

```
array (
  'fees' => 
```

and currenty is:

```
array (
  0 => 
  array (
    'fees' => 
```

**Comment by pippinsplugins** [comment] 2016-11-21 16:11
My guess is it has to do with this https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5213/files

**Comment by sunnyratilal** [comment] 2016-11-21 16:15
@pippinsplugins That code will only run if the meta key being updated is `_edd_payment_user_email` or `email`

**Comment by cklosowski** [comment] 2016-11-21 16:46
Yeah it was that change. the side affect if using `false` for single is that we get back a `0` indexed array, which, the data was saving for the custom fields but in an array of `[0]['phone']`

This leads me to believe that we might have this in a few cases...shoudl we write an upgrade routine that looks through all payment meta for a `0` index and move the content out of it, and into the main array @pippinsplugins ?

**Comment by pippinsplugins** [comment] 2016-11-21 17:09
@cklosowski I'd be leery to do that for every payment. How about checking them when the payment is loaded. That will fix any affected payments over time.

**Comment by cklosowski** [comment] 2016-11-21 17:14
yeah I'll see if I can get somethign done up for that.

**Comment by cklosowski** [comment] 2016-11-21 17:50
ok @pippinsplugins I added in a clause when getting the meta, that if something is setup with a `0` index, we fix it...and then immediately update the post meta, so it ever only runs once. I also added in unit tests to prove the fix.

**Comment by cklosowski** [comment] 2016-11-21 17:57
@tomasvilda can you verify that this PR will do what you need?

**Comment by cklosowski** [comment] 2016-11-21 17:57
@upsellpl Same, if you're available for a quick test.

**Comment by michaelbeil** [comment] 2016-11-21 18:12
Looks good here.

**Comment by tomasvilda** [comment] 2016-11-21 18:14
@cklosowski using latest version of class-edd-payment.php makes older custom fields visible again and new payments data is visible also. Thank you!

**Comment by cklosowski** [comment] 2016-11-21 18:17
Thanks @tomasvilda I'll get this merged in and released today.

**Closed** 2016-11-21 18:50 UTC
Labels: Bug

**Comment by stephywells** [comment] 2016-11-21 18:59
Just to add to this... I'm seeing a similar issue with non-custom fields. The whole array is in [0]. I'm seeing payments with no downloads. I added a quick fix to prevent broken accounts:
`	add_filter( 'edd_get_payment_meta__edd_payment_meta', 's11EddMigrate::correct_payment_meta_format' );
	function correct_payment_meta_format( $meta ) {
		if ( isset( $meta[0] ) && ! isset( $meta['cart_details'] ) ) {
			$more_meta = $meta[0];
			$meta = array_merge( $meta, $more_meta );
		}
		return $meta;
	}`

It looks like your fix will cover it all. Just wanted to let you know the issue is bigger than just custom fields.
