### ISSUE TITLE
Inactive discount codes show as "Active" within discount table view

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6534] opened 2018-05-01 19:03 UTC
**Bug Report**
When switching a discount code from "Active" to "Inactive", the table still display's the discount code as "Active".

**Expected behavior**
The table should show the discount code as "Inactive".

**Actual behavior**
Discount code remains as "Active", confusing the site owner.

**Steps to reproduce the behavior**
1. Create a new discount code and set it to "Active"
2. Within the table set it to "Inactive" 
3. The discount code continues to show as "Active"

**Comment by SDavisMedia** [comment] 2018-05-02 16:44
This stopped working in 2.9. Everything before was fine. I haven't had any luck tracking down the culprit, though.

**Comment by cklosowski** [comment] 2018-07-03 22:16
So the root cause of this is that `status` and `post_status` are attempted to be used interchangeably.

We have `EDD_Discount::update_status` which updates the `post_status` column, but then we also have `EDD_Discount::setup_status` which is using `$this->get_meta`.

We need to pick one, as we're ending up with mixed results with `status` being `inactive` from meta, but the `post_status` being listed as `Active`.

**Comment by cklosowski** [comment] 2018-07-03 22:16
@sunnyratilal let me know what you think here.

**Comment by sunnyratilal** [comment] 2018-07-10 21:40
After discussing with @cklosowski, this will be fixed in 3.0.

**Comment by sunnyratilal** [comment] 2018-07-11 23:11
Issue has been fixed in 3.0.

**Closed by sunnyratilal** 2018-07-11 23:11 UTC
Labels: Administration, Bug, Discounts
