### ISSUE TITLE
3.0 - Orders - Combine Items, Adjustments, and Amounts UI

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7582] opened 2020-02-12 16:49 UTC
### Explain your enhancement (please be detailed)

Create a unified UI to present Order Items, Adjustments, and Amounts.

### Justification or use case

Currently when viewing or creating an order in EDD 3.0 there are 3 separate areas containing amounts related to the Order: Items, Adjustments, and Amounts.

As it stands the Items and Adjustments are implemented with `WP_List_Table`, separate from the Amounts area:

<img width="1119" alt="Screen Shot 2020-02-12 at 11 14 36 AM" src="https://user-images.githubusercontent.com/491124/74357184-8a0c2280-4d8d-11ea-8804-59c5cd992dc8.png">

The "Order Adjustments" area is likely causing the most disconnect in the UI. Grouping applied Discounts inside of "Order Adjustments" but then displaying "Adjustments" and "Discount" amounts separately in other areas causes confusion as to what an Adjustment actually is.

While the new database has provided tons of great new functionality I think the current UI presents the information too much in a _database-y_ way versus a more traditional invoice. The user does not need to know that we store or classify tax, credit, fee, or discount as an `adjustment`.

Another potentially confusing concept is adjusting or displaying a "Refunded" status for individual line items. To help further enforce the concept of "order amounts cannot change" not adjusting the line item will help show that in this order nothing has changed.

<img width="1119" alt="Screen Shot 2020-02-12 at 11 25 21 AM" src="https://user-images.githubusercontent.com/491124/74356976-30a3f380-4d8d-11ea-8fcf-06a1a62d242c.png">

The above prototype (amounts are not accurate) displays a way to potentially resolve these disconnects.

By not "classifying" adjustments but instead simply listing how they affect the Order subtotal the user has fewer dots to connect.

Beyond that "refunded" line items remain the same after a Refund has been issued and instead a new entry is added to the amount summary after the existing Order total is listed. This helps enforce that the current order has not changed -- but there is a new record that affects the net. The Net amount could be shown below as well.

The line-item Discount and Tax amounts were moved below the Download name as secondary information because having them in their own column disrupts the Discount and Tax total amounts in the summary area. They can be shown when hovering a row if the specific information is needed. 

Clicking "Issue Refund" will work similarly to what is setup now: listing the available order items that can be "refunded". Ideally you should be able to create a refund for a specific item quantity as well as any additional fees.

Creating an Order would present a similar UI, with "Add" buttons replacing the Refund button at the bottom. They would trigger a modal similar to the Refund modal allowing options to be selected (and the ability to override amounts). 

---

Some previous discussion in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7341

**Comment by nosegraze** [comment] 2020-02-12 17:01
> I think the current UI presents the information too much in a database-y way versus a more traditional invoice. The user does not need to know that we store or classify tax, credit, fee, or discount as an adjustment.

:100:

**Comment by spencerfinnell** [comment] 2020-02-12 19:29
Using a modal for adding items would allow that UI to be expressed a little more freely/clearly:

<img width="515" alt="Screen Shot 2020-02-12 at 2 08 52 PM" src="https://user-images.githubusercontent.com/491124/74369786-f72ab280-4da3-11ea-8055-46bd40b0787d.png">
<img width="510" alt="Screen Shot 2020-02-12 at 2 09 16 PM" src="https://user-images.githubusercontent.com/491124/74369789-f7c34900-4da3-11ea-9377-3e8f54537ff7.png">

As well as keeping the base Add/View screens more consistent.

**Comment by spencerfinnell** [comment] 2020-02-27 20:54
Bringing the PR discussion back here.

@nosegraze regarding [pull/7599#issuecomment-592003274](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7599#issuecomment-592003274) -- how about something like this:

<img width="800" alt="Screen Shot 2020-02-27 at 3 51 38 PM" src="https://user-images.githubusercontent.com/491124/75485752-3f87ca00-5979-11ea-9cff-942f8953796f.png">

This would appear when the tax rate has changed and there are existing Order Items. Clicking "Update Amounts" would recalculate taxes for Order Items that were added without manually entering amounts.

We also may consider differentiating Order Item rows that were manually adjusted so it's more obvious why they do not change.

**Comment by nosegraze** [comment] 2020-02-28 08:17
@spencerfinnell I like that :+1:

**Comment by spencerfinnell** [comment] 2020-02-28 17:09
@nosegraze Since an Order can only have one actual tax rate the process now would mean that if you:

1. Add a Download
2. Change the rate
3. Dismiss the tax rate notice
4. Add another Download

All other Downloads that weren't manually adjusted when initially adding will be adjusted a well -- essentially doing the same as if you _had_ clicked `Update Amounts`.

If that's the case then the only time the notice is really helpful is if you're just about to create the order, realize the taxes are all wrong, and make an adjustment. I think that is a valid time to show it but wonder if the side effect of it showing _during_ order creation might cause confusion.

**Comment by nosegraze** [comment] 2020-03-04 13:25
@spencerfinnell 

> All other Downloads that weren't manually adjusted when initially adding will be adjusted a well

Not sure if I'm 100% clear on this. In the steps you listed, are you saying that download from step 1 would be adjusted with the new tax amount?

**Comment by spencerfinnell** [comment] 2020-03-04 13:34
> Not sure if I'm 100% clear on this. In the steps you listed, are you saying that download from step 1 would be adjusted with the new tax amount?

Yes.

If the Tax amount wasn't manually set (on the individual Order Item) when it was initially added then changing the rate and adding a new Download updates all existing Order Items based on the new percentage. That is done under the assumption that an order only supports one tax rate.

However, looking again now, if you make a purchase on the frontend checkout there is an Order Adjustment record generated that stores a tax rate percentage for each Order Item.  I'm not sure that amount is actually used anywhere currently, but we could (and probably _should_) do the same thing when manually creating an order which would allow Order Item tax amounts to remain independent of each other.

**Comment by nosegraze** [comment] 2020-03-04 13:42
Unrelated to the above... I've discovered an inconsistency with fees and total calculations.

I'm testing with the Discounts Pro add-on, which adds discounts as "fees" (adjustments).

`release/3.0`

![Screenshot from 2020-03-04 13-37-39](https://user-images.githubusercontent.com/6324272/75884952-8f550e00-5e1d-11ea-9f77-3ccbf6175f19.png)

Notice there's one adjustment record and total is $89.40.

`issue/7582`

![Screenshot from 2020-03-04 13-37-58](https://user-images.githubusercontent.com/6324272/75884927-85330f80-5e1d-11ea-8d51-e5d0d7c5d347.png)

There are now two fee entries and total is recorded as $64.90.

I'm wondering if it's because of this:

![Screenshot from 2020-03-04 13-38-27](https://user-images.githubusercontent.com/6324272/75885027-b4e21780-5e1d-11ea-818d-10bf97f3d115.png)

The discount is applied to the `order` and `order_item`. In this case both of the `object_id`s are `57`. I tried to reproduce this a second time and couldn't, because that second time the `order_item` ID happened to be different:

![Screenshot from 2020-03-04 13-41-26](https://user-images.githubusercontent.com/6324272/75885131-dfcc6b80-5e1d-11ea-8119-cd2cca1bd361.png)

Possibly missing an `object_type = order` somewhere?

**Comment by spencerfinnell** [comment] 2020-03-16 14:08
Some adjustments related to ensuring tax rates are easy to use/understand in https://github.com/easydigitaldownloads/easy-digital-downloads/tree/issue/7582-tax-change

- When adding a Download before a rate is set there is a more obvious notice:
<img width="416" alt="Screen Shot 2020-03-16 at 10 02 41 AM" src="https://user-images.githubusercontent.com/491124/76766190-ff448c00-676d-11ea-9d5c-d34ca92afcfa.png">

- Manually set amounts are noted via `&dagger;`
<img width="801" alt="Screen Shot 2020-03-16 at 10 03 00 AM" src="https://user-images.githubusercontent.com/491124/76766206-04094000-676e-11ea-941e-a98c379dee70.png">

- The tax rate change notice explicitly mentions automatic calculations:
<img width="796" alt="Screen Shot 2020-03-16 at 10 06 34 AM" src="https://user-images.githubusercontent.com/491124/76766227-0b304e00-676e-11ea-8f57-ad34a40c1aab.png">

**Comment by ashleyfae** [comment] 2020-03-16 15:03
I like that :+1: 

Note: removing an item doesn't appear to work for me. Clicking the `x` doesn't do anything. No console errors.

**Comment by ashleyfae** [comment] 2020-03-16 15:04
Correction: clicking the `x` does not remove the item from teh table, but it does change the `Total` at the bottom to `$0.00`.

**Comment by spencerfinnell** [comment] 2020-03-16 15:14
@ashleyfae Thanks -- I've noticed that before and wasn't sure if it was just a fluke or not. I'll figure that out.

**Comment by spencerfinnell** [comment] 2020-03-17 16:38
#7599 has been updated to address previous feedback.

Any remaining mobile issues should not be specific to this implementation and happen at a core/WordPress-level.

**Comment by ashleyfae** [comment] 2020-03-19 15:05
- Confirmed [inconsistent fee/totals issue](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7582#issuecomment-594529475) has been fixed.
- Confirmed [issue with removing a download](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7582#issuecomment-599586178) has been fixed.
- Confirmed I can now add a download, then set a customer, then set a tax rate, then use provided button to update tax rate for existing downloads.
- Confirmed responsive design works.

There is an issue with discount codes and tax calculations.

- Create a new order.
- Assign a customer / country that has a tax rate.
- Add a download. Tax amount is calculated correctly.
- Add a discount.
- Tax rate is not reduced / recalculated.

Here's how it looks:

![Screenshot from 2020-03-19 15-03-11](https://user-images.githubusercontent.com/6324272/77081766-06300080-69f3-11ea-9d1f-12af166cd36d.png)

Here's what it should be:

![Screenshot from 2020-03-19 15-03-23](https://user-images.githubusercontent.com/6324272/77081774-0a5c1e00-69f3-11ea-91ee-5fcec8216067.png)

In the admin UI the tax amount is the _pre-discount tax amount_ but it should be recalculated to take the discount into account.

**Comment by spencerfinnell** [comment] 2020-03-23 14:32
@ashleyfae Updated #7599

**Comment by ashleyfae** [comment] 2020-03-24 10:54
@spencerfinnell Looking good now!

I have encountered one issue but it's sporadic and I don't know how to tell you to reproduce it. Sometimes when I'm adding a download, clicking `Add Download` doesn't do anything, so then I click it again, and it works but adds the download _twice_ (so I guess it did actually work the first time, the UI just didn't tell me it had?). I had it happen 3 times while messing around just now, but I couldn't _make_ it happen intentionally. :woman_shrugging:

**Comment by spencerfinnell** [comment] 2020-03-24 11:34
@ashleyfae thanks for testing! I’ll try to reproduce that. I still want to try and preload some Downloads in the modal too.

**Comment by spencerfinnell** [comment] 2020-03-24 16:12
@ashleyfae Pushed some error handling that should prevent any of those weird situations from happening.

**Comment by ashleyfae** [comment] 2020-03-27 12:39
@spencerfinnell Excellent! I played around a bunch and the problem didn't happen again. I love the loading of products. :+1: There is one minor quirk... It doesn't impact functionality, just looks a bit weird.

- Add one product to the order.
- Add a second product. Keep an eye on the "Download" dropdown as you press the `Add Download` button.
- You'll see the dropdown, like, quickly cycle through all the downloads that are already on the order. The more downloads you have in the order, the more noticeable it is.

**Comment by spencerfinnell** [comment] 2020-03-27 14:01
Good catch. Pushed a few tweaks to stop that.

**Comment by ashleyfae** [comment] 2020-04-06 12:13
Don't think I can break anything else! Well done @spencerfinnell .

**Comment by cklosowski** [comment] 2020-04-22 22:36
When adding a new order @spencerfinnell I'm seeing a weird date as the default:
![image](https://user-images.githubusercontent.com/1390124/80040447-f3f02900-84ae-11ea-9a62-29cf6f9a1902.png)

Currently I'm on GMT +0

**Comment by spencerfinnell** [comment] 2020-04-22 22:42
@cklosowski Addressed in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7578#issuecomment-586281961

**Comment by cklosowski** [comment] 2020-04-22 23:02
@spencerfinnell got it, merged that into `release/3.0` and then updated both this issue branch and the `try/edd3-orders`

**Comment by cklosowski** [comment] 2020-04-23 00:04
At this point, I'm starting to think we should just merge this whole thing into `release/3.0` and we can follow up with anything needed there. I can't find anything breaking at this point, but there are a lot of things that this introduces that might be blocking going forward. It will clear out our issue list for the `3.0` milestone quite a bit and allow us to move forward, focusing on things that needed to be wrapped up.

thoughts @ashleyfae and @spencerfinnell ?

**Comment by spencerfinnell** [comment] 2020-04-23 00:08
Fine by me! It will be easier to review any follow up issues in smaller PRs.

**Comment by ashleyfae** [comment] 2020-04-23 06:51
Yes, let's do it!

**Closed** 2020-04-23 23:24 UTC
Labels: component-administration, component-orders, scope-ui, type-improvement, workflow-needs-lead-feedback
