### ISSUE TITLE
media-upload script enqueued for all custom post types

### ISSUE THREAD

**Issue by mgshaw** [easydigitaldownloads/Easy-Digital-Downloads#3534] opened 2015-06-29 15:09 UTC
Hi,

Sorry if this is a known issue, but I noticed that the 'media-upload' script appears to be enqueued on "post-new.php" and "post.php" for all post types (see includes/scripts.php on line 205). 

This messes up the styling of thickboxes on that page in one of my plugins, due to this known issue:

https://core.trac.wordpress.org/ticket/17249

I just wanted to open up a ticket here in case it could be limited on your end to only enqueue on specific post types.

**Comment by chriscct7** [comment] 2015-06-29 15:35
This is because `edd_is_admin_page` is returned as true on any post new or edit screen because of #2760 & #3033 & #2418 et al.

Here's what we could do that solves this issue:
1. Take edd_is_admin_page and only return true on EDD pages (not all post new/edit screens)
2. Introduce a new function that just does is post new/edit screen
3. Take the JS and CSS for "Insert Download" modal and put them in their own files. Then enqueue just them if the new function for 2 is true.
4. Take all of the other JS and CSS we enqueue and enqueue them more specifically using the new edd_is_admin_page improvements we're doing for 2.4
5. Introduce a filter by which the presence of the "Insert Download" modal can be turned off (turning off the HTML output, as well as the CSS and JS output.

This would solve many of our issues with backend plugin conflicts.

Thoughts @easydigitaldownloads/core-devs?

**Comment by pippinsplugins** [comment] 2015-06-29 15:39
Closing as duplicate of #3033. Definitely something we want to address.

**Closed by pippinsplugins** 2015-06-29 15:39 UTC
Labels: Bug
