### ISSUE TITLE
Adding display:none to price options breaks add to cart jQuery

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4653] opened 2016-06-03 00:51 UTC
Alright, this is one of the stranger bugs I've seen.

Let's say you have a download product with 5 price options, like this:
![screen shot 2016-06-02 at 7 45 37 pm](https://cloud.githubusercontent.com/assets/1034109/15765454/a235cd86-28fa-11e6-9277-8e62d551f829.png)

Now, for one reason or another, you decide that you want to hide the last two price options using CSS:
```css
.edd_price_options ul li:nth-child(4), .edd_price_options ul li:nth-child(5), .edd_price_options ul li:nth-child(6) {
	display: none;
}
```
This results in the price options rendering like this:
![screen shot 2016-06-02 at 7 46 50 pm](https://cloud.githubusercontent.com/assets/1034109/15765472/c4da8bba-28fa-11e6-9975-e714931baf71.png)

So far so good.

Now a customer comes along and selects `Price Three` and clicks add to cart. The cart widget and checkout now show that you have actually added `Price One` to the cart:

![screen shot 2016-06-02 at 7 48 03 pm](https://cloud.githubusercontent.com/assets/1034109/15765487/f0c76ebe-28fa-11e6-97b9-b2c209229f0e.png)

It does not matter which price option is selected, the first price option will _always_ be added to the cart so long as the CSS above is on the site.

Now, if that CSS is changed to this, it works fine:
```css
.edd_price_options ul li:nth-child(4), .edd_price_options ul li:nth-child(5), .edd_price_options ul li:nth-child(6) {
	height: 0;
	width: 0;
	overflow: hidden;
}
```
This CSS also works:
```css
.edd_price_options ul li:nth-child(4), .edd_price_options ul li:nth-child(5), .edd_price_options ul li:nth-child(6) {
	visibility: hidden;
}
```

The JS that handles the add to cart process is in `edd-ajax.js`. Here's the relevant section:
```js
if( variable_price == 'yes' ) {

	if ( form.find('.edd_price_option_' + download).is('input:hidden') ) {
		item_price_ids[0] = $('.edd_price_option_' + download, form).val();
		if ( form.find('.edd-submit').data('price') && form.find('.edd-submit').data('price') > 0 ) {
			free_items = false;
		}
	} else {
		if( ! form.find('.edd_price_option_' + download + ':checked', form).length ) {
			 // hide the spinner
			$this.removeAttr( 'data-edd-loading' );
			alert( edd_scripts.select_option );
			return;
		}

		form.find('.edd_price_option_' + download + ':checked', form).each(function( index ) {
			item_price_ids[ index ] = $(this).val();

			// If we're still only at free items, check if this one is free also
			if ( true === free_items ) {
				var item_price = $(this).data('price');
				if ( item_price && item_price > 0 ) {
					// We now have a paid item, we can't use add_to_cart
					free_items = false;
				}
			}

		});
	}

}
```

It appears that the `display:none` is effecting jQuery's ability to return proper results with `.find()`, but I have no idea why.

**Comment by DrewAPicture** [comment] 2016-06-03 01:43
So, my best guess is that all of the option selectors are match `.edd_price_option + download` with `input:hidden` *some* of them are considered “hidden” by jQuery because of the `display:none;`. Thus, the `item_price_ids` array is empty on AJAX post, defaulting to the first radio option.

**Comment by mintplugins** [comment] 2016-06-03 15:54
Just leaving a note with a customer who experienced this issue: https://secure.helpscout.net/conversation/206537181/34812/?folderId=180504

**Comment by pippinsplugins** [comment] 2016-06-03 15:58
Moving this up in priority.

**Comment by sunnyratilal** [comment] 2016-06-04 08:18
@DrewAPicture is correct. Using `.is(":hidden")` with jQuery checks if the element has a `display: none` attribute to it.   The reason `visibility: hidden` works in this case is because the `visibility` attribute still draws and creates the layout and to jQuery the element is _there_.  jQuery checks the dimensions of an element before declaring it as `hidden`. `display: none` zeros out the dimensions whereas `visibility: hidden` doesn't.

**Comment by pippinsplugins** [comment] 2016-06-04 13:13
Instead of using `:hidden` perhaps we could directly target an input that has `type="hidden"` instead.

**Comment by crissoca** [comment] 2016-06-21 16:03
I'm trying to create a fix for this, however I'm blocked, I want to test a scenario where this condition is met:

```javascript
    if ( form.find('.edd_price_option_' + download).is('input:hidden') ) {
        item_price_ids[0] = $('.edd_price_option_' + download, form).val();
        if ( form.find('.edd-submit').data('price') && form.find('.edd-submit').data('price') > 0 ) {
            free_items = false;
        }
    }
```

But I can't seem to find one.

So far this is my fix:

```javascript
		if( variable_price == 'yes' ) {

			if ( form.find('.edd_price_option_' + download + '[type="hidden"]').length > 0 ) {
				item_price_ids[0] = $('.edd_price_option_' + download, form).val();
				if ( form.find('.edd-submit').data('price') && form.find('.edd-submit').data('price') > 0 ) {
					free_items = false;
				}
			} else {
				if( ! form.find('.edd_price_option_' + download + ':checked', form).length ) {
					 // hide the spinner
					$this.removeAttr( 'data-edd-loading' );
					alert( edd_scripts.select_option );
					return;
				}

				form.find('.edd_price_option_' + download + ':checked', form).each(function( index ) {
					item_price_ids[ index ] = $(this).val();

					// If we're still only at free items, check if this one is free also
					if ( true === free_items ) {
						var item_price = $(this).data('price');
						if ( item_price && item_price > 0 ) {
							// We now have a paid item, we can't use add_to_cart
							free_items = false;
						}
					}

				});
			}

		} else {
			item_price_ids[0] = download;
			if ( $this.data('price') && $this.data('price') > 0 ) {
				free_items = false;
			}
		}
```

**Comment by pippinsplugins** [comment] 2016-06-22 02:53
@crissoca Have you set up the same configuration shown in my screenshot above?

**Comment by crissoca** [comment] 2016-06-22 03:25
@pippinsplugins I have and I'm able to reproduce the bug, but I trying to make sense on when this validation is needed, from what I can tell it looks for products with hidden value and check if it have a price and if it's bigger than 0

But I wanted to make a test scenario, my fix right now it's working I'm able to add the correct product even if the items are hidden, like you specified.

Just trying to do proper testing before creating a PR

**Comment by pippinsplugins** [comment] 2016-07-11 03:12
I'd have to test as I don't recall exactly, but I believe it's for purchase buttons added to the page with the price_id property: `[purchase_link id="X" price_id="1"]`

**Comment by crissoca** [comment] 2016-07-12 04:20
I think you are right, this shortcode `[purchase_link id="X" price_id="1"]` also uses the same script, I give it a test and everything seems to be working fine with my fix, I'll submit a pr in a sec.

**Comment by pippinsplugins** [comment] 2016-07-13 15:40
Thanks for the PR! We'll get it tested for the next point release.

**Comment by cklosowski** [comment] 2016-07-21 21:45
This seems to work great for me. I'm going to go ahead and merge it into master.

**Comment by cklosowski** [comment] 2016-07-21 21:46
Tested with Vendd's sidebar as well as including the `[purchase_link]` shortcode.

**Closed** 2016-07-21 21:46 UTC
Labels: Bug, Has PR, Needs Testing
