### ISSUE TITLE
Totals with discounts calculated differently by PayPal resulting in rounding discrepency

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5879] opened 2017-07-18 19:02 UTC
Reported by [a customer](https://secure.helpscout.net/conversation/399051513/63242/?folderId=180499) who explained that they had a 10% discount being applied to purchases of ten $69.99 items. The total pre discount is $699.90 and post discount on EDD is $629.91. But then you proceed to PayPal and it shows $629.90. If the customer completes the purchase this results in the IPN failing because the totals don't match.

Looking closer at what PayPal shows, I see that it is discounting each item and [using that as the item price](https://cloudup.com/cG9SmRk6kdb). In the end, EDD is not calculating exactly the same way that PayPal is and we're sometimes getting rounding errors.

Closely related to #3336

**Comment by cklosowski** [comment] 2017-07-18 19:07
The goal here, I believe is to get PayPal to show the exact same as EDD, not EDD to bend to PayPal, that way we're consistent for all gateways. The likely case is that the 10% discount is on the line item, and we're sending the discounted price to PayPal, not the full price and the discount amount.

**Comment by cklosowski** [comment] 2017-07-18 19:07
Moving to 2.8.5, the first few milestones for 2.8.x are reserved for 'fast fixes' after the 2.8 release.

**Comment by brashrebel** [comment] 2017-08-16 21:46
Just got another detailed message from the same customer linked to in description with some screenshots clearly demonstrating the difference between a correct and an incorrect transaction.

**Comment by cklosowski** [comment] 2017-09-26 15:55
Ok after digging into this pretty deeply, the main flaw we were getting was with our rounding when doing percentage discounts containing quantities. We were taking a discounted amount that might contain more than 2 decimal points...and then multiplying it.

This exposed without quantities but it's much easier to see with them.

Gateways like PayPal, that support quantity pricing, take the final item price and multiply it by the quantity.

Our discount calculation wasn't rounding the discounted amount before multiplying by quantity...so in the case of @brashrebel 's customer...the discount was coming out to:
`6.991` per item * 10, but after you multiply that...you get an extra penny in there...b/c `.001*10 = .01`

We just need to be sure to round the discounted amount.

**Comment by cklosowski** [comment] 2017-09-26 15:57
Things to test:
1) Flat rate discounts (both odd and even amounts $1.00 and $1.13)
2) Percentage discounts (both odd and even % like 10% and 11%)
3) Quantities (odd and even)

**Comment by pippinsplugins** [comment] 2017-09-26 16:29
Adding another item that has to be tested:

- Purchase with 5-10 separate items of varying amounts.

**Comment by mintplugins** [comment] 2017-10-19 22:15
Confirmed the initially reported scenario is reflecting the same amount in EDD and on Paypal Standard ($699.90).

**Comment by SDavisMedia** [comment] 2017-10-19 22:22
Same here. Also confirmed the same in Stripe and 2Checkout.

**Comment by mintplugins** [comment] 2017-10-19 22:25
I'm getting weird results with a flat rate

EDD Amount:
$698.77

Paypal Amount:
698.80

This is a $69.99 product in the cart with a quantity of 10 and a flat rate discount of 1.13

**Comment by pippinsplugins** [comment] 2017-10-19 22:25
I have tested:

1. Single $10 item with a flat $1.00 discount. Worked.
2. Single $10 item with flat $1.13 discount. Worked.
3. Single $10 item with flat $1.13 discount and a quantity of 10. This fails:
<img width="770" alt="screen shot 2017-10-19 at 5 22 10 pm" src="https://user-images.githubusercontent.com/1034109/31797152-7b3c012a-b4f2-11e7-9a39-4f6953c151ee.png">
<img width="838" alt="screen shot 2017-10-19 at 5 22 13 pm" src="https://user-images.githubusercontent.com/1034109/31797153-7b63a7fc-b4f2-11e7-8f1d-06910cab38f5.png">

**Comment by cklosowski** [comment] 2017-10-19 22:26
Ok let's punt this until we can get a little more testing done on it after I fix that.

**Comment by pippinsplugins** [comment] 2017-10-19 22:26
:+1:

**Comment by sunnyratilal** [comment] 2017-10-19 22:28
Tested and got the same results as @pippinsplugins. Flat rate with quantity failed.

**Comment by pippinsplugins** [comment] 2017-10-26 19:58
I have a customer reporting this error:

>>>Error: Transaction refused because of an invalid argument. See additional error messages for details. The totals of the cart item amounts do not match order amounts.

That is happening with PayPal Pro and PayPal Express. The error occurs because rounding is wrong. For the example order where I replicated it, the amount was supposed to be 33.50 but PayPal received 33.49.

The attached PR did not, unfortunately, fix it.

**Comment by pippinsplugins** [comment] 2017-10-26 20:08
Ignore my issue above. It's an extension bug:

**Comment by SDavisMedia** [comment] 2018-03-06 03:54
I tested with the numbers here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5879#issuecomment-338055157

Payments are completing and I'm seeing the $0.03 discount over on PayPal. So everything checks out. This feels really dirty but I don't have a better solution. I worry about reports, though. EDD's reports should be fine but PayPal's data would have to be inaccurate with this approach.

**Comment by cklosowski** [comment] 2018-03-12 19:31
@pippinsplugins Yeah I think I'm ok with this. It's ugly, but I don't know of a better way around it.

**Comment by mintplugins** [comment] 2018-03-13 20:49
I'm getting the same results here with the $0.03 discount at paypal
<img width="466" alt="screen shot 2018-03-13 at 4 47 12 pm" src="https://user-images.githubusercontent.com/1638128/37369051-58f5082e-26de-11e8-9a05-44bf4e0eab13.png">


I think this is definitely a temporary fix until #6419 hopefully solves it in a little bit strange of a way.

**Comment by cklosowski** [comment] 2018-03-13 20:52
:+1: going ot merge this then.

**Closed** 2018-03-13 20:52 UTC
Labels: Bug, Discounts, Has PR, Needs Testing, PayPal, Priority: High
