### ISSUE TITLE
Cache busting cookies: edd_items_in_cart

### ISSUE THREAD

**Issue by clifgriffin** [easydigitaldownloads/Easy-Digital-Downloads#3172] opened 2015-02-19 22:21 UTC
I've started using fastcgi caching with Nginx over caching plugins.  The down downside of this is that Nginx will not cache any page or serve a cached page for any request with a Set-Cookie, and unlike Varnish, you can't exclude cookies from the cache.

I've noticed that every page request on sites with EDD includes a Set-Cookie header from EDD in the form of `edd_items_in_cart`.  It defaults to `deleted`, but if any items are in the cart it is set to that number.

I can't figure out why it would be necessary to set this cookie on every single request, especially when a user hasn't initiated any shopping actions.  Nor does it feel like the kind of data that needs to be in a cookie. 

With EDD's strong AJAX coverage, I'd think there would be plenty of ways to avoid this entirely. 

(I'm not sure if EDD uses PHP sessions, but if so the same would apply for first page requests that cause a new session. That's harder to solve though.)

**Comment by pippinsplugins** [comment] 2015-02-19 22:23
This is a bug and is unintentional.

**Comment by pippinsplugins** [comment] 2015-02-19 22:23
We definitely need to fix it.

**Comment by cklosowski** [comment] 2015-03-13 00:38
With the PR attached here ( #3197 ) we'll have to do some good testing. @clifgriffin can you submit this to the `release/2.4` branch instead of master? With 2.3 just going out we're trying to keep merges into master at a minimum as to allow for quick bug fixes.

**Comment by pippinsplugins** [comment] 2015-06-17 20:40
Things to test before merge:
- [ ] WPEngine
- [ ] Pagely
- [ ] W3 Total Cache
- [ ] WP Super Cache
- [ ] WP Rocket

**Comment by pippinsplugins** [comment] 2015-06-17 20:41
We have merged in for testing but all cases above must be tested before closing this.

**Comment by cklosowski** [comment] 2015-06-22 05:24
I've tested GoDaddy Managed and it's working fine on there.

**Comment by pippinsplugins** [comment] 2015-06-23 19:11
Works great on Pagely.

**Comment by cklosowski** [comment] 2015-06-23 19:12
If someone has a WPEngine account they can test with, I'm having issues with mine showing empty carts, on `master` even.

**Comment by pippinsplugins** [comment] 2015-06-23 19:15
I'll be able to test on mine.

**Comment by pippinsplugins** [comment] 2015-06-29 17:46
Testing on WPEngine now.

**Comment by pippinsplugins** [comment] 2015-06-29 17:50
It works on my localhost with WP Super Cache.

**Comment by mindctrl** [comment] 2015-06-29 17:57
Setting up for W3TC testing now.

**Comment by pippinsplugins** [comment] 2015-06-29 17:59
It's failing on WPEngine for me.

**Comment by clifgriffin** [comment] 2015-06-29 17:59
I've found that WP Engine aggressively caches cookies. Depending on the nature of failure, it might require having them whitelist EDD cookies?

**Comment by pippinsplugins** [comment] 2015-06-29 18:00
We've had out cookies white listed already (since a year or more ago).

**Comment by pippinsplugins** [comment] 2015-06-29 18:00
Assuming they didn't remove the whitelist.

**Comment by clifgriffin** [comment] 2015-06-29 18:01
@pippinsplugins Ah, nice.

**Comment by pippinsplugins** [comment] 2015-06-29 18:07
Pretty sure that WP Engine is working properly, just getting them to exclude my checkout page from caching so I can confirm.

**Comment by pippinsplugins** [comment] 2015-06-29 18:15
just confirmed that having the checkout page excluded from caching on WPEngine resolves the issue.

**Comment by pippinsplugins** [comment] 2015-06-29 18:17
WP Rocket works great.

**Comment by pippinsplugins** [comment] 2015-06-29 18:17
All good here!

**Closed by pippinsplugins** 2015-06-29 18:17 UTC
Labels: Bug, Needs Testing
