### ISSUE TITLE
3.0 - View order Details: 

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6811] opened 2018-07-30 17:56 UTC
### Expected behavior
Order Amounts section should display without an overlap

### Actual behavior
The labels on the Order Amounts section can run over on some OS/Browser combinations. Keep in mind this may change quite a bit when we have translated strings.
![image](https://user-images.githubusercontent.com/1390124/43414284-f4b176e0-93f7-11e8-9a0a-9be65efae3a2.png)

### Steps to reproduce the behavior
1) View order Details

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:
I was using Linux with FireFox to have the above outcome.

**Comment by sunnyratilal** [comment] 2018-08-01 06:47
Closing as this is a duplicate of #6787

**Closed by sunnyratilal** 2018-08-01 06:47 UTC
Labels: Administration, Bug
