### ISSUE TITLE
Make Discount Codes restrict-able by category. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5870] opened 2017-07-13 14:34 UTC
Right now you can restrict a discount code so that it can only be used for specific products. 

A customer has requested that there also be an option to limit a discount code so that it can only be used for products in a specific category(s).

**Comment by pippinsplugins** [comment] 2017-07-13 16:17
Duplicate of #5015

**Closed by pippinsplugins** 2017-07-13 16:17 UTC
Labels: Enhancement
