### ISSUE TITLE
Billing state/province select field 

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/easy-digital-downloads#7183] opened 2019-03-12 17:08 UTC
### Expected behavior
Switching between a Country with predefined states to a Country with no defined states should work correctly

### Actual behavior
If you select a Country like USA and choose a state, after that you select a Country with no set States like Albania will not change the "state" field to an input text field

### Steps to reproduce the behavior
1) On the [edd_profile_editor] page try to change your country.
2) Selecting a country with no set states does not change the fields to a text input.
3) The same issue seems to occur when you try to change back to a country with set states like USA

### Information (if a specific version is affected):
PHP Version: 7.2.1

EDD Version (or branch): master branch

WordPress Version: 5.1

Any other relevant information:
Reported by customer here: https://secure.helpscout.net/conversation/797535668/102531/ and he does mention a possible fix but that does not work for me. The fields do not change at all.

**Comment by cklosowski** [comment] 2019-03-12 18:29
@misulicus has tested and confirmed it, but I need 2 more confirmations of the fix @mintplugins @SDavisMedia @dgoldak if you can help out here.

**Comment by misulicus** [comment] 2019-03-12 18:30
Yep confirmed fixed for checkout page and on the profile editor page [edd_profile_editor]

**Comment by dgoldak** [comment] 2019-03-12 18:32
Testing...

**Comment by dgoldak** [comment] 2019-03-12 18:52
The checkout page works for me but [edd_profile_editor] does allow non-US states.

<img width="541" alt="Screen Shot 2019-03-12 at 1 52 07 PM" src="https://user-images.githubusercontent.com/30910807/54227508-0c30fe80-44ce-11e9-8240-47aa8103505e.png">

**Comment by cklosowski** [comment] 2019-03-12 18:54
@dgoldak please be sure to clear all caches, this appears that you are not getting the field reset.

**Comment by dgoldak** [comment] 2019-03-12 19:28
I checked on my local site and both checkout and [edd_profile_editor] are working as expected. 

What I ran into above must have been something unique about my site, such as unexpected caching.

**Comment by mintplugins** [comment] 2019-03-12 19:42
Interestingly, I could not replicate this if I had Recurring Payments+Stripe, and a Stripe Saved Card.It worked there, but there were lots of unhappy notices from the browser:

<img width="1439" alt="Screen Shot 2019-03-12 at 3 38 48 PM" src="https://user-images.githubusercontent.com/1638128/54230526-f24ae800-44dc-11e9-83a0-2a1cf5d3a285.png">

When I disabled Recurring Payments and Stripe, I could then replicate on `master` of EDD core. 

<img width="574" alt="Screen Shot 2019-03-12 at 3 40 26 PM" src="https://user-images.githubusercontent.com/1638128/54230633-2de5b200-44dd-11e9-86e6-5f5d69a5e61d.png">

Confirmed fixed on `issue/7183`
<img width="586" alt="Screen Shot 2019-03-12 at 3 41 36 PM" src="https://user-images.githubusercontent.com/1638128/54230720-5ff71400-44dd-11e9-9ba9-4e337f56606c.png">

**Comment by SDavisMedia** [comment] 2019-03-12 20:43
I could only replicate this on `master` on Checkout. I couldn't replicate on `[edd_profile_editor]`. Furthermore, I could only replicate by switching from US to Albania (or any country with no States/Province list) and having it _successfully_ switch to text input, but then failing to load the `select` menu when switching back to US.

Regardless, everything works as expected on `issue/7183`. 👌

**Closed** 2019-03-14 22:52 UTC
Labels: Bug, Checkout, Has PR, Needs Testing
