### ISSUE TITLE
Multiple instances of variable product form causes label target issue

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#3598] opened 2015-07-10 16:46 UTC
When there are multiple instances of the [purchase_link] shortcode on a page for the same variable product, clicking on the labels takes you to the first instance of the shortcode instead of just selecting the radio option as I suspect a user would expect.

For users with long sales pages and repeated calls to action throughout, this creates a potentially confusing experience.

**Comment by cklosowski** [comment] 2016-05-16 20:53
@brashrebel there is a caveat to this without some extra JS involved. The issue is that, while we make the IDs on the forms themselves unique, we weren't making the inputs themselves, so the `labels` all had the same `id` attributes, by appending the `form_id` to the `input` `ids` we can make it so the labels work with the same form. They caveat is that picking a price ID on one form, will not update the other form without some JS.

@easydigitaldownloads/core-devs are we ok with that?

**Comment by pippinsplugins** [comment] 2016-05-16 20:55
Why not just update the labels with the ID? That doesn't require any JS.

**Comment by cklosowski** [comment] 2016-05-16 20:56
@pippinsplugins that's what I'm doing...however it won't update both forms when you select an item. You cannot have two elements with the same `id`, by doing so you break HTML compliance, and also, no matter what, clicking on a label on any non-first form will scroll you to the first form.

**Comment by cklosowski** [comment] 2016-05-16 20:57
I'll commit what I have for testing.

**Comment by SDavisMedia** [comment] 2016-05-18 18:50
Replicated and confirmed fix for me on `issue/3598`. Also tested adding price options to the cart from multiple purchase forms to make sure the right item was being added. All good.

**Comment by cklosowski** [comment] 2016-05-18 19:03
@SDavisMedia can you test again? Had to fix a merge conflict and want to make sure I didn't break anythign after re-adding the schemea stuff that was merged.

**Comment by SDavisMedia** [comment] 2016-05-18 19:10
@cklosowski All good still after pulling `issue/3598` down again.

**Comment by cklosowski** [comment] 2016-05-20 17:50
@brashrebel does this resolve the initial issue for you? If so i'll merge and close this out

**Comment by pippinsplugins** [comment] 2016-05-20 19:35
Merged and closing. Will re-open if @brashrebel notices anything.

**Closed by pippinsplugins** 2016-05-20 19:35 UTC
Labels: Bug, Frontend, Has PR, Needs Testing

**Comment by brashrebel** [comment] 2016-05-21 16:14
Confirmed fixed for me in `release/2.6`.

**Comment by cklosowski** [comment] 2016-05-21 17:53
Thanks @brashrebel
