### ISSUE TITLE
Key in Payment Meta array not updated to correct key after 2nd attempt to purchase

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/easy-digital-downloads#5745] opened 2017-05-18 01:02 UTC
First a bit of background. In the AffiliateWP account section there's a button for downloading AffiliateWP. This is only shown if a download URL can be built using `edd_get_download_file_url()`, which takes the payment key. In short, the customer could not see the button at all to download AffiliateWP even though they had a valid purchase etc. `edd_get_download_file_url()` just returned `false`.

I discovered that on the EDD order, the `key` shown in the `Payment Meta` metabox did not match that the payment key in the `_edd_payment_meta` array. It's slipping my mind but I'm pretty sure the `_edd_payment_purchase_key` meta key showed the correct one. After changing the key in the `_edd_payment_meta` array, `edd_get_download_file_url()` was able to build out the download link and the button then appeared for the customer, hooray.

So it seems that a payment key was recorded initially for the first unsuccessful payment by the customer. When they purchased again, the new key was added, but it did not update the `_edd_payment_meta` array. The keys should match, correct?

Here's the order where I fixed the Key in the DB directly:
https://affiliatewp.com/wp-admin/edit.php?post_type=download&page=edd-payment-history&view=view-order-details&id=163496

You can see `Payment recovery triggered URL` mentioned a few times in the payment notes.

**Comment by cklosowski** [comment] 2017-05-18 01:31
Will look into this @sumobi

**Comment by cklosowski** [comment] 2017-05-22 22:25
I'm not sure how to replicate this at the moment. We have code specifically around the payment recovery process (which the payment above used), that should just take the old payment key from the initial purchase process.

Locally I tried this and i got the same purchase key each time. Going to keep trying though, using different emails, waiting, X number of minutes, etc.

**Comment by cklosowski** [comment] 2017-05-22 22:42
Tested with a separate email address on recovery than the initial payment and it was the correct payment key in both the `_edd_payment_meta[key]` and `_edd_payment_purchase_key` meta.

**Comment by cklosowski** [comment] 2017-05-22 23:01
@pippinsplugins can you see if you can replicate this locally? I'm not able to.

**Comment by cklosowski** [comment] 2017-05-22 23:03
The steps I've tried
1) Add item to cart
2) Choose PayPal Express at checkout
3) Once at the paypal site, close the tab
4) Use the payment recovery system (view in admin or payment history)
5) Purchase with a different email address on chekcout
6) Verify `_edd_payment_purchase_key` and `_edd_payment_meta[key]` match

**Comment by pippinsplugins** [comment] 2017-05-22 23:45
This sounds exactly like https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5472

**Comment by cklosowski** [comment] 2017-05-22 23:47
It really does, but this happened to @sumobi  like last week...which raises the question if there is still a way to make it happen.

**Comment by cklosowski** [comment] 2017-05-22 23:48
Strike that...the purchase was from February....derp. Could have completely been fixed by the issue mentioned by @pippinsplugins

**Comment by cklosowski** [comment] 2017-05-22 23:48
@sumobi going to close for now as a duplicate of #5472 until we see it happen again.

**Closed by cklosowski** 2017-05-22 23:48 UTC
Labels: Bug
