### ISSUE TITLE
Custom jQuery UI enqueued on all post-new.php and post.php pages

### ISSUE THREAD

**Issue by glennansley** [easydigitaldownloads/easy-digital-downloads#3033] opened 2015-01-30 14:27 UTC
Hey,
Are you guys intending to enqueue your custom jQuery UI styling on all post-new.php and post.php pages regardless of the post_type? It looks like it's being enqueued if edd_is_admin_page() returns true (line 209 of includes/scripts.php)... and edd_is_admin_page() is returning true on non EDD admin pages like post-new.php.

I see where I could modify the result of edd_is_admin_page() via the filter with the same name if I need to, but wanted to make sure this was your intention first because it seemed a bit greedy and imprecise. :)

Thanks!

**Comment by pippinsplugins** [comment] 2015-01-30 15:46
This is intentional, though we don't like it. It's done for the reasons described in #2418, specifically this comment: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/2418#issuecomment-50677419

I'd love to improve it but have never come up with a good solution.

**Comment by glennansley** [comment] 2015-01-30 16:14
Gotcha. Yeah. that's tough. I realize there a probably other implications besides the jquery custom UI inside that block of code that enqueues scripts for you, so this won't cover everything, but you could possibly scope the custom jQuery UI rules to your divs with the CSS Scope option on http://jqueryui.com/download/. That might be worth looking into. We probably need to do the same thing where we use it.

**Comment by pippinsplugins** [comment] 2015-01-30 16:45
Oh, that's an interesting idea. We'll keep this open and scope it out for 2.4.

**Comment by pippinsplugins** [comment] 2015-02-10 23:33
Duplicate of #3033

**Comment by rnovotny** [comment] 2016-07-14 00:01
@pippinsplugins We are running in to some minor conflicts w/ Easy Pricing Tables.  Can't you just change this line: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/admin-pages.php#L343

from

`if ( 'download' == $typenow || 'index.php' == $pagenow || 'post-new.php' == $pagenow || 'post.php' == $pagenow ) {`

to

`if ( 'download' == $typenow || ( ( $typenow == 'post' || $typenow == 'page' ) && ( 'index.php' == $pagenow || 'post-new.php' == $pagenow || 'post.php' == $pagenow )) ) {`

**Comment by pippinsplugins** [comment] 2016-07-14 16:05
No because we need it on custom post types for our `Insert Download` pop up window. That's where the real struggle in how to resolve this comes in.

**Comment by sunnyratilal** [comment] 2017-01-14 21:15
Punting to 2.7.3 for further discussion

**Comment by cklosowski** [comment] 2018-03-05 17:43
Just an opinion here. I think when Gutenberg hits Core, this could be something we can 'stop' doing by building a block that performs the same as the `Insert Download` pop-up. By converting it to a Gutenberg block, we don't need the jQuery UI aspect of it particularly, if we build it in a way that isolates loading the scripts/styles (if we still need them).

**Comment by cklosowski** [comment] 2018-03-12 22:17
Punting so we can have some discussion about the future of this `Insert Download` feature into something that aligns with the future of the WP Editor.

**Comment by JJJ** [comment] 2018-08-18 04:36
Closing this. Style are no longer enqueued on every page in EDD3.0.

Thanks everyone!

**Closed by JJJ** 2018-08-18 04:36 UTC
Labels: Enhancement
