### ISSUE TITLE
EDD_Download update_meta fails for 0 integer values

### ISSUE THREAD

**Issue by rahilwazir** [easydigitaldownloads/easy-digital-downloads#6745] opened 2018-07-11 02:56 UTC
### Expected behavior
When I use the function `edd_decrease_purchase_count( 123 )` I expect it to decrease the sales count by 1 for the product 123, thus resulting into 0 sales.

### Actual behavior
It does not decreases the sales count (only when the product have 1 sale). When I checked under the hood, the [`EDD_Download::update_meta`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-download.php#L853) method has `empty()` construct for `$meta_value`, so in this case `$meta_value = 0` (as [`EDD_Download::decrease_sales`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-download.php#L688)) and it fails.

```
$total_sales = $this->get_sales() - $quantity;
                       |                |
                       |                |
                      \|/              \|/
                       1          -     1      = 0
```

### Steps to reproduce the behavior
1) Enable product quantity (Optional, defaults to 1 anyway)
2) Purchase the product
3) Run the following function on `init` hook (for testing) with the purchased product id, i.e. `edd_decrease_purchase_count( 123 );`

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): 2.9.4

WordPress Version: 4.9.7

**Comment by cklosowski** [comment] 2018-09-06 20:44
This is ready for testing, easy steps here:
1) Have a product with a single sale count (1).
2) Via Debug Bar Console run the following `var_dump( edd_decrease_purchase_count( <download_id> ) );`

On `master`:
This will result in a `false` return as the update failed to run.

On `issue/6745`:
This will result in a return of `0`, and the new purchase count of the product will be `0`, since the update was allowed to be processed.

**Comment by SDavisMedia** [comment] 2018-09-06 23:40
Replicated on `master`. Confirmed fixed on `issue/6745`. :+1:

**Closed** 2018-09-07 02:12 UTC
Labels: Bug, Has PR, Needs Testing
