### ISSUE TITLE
Admin Feature: Refresh reports button

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/easy-digital-downloads#3812] opened 2015-09-17 23:08 UTC
Report data is stored in transients. If a user has a busy site, it's helpful that they have a way to refresh reports and clear the transient cache. How about a button like this?

![refresh-button](https://cloud.githubusercontent.com/assets/1571635/9948133/33aa4b10-5d55-11e5-97d3-e40ad7608856.png)

and once the cache is cleared:

![9-17-2015 4-06-30 pm](https://cloud.githubusercontent.com/assets/1571635/9948226/231a2e7c-5d56-11e5-8578-7f25c405a41f.png)

This can be achieved with code like this:

```
/**
 * EDD Reports Refresh Button
 * @description: Outputs a "Refresh Reports" button for graphs
 */
function edd_reports_refresh_button() {

    $url = wp_nonce_url( add_query_arg( array(
        'edd_action'  => 'refresh_reports_transients',
        'edd-message' => 'refreshed-reports'
    ) ), 'edd-refresh-reports' );

    echo '<a href="' . $url . '" data-tooltip="' . __( 'Clicking this will clear the reports cache.', 'edd' ) . '" data-tooltip-my-position="right center"  data-tooltip-target-position="left center" class="button alignright edd-refresh-reports-button edd-tooltip">' . __( 'Refresh Reports', 'edd' ) . '</a>';

}

add_action( 'edd_reports_graph_additional_stats', 'edd_reports_refresh_button' );

/**
 * Trigger the refresh of reports transients
 *
 * @since 1.3
 *
 * @param array $data Parameters sent from Settings page
 *
 * @return void
 */
function edd_run_refresh_reports_transients( $data ) {

    if ( ! wp_verify_nonce( $data['_wpnonce'], 'edd-refresh-reports' ) ) {
        return;
    }

    //Delete transients
    delete_transient( 'edd_estimated_monthly_stats' );
    delete_transient( 'edd_earnings_total' );
    delete_transient( md5( 'edd_earnings_this_monththis_month' ) );
    delete_transient( md5( 'edd_earnings_todaytoday' ) );

}

add_action( 'edd_refresh_reports_transients', 'edd_run_refresh_reports_transients' );
```

...Then change this here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/payments/functions.php#L689

to:

```
    if ( ! empty( $_GET['_wpnonce'] ) && wp_verify_nonce( $_GET['_wpnonce'], 'edd-refresh-reports' ) ) {
        $earnings = false;
    } else {
        $earnings = get_transient( $key );
    }
```

I have it working in this branch on Give: https://github.com/WordImpress/Give/tree/issue/210

The issue stems from complaints like this: https://github.com/WordImpress/Give/issues/85

LMK if you'd be interested in this functionality with in EDD and I can submit a PR :smile:

**Comment by mindctrl** [comment] 2015-09-17 23:23
If we do this, I'd like to see the notice use a more end user friendly tone like the button does. Something like "The reports have been refreshed".

**Comment by DevinWalker** [comment] 2015-09-17 23:25
@mindctrl yeah for sure. My language is a little less user friendly.

**Comment by pippinsplugins** [comment] 2015-09-18 13:45
Nice idea, I like it.

**Comment by cklosowski** [comment] 2015-09-18 16:50
Yes, looks like a great addition. Thanks @DevinWalker.

**Comment by DevinWalker** [comment] 2015-09-18 18:09
Glad you guys like it. I'll submit a PR soon!

**Comment by michaelbeil** [comment] 2015-09-18 18:20
This is really great @DevinWalker!

**Comment by SDavisMedia** [comment] 2016-05-18 17:44
Super slick, @DevinWalker. :+1:

The refresh button only shows on the default **Report Type** display for the Reports tab and the **Earnings** display. The information from the other selections like **Earnings by Category** should be pulling from the same data. I think the refresh button should show on all pages since all the data will be refreshed.

Also, unfortunately, the PR is a little old now. That's our fault so we definitely apologize for that. But do you think you could refresh your PR with `master`? Things like the text domain need to be updated from `edd` to `easy-digital-downloads`.

**Comment by pippinsplugins** [comment] 2016-05-18 17:47
We can also refresh ourselves if time is short for Devin.

**Comment by michaelbeil** [comment] 2016-05-18 18:28
I made a comment here as well about updating the title of the refresh reports button: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/3822#issuecomment-220101712

**Comment by sunnyratilal** [comment] 2017-01-14 21:23
Merged into `release/2.7`

**Comment by pippinsplugins** [comment] 2017-02-02 18:20
This doesn't seem to work.

Today from dashboard widget: $1,179.40
Today from reports graph: $496

Clicking refresh doesn't change anything.

**Comment by cklosowski** [comment] 2017-02-02 18:21
We probably just missed a transient or something. @sunnyratilal can you take a look?

**Comment by sunnyratilal** [comment] 2017-02-06 20:47
Correct transients are being deleted. Just tested myself and the stats refreshed correctly.

**Comment by sunnyratilal** [comment] 2017-02-06 20:50
`edd_stats_earnings` and `edd_stats_sales` are the two transients that handle all the data for reports. Both are being deleted https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.7/includes/admin/reporting/graphing.php#L967-L980

**Comment by pippinsplugins** [comment] 2017-02-07 06:17
This may be working and, instead, be a mis-identified issue caused by #1980

**Comment by pippinsplugins** [comment] 2017-02-08 17:47
Confirmed it was an issue with #1980, not this.

**Closed by pippinsplugins** 2017-02-08 17:47 UTC
Labels: Administration, Reports
