### ISSUE TITLE
User Agent Logging

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5426] opened 2017-01-31 20:37 UTC
Within the download log it would be useful to store the user agent for the following purposes:

- To have a general idea of the users browser and OS to help diagnose support requests/queries with downloading and/or other website related issues.

- It's useful for identifying fraudulent transactions and users intending to "pirate" downloadable products, since most will attempt to spoof the user agent.

For display purposes it doesn't make sense to put it in the admin panel since space is lacking, but certainly on the download history CSV export.

**Comment by pippinsplugins** [comment] 2017-01-31 21:46
I agree, good idea.

**Comment by cklosowski** [comment] 2017-08-21 22:44
This is a duplicate of #5617, since it contains other improvements, I'm going to close this as the duplicate. In order for the download history export to contain the User Agent, we'll have to store it in the logs anyway.

**Closed by cklosowski** 2017-08-21 22:44 UTC
Labels: Administration, Enhancement, Priority: Low, Reports
