### ISSUE TITLE
Changing payment status to refund no longer shows the "Refund in Gateway" option. Requires manually refunding again.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#6451] opened 2018-03-22 01:49 UTC
Updated a few days ago to v2.9 and all of our extensions are updated as well. Using PayPal Standard and when I went to refund a renewal payment the typical checkbox to also refund the payment via paypal didn't appear.

Thought it may have been new to just assume and do it automatically but I had to do it manually via PayPal.

**Comment by danieliser** [comment] 2018-03-22 01:52
Also side note, after I manually refunded I don't see any changes in the payment based on paypal API calls. IE license keys are still active, no note of payment refunded etc.

I can give a full list of extensions. No JS errors on page, no PHP errors in logs.

**Comment by danieliser** [comment] 2018-03-22 03:59
Want to add that this only appears to be an issue on renewal payments. Just refunded another correctly from a normal first time purchase.

**Comment by cklosowski** [comment] 2018-03-22 22:19
@danieliser This was a payment logged via recurring payments that cannot be refunded?

**Comment by danieliser** [comment] 2018-03-23 04:36
@cklosowski From all the usage I have had of the newest version that would be my diagnosis.

I had to manually refund a renewal payment and deactivate the licenses etc.
- Prior to changing status to refunded and having to do all of this I had hard refreshed, logged out and back in and basic debugging to ensure it wasn't something like that. The checkbox I expected to appear simply wasn't in the html.

Refunded another 2 payments later that day that were initial purchases and the checkbox appeared correctly and payments auto refunded via paypal.

Keeping an eye on it, will report next refund what I see.

**Comment by mindctrl** [comment] 2018-03-23 05:04
I saw this on a PayPal renewal too. The box appears on renewal payments from Stripe, but not PayPal.

**Comment by cklosowski** [comment] 2018-03-23 18:26
This is actually a recurring bug. Recurring is not adding the `payment mode` to the payments it creates in `EDD_Subscription->add_payment`. Because of this, this line is failing:
```
	$key       = edd_get_payment_meta( $payment_id, '_edd_payment_mode', true );
	$username  = edd_get_option( 'paypal_' . $key . '_api_username' );
	$password  = edd_get_option( 'paypal_' . $key . '_api_password' );
	$signature = edd_get_option( 'paypal_' . $key . '_api_signature' );
```

Confirmed on EDD's live site:
```
<?php
var_dump(edd_get_payment_meta( 1213173, '_edd_payment_mode', true ) );
string(0) ""
```
Since the mode is empty, the option values are invalid. Closing to open on Recurring. Since test and live could occur on the same site....we cannot assume `live` or `test`. We can fix this going forward for recurring payments with a fix in EDD Recurring.

**Closed by cklosowski** 2018-03-23 18:26 UTC
Labels: Bug, PayPal, Payments
