### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by boluda** [easydigitaldownloads/easy-digital-downloads#6717] opened 2018-07-07 08:38 UTC
### Expected behavior
When I run the file download logs database upgrade the file download logs database or recount stats, I expect it to work.

### Actual behavior
Both trigger a PHP Fatal error.

### Steps to reproduce the behavior
1) Try to run any important upgrade like file download logs database, reset the shop or recount shop stats.
2) Shop with 82.337 payments.
3) Even with 128MG it's not enough.
4) This is the error
[07-Jul-2018 08:19:57 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 133883136 bytes) in /usr/home/web/wp-includes/wp-db.php on line 1924

### Information (if a specific version is affected):
PHP Version: 7.0
EDD Version (or branch): 2.9.3
WordPress Version: 4.9.7

**Comment by pippinsplugins** [comment] 2018-07-10 02:32
Going to close this one as a duplicate of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6731

That issue has more details on it.

**Closed by pippinsplugins** 2018-07-10 02:32 UTC
Labels: Bug

**Comment by boluda** [comment] 2018-07-10 03:14
Thanks!
