### ISSUE TITLE
Verify all countries exist in the .pot file.

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#7798] opened 2020-04-29 16:17 UTC
### Explain your enhancement 
~Add Varese and Monza e Brianza to the translation file.~
Verify all countries able to be translated are in the .pot file distributed.

### Justification or use case
~They are spelled different in Italy.~
Some of the countries are missing, like these examples.

> "Varesa" instead of "Varese"
> "Monza e della Brianza" instead of "Monza e Brianza" 

https://secure.helpscout.net/conversation/1148474393/152200?folderId=180499

**Comment by cklosowski** [comment] 2020-05-05 18:41
Since this is going to affect the translation files, and 3.0 will require a lot of updates to the translations, we should get this in for the big set of translation updates that will need to be done.

**Comment by dgoldak** [comment] 2020-05-05 18:46
I'm wondering if this should be updated make sure all countries are added to the translation file? Another customer needs to translate more countries that do not currently exist in the pot file.

https://secure.helpscout.net/conversation/1147870011/152139?folderId=1847242

**Comment by ashleyfae** [comment] 2021-03-12 07:36
Just noting that the issue is the strings are not translation-ready.

**Comment by ashleyfae** [comment] 2021-05-20 12:16
See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4934 specifically https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4934#issuecomment-249626433

**Comment by ashleyfae** [comment] 2021-05-20 12:16
Actually closing this in favour of that one.

**Closed by ashleyfae** 2021-05-20 12:16 UTC
Labels: scope-i18n
