### ISSUE TITLE
3.0 Reports: Longer range reports not grouping by month

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6792] opened 2018-07-23 15:06 UTC
For example: A date range of 2017-01-01 to 2018-07-20

![image](https://user-images.githubusercontent.com/1254870/43085221-6da610d2-8e68-11e8-8ddd-91cb40bcf29e.png)

Shows a chart like this, with every day itemized:
![image](https://user-images.githubusercontent.com/1254870/43085235-75c31d3c-8e68-11e8-840c-975acc0c2d38.png)

It should be grouped by month.

**Comment by cklosowski** [comment] 2018-07-24 01:55
Seems like our `$day_by_day` value is getting set to `true` when it should be `false` somewhere.

**Comment by SDavisMedia** [comment] 2018-07-24 19:40
I'm curious why this should be grouped by month (besides for obvious visual reasons). Is it just that it's expected behavior based on the code, and therefore this is a bug? Or is it because of the display issue?

I definitely don't want it to display the way it does, but I understand why it displays this way. 

When using the custom filter over random date ranges, what determines if it should be day by day or month by month? What if the filter covers 3 months? What about 6 months?

**Comment by sunnyratilal** [comment] 2018-07-25 00:35
The logic was incorrect here to start with. Currently any range longer a year gets grouped by month. The is fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/c730f15bd7d3acf2a51bf4fb1edecc54454ef8ca.

However, our logic currently sets anything longer than a quarter of a range to be grouped by month as shown here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/reports/reports-functions.php#L754-L787

My vote is to adjust the condition on line 775 to be `$difference >= ( YEAR_IN_SECONDS / 4 )`.

Interested in yours thoughts @SDavisMedia and @mindctrl.

**Comment by sunnyratilal** [comment] 2018-07-25 00:36
The logic was incorrect here to start with. Currently any range longer a year gets grouped by month. This fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/c730f15bd7d3acf2a51bf4fb1edecc54454ef8ca.

However, our logic currently sets anything longer than a quarter of a range to be grouped by month as shown here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/reports/reports-functions.php#L754-L787

My vote is to adjust the condition on line 775 to be `$difference >= ( YEAR_IN_SECONDS / 4 )`.

Interested in your thoughts @SDavisMedia and @mindctrl.

**Comment by sunnyratilal** [comment] 2018-08-09 21:59
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/5e975dba996faff6fc38c60723c009d09da01882.

**Closed by sunnyratilal** 2018-08-09 21:59 UTC
Labels: Bug, Reports
