### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rolero** [easydigitaldownloads/easy-digital-downloads#6234] opened 2017-12-18 09:35 UTC
We noticed when using the "import downloads" module within the admin tools section that every time that we import a file, we need to setup the mapping manual. The file format of each file that we offer is every time the same. We ensured that the column names match with those that EDD expects. We want to reduce repeating manual work. Would be great if the import tool recognizes the column names within the CSV file and auto-maps them if possible.

Import section within EDD admin tools:
https://pasteboard.co/GYL3SqY.png

View of the option list that shows mathing values. Why not auto select :)
https://pasteboard.co/GYL4jAO.png

Example of the csv file (printscreen)
https://pasteboard.co/GYL4Z3Z.png

**Why we need this?**

We continuously sync the platform that runs EDD with an external 3th party platform. We check which downloads we did not import yet using the EDD API and check the SKU values already in EDD. Based on the outcome we query which files we need to import and create and export file. That file we import into EDD. "

**What we actually need**
Would be awesome if EDD would offer the import functionality through it's API interface. That I could send each import record through the API and that EDD would take care of the rest. If somebody can develop as a plugin, feel free to contact us. We are willing to reward the one that can create this.

**Comment by cklosowski** [comment] 2017-12-18 13:35
Auto-mapping is a duplicate of #5797

At this point the API is Read-Only. There is no 'write' API available until we build out an API that integrates with the WP JSON API. I'll add Import/export to the JSON api issue in #6029

**Closed by cklosowski** 2017-12-18 13:35 UTC
