### ISSUE TITLE
Fees and Cart recovery can end up with duplicate fees due to key naming

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6971] opened 2018-10-04 20:31 UTC
### Expected behavior
When resuming a payment, all fees should match what they previously were and only show the proper number of times.

### Actual behavior
In an edge case with Discounts Pro (where a specific ID is used), you can end up with the same Fee showing twice (only applying once however) due to the fact that the item based fees don't have the ID defined in the array, where as the global fees array does.

### Steps to reproduce the behavior
1) Setup a Discounts Pro Discount
2) Add item to cart so Discounts Pro discount applies
3) Checkout using PayPal but do not complete purchase
4) Go to Purchase History and click Complete Purchase for the abandoned order
5) Cart should show duplicate discounts

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `master`

WordPress Version: All

Any other relevant information:
This was discovered and reported with Discounts Pro here: https://github.com/easydigitaldownloads/edd-discounts-pro/issues/147

**Comment by SDavisMedia** [comment] 2018-10-05 00:17
I'm having mixed results just trying to replicate this. On my local site, the recovery process fails to even add a single fee (discount) to the cart. The payment being recovered is all accurate, fee and everything. But once you click the link to Complete Purchase, no fee.

On my live test site, the fee is present during cart recovery as it should be, but it is _not_ a double fee, which is what I'm trying to replicate. So something's up.

@mintplugins Could you try to replicate this behavior when you get a chance?

**Comment by mintplugins** [comment] 2018-10-05 15:49
On my local test site, the fee is always present, and after manually completing the payment, I still only have 1 fee. Everything appears to be working correctly for me on `master`.

<img width="291" alt="screen shot 2018-10-05 at 11 48 55 am" src="https://user-images.githubusercontent.com/1638128/46545548-aabc9200-c894-11e8-9c76-94e6110884f8.png">

**Comment by dgoldak** [comment] 2018-10-05 16:38
I confirmed fix works on my local test site and have been able to get consistent results. With `issue/6971` loaded, clicking Compete Purchase via Order History only contains 1 discount. Reverting back to `master` causes duplicate discounts.

**Comment by dgoldak** [comment] 2018-10-05 16:42
@mintplugins how did you manually complete the payment? Did you go to your Purchase History (ie http://edd.local/checkout/purchase-history/)?

**Comment by cklosowski** [comment] 2018-10-05 17:09
@mintplugins this wasn't affecting the backend...it was only affecitng the display on the front end.

**Comment by SDavisMedia** [comment] 2018-10-05 17:32
I've been trying to replicate again this morning and I still can't. I even tried going straight to checkout without using the Complete Purchase process like @dgoldak has, but still no issues on my end.

**Comment by mintplugins** [comment] 2018-10-09 14:01
After running the `EDD()->cart->empty_cart()`, confirmed fixed on `issue/6971` 👍

**Comment by cklosowski** [comment] 2018-10-09 14:43
Since this affects checkout, I need 3 confirmations. So far I just have two. @misulicus @pippinsplugins @davidsherlock can one of you try and replicate this and confirm the fix?

A couple notes, between replicating and confirming the fix, it might be necessary to run this command in debug bar console:
`EDD()->cart->empty_cart()`

Either that or run in completely separate incognito sessions so that your cart data doesn't persist.

**Comment by misulicus** [comment] 2018-10-09 15:15
bug confirmed and also fix seems to be working for me.
Tested on master discounts pro

**Comment by cklosowski** [comment] 2018-10-10 04:58
Thanks @misulicus that's 3 confirmations that this fixes a repeatable problem. I'm going to merge this PR.

**Closed** 2018-10-11 18:18 UTC
Labels: Bug, Checkout, Has PR, Needs Testing
