### ISSUE TITLE
Allow target attribute in links within privacy policy field label

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#6585] opened 2018-05-22 08:46 UTC
Currently, you can add a link to your privacy policy in the checkout privacy policy agree on the field, BUT, you cannot set it with target="_blank" as you would want to keep them on checkout.

Appears that it strips that out when saving.

Maybe another option would be to add a {{privacylink}} tag capability there as well.

**Comment by pippinsplugins** [comment] 2018-05-22 13:08
Duplicate of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6579

**Closed by pippinsplugins** 2018-05-22 13:08 UTC
