### ISSUE TITLE
exclude_categories/tags parameter in [downloads] shortcode not working

### ISSUE THREAD

**Issue by sdavis2702** [easydigitaldownloads/Easy-Digital-Downloads#3001] opened 2015-01-26 02:19 UTC
As mentioned here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2970#issuecomment-70596807

Now that the relation issue is taken care of, we should be clear to stab at this one.

Relevant ticket: https://easydigitaldownloads.com/support/topic/add-not-to-downloadrelation/

**Comment by cklosowski** [comment] 2015-01-26 02:23
:hocho:

**Comment by pippinsplugins** [comment] 2015-01-26 15:37
Let's get this fixed for 2.2.5

**Comment by sdavis2702** [comment] 2015-01-27 18:23
FYI, @cklosowski brought to my attention we were testing (or at least typing in our comments) `exclude_categories`,`exclude_tags` when it should be `exclude_category`,`exclude_tag`.

So let's make sure we get that right when testing. For me, the correct using of those parameters does **not** work when coupled with a `category` parameter that specifies a parent category that has children... one of which is being excluded.

Parent Category: 0 items
... Child Category 1: 2 items
... Child Category 2: 2 items

`[downloads category="parent-category" exclude_category="child-category-1"]`

^^^ That's where it's not working for me.

**Comment by pippinsplugins** [comment] 2015-01-27 18:35
Second set that is not working for me:

`[downloads category="9" exclude_category="10"]`

10 and 9 are both top-level categories and some items in 10 are also in 9.

Items in 10 still show up.

**Comment by sdavis2702** [comment] 2015-01-27 18:37
I just got the same results. ^^^

**Comment by cklosowski** [comment] 2015-01-27 21:02
Ok I think I have a plan for this, but it's a pretty major change to the Downloads shortcode query. I don't think that's right for 2.2.5. We'll punt this to 2.3, and really beef up testing on it.

Essentially we'll need to add a bunch of cases, but the root cause of these bugs are, we want ```OR``` to be the default clause, however, as soon as you have excludes, you would need to include the ```inclusionary``` cases WITHIN the ```exclusionary``` clause, or else you'll always get every product.

Currently we have:
Get all items in Category X OR All items NOT IN Category Y, leaving with you with every item

We need something like:
Get all items in Category X OR ( All items in Category X AND not in Category Y )

**Comment by mindctrl** [comment] 2015-02-02 18:11
Related? https://easydigitaldownloads.com/support/topic/shortcode-for-download-to-display-grid-stopped-working/#post-428079

**Comment by cklosowski** [comment] 2015-02-17 18:43
ok @mindctrl and @sdavis2702 can you guys test this out? it's on branch `issue/3001`. I think I have it working as needed.

A note about this method...it degrades in performance the more categories/tags you add to each of them. But that's just a symptom of meta queries in general. So we have to live with it for now.

**Comment by cklosowski** [comment] 2015-02-17 18:57
@pippinsplugins I guess you can test it out if you want too ;)

**Comment by pippinsplugins** [comment] 2015-02-18 16:08
Will do!

**Comment by sdavis2702** [comment] 2015-02-23 19:15
@cklosowski, good stuff. That fixed it for me. :+1:

**Comment by chriscct7** [comment] 2015-02-23 19:28
When using the following: 
[downloads category="parent-category" exclude_category="parent"]

Where parent is a valid category that downloads belong to and parent-category is an invalid category that does not exist. All products - the ones in parent are shown. Is this expected or are we expecting a null set of downloads?

**Comment by sdavis2702** [comment] 2015-02-23 19:36
@chriscct7 well the question to ask here is what we want the following to show:

[downloads category="parent-category"]

...when `parent-category` is invalid. Right now, it shows all downloads as if the category parameter is not being used at all (which I think is right). And with that behavior, `exclude_category="parent"` displaying everything _but_ `parent` with an invalid category parameter makes sense.

**Comment by chriscct7** [comment] 2015-02-23 19:37
Ok, yeah I guess thats fair. The only thing is when you have a small number of downloads when you are setting up a site it might seem that you are getting the right downloads from your shortcode and you don't realize you've typo'd a category until much later

**Comment by chriscct7** [comment] 2015-02-23 19:38
Other then that, the rest of this works great :+1:

**Comment by mindctrl** [comment] 2015-02-23 21:30
Getting no downloads with this shortcode:
`[downloads category="category-3,charts-graphs" exclude_category="another-category"]`

Category structure:
```
- category-3
- charts-graphs
-- another-category
```
Will do some more testing.

**Comment by mindctrl** [comment] 2015-02-24 00:25
More tests with screenshots.

![downloads-shortcode-test-products](https://cloud.githubusercontent.com/assets/1254870/6340837/a7538be6-bb91-11e4-8732-28d1d6134919.png)

![downloads-shortcode-test-output](https://cloud.githubusercontent.com/assets/1254870/6340840/ad7f81dc-bb91-11e4-8a25-a9beec69d18d.png)

**Comment by cklosowski** [comment] 2015-02-25 18:25
Thanks @mindctrl, will do some more testing.

**Comment by cklosowski** [comment] 2015-02-28 17:20
Ok @mindctrl I think we're at the point where we can do this properly. We have a logical limitation when `exclude_*`. It's hard to explain in words but it's best to think of it in a Venn Diagram...

We cannot support multiple categories with an `OR` relation when we have an exclude. As it would mean we would get ALL products. We have to Switch to `AND`, to allow a proper meta query.

**Comment by pippinsplugins** [comment] 2015-03-06 02:51
This seems to be working well for me! Merged into `release/2.3`

**Comment by mindctrl** [comment] 2015-03-09 15:17
@chriscct7 wanted me to post the page content from my tests above for easy copy/pasting.
```
<h2>parent-1 and parent-2</h2>
<pre>
[[downloads category="parent-1, parent-2"]]
</pre>
[downloads category="parent-1, parent-2"]

<br><br><br><br>
<h2>parent-1 and parent-2, exclude parent-1-child</h2>
<pre>
[[downloads category="parent-1, parent-2" exclude_category="parent-1-child"]]
</pre>
[downloads category="parent-1, parent-2" exclude_category="parent-1-child"]

<br><br><br><br>
<h2>parent-1, parent-2, and parent-3</h2>
<pre>
[[downloads category="parent-1, parent-2, parent-3"]]
</pre>
[downloads category="parent-1, parent-2, parent-3"]

<br><br><br><br>
<h2>parent-1, parent-2, parent-3, exclude parent-1-child</h2>
<pre>
[[downloads category="parent-1, parent-2, parent-3" exclude_category="parent-1-child"]]
</pre>
[downloads category="parent-1, parent-2, parent-3" exclude_category="parent-1-child"]

<br><br><br><br>
<h2>parent-1, parent-2, parent-3, exclude parent-1-grandchild</h2>
<pre>
[[downloads category="parent-1, parent-2, parent-3" exclude_category="parent-1-grandchild"]]
</pre>
[downloads category="parent-1, parent-2, parent-3" exclude_category="parent-1-grandchild"]
```

**Comment by chriscct7** [comment] 2015-03-09 15:18
Awesome thanks @mindctrl

**Comment by pippinsplugins** [comment] 2015-03-10 00:12
@mindctrl Is everything working as expected for you?

**Comment by mindctrl** [comment] 2015-03-10 02:03
@pippinsplugins looks good here.

**Comment by pippinsplugins** [comment] 2015-03-10 02:48
Excellent.

**Closed** 2015-03-10 02:48 UTC
Labels: Bug, Has PR, Needs Testing
