### ISSUE TITLE
New Importer should use existing customer_id as a canonical source

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4625] opened 2016-05-26 21:08 UTC
The new payment importer, in it's current state creates new customers with an email address is found that isn't associated with a customer. On a brand new site, especially with the addition of #3755, it's possible that a single customer from the export, who made purchases with multiple email addresses, could end up as multiple customers in the new site that's imported into.

We could use something like the following:
```
1. add customer_id to payment export
2. during import store the canonical customer ID in customer meta
3. on each subsequent customer look up, see if there is a customer already created with the canonical ID
4. If so, use that customer and add the additional email
5. If not, create a new customer
```

**Comment by pippinsplugins** [comment] 2016-06-08 18:58
Ok this is ready for testing.

It's a bit of a tricky one, so read / test carefully.

1. Start with a fresh store
2. Make a purchase
3. Add a new email to the customer created in step 2. Customer should now have two email addresses.
4. Make a second purchase using the _second_ email added to the customer
5. Export payment history
6. Reset store _or_ move to different fresh store
7. Import payment history. Two fields that must be mapped: `customer_id` and `email`
8. After import, you should have _only one_ customer record that shows both email addresses.

**Comment by mintplugins** [comment] 2016-06-08 19:20
When doing the mapping, I have the fields repeated 547 times :O 

<img width="1437" alt="screen shot 2016-06-08 at 3 19 33 pm" src="https://cloud.githubusercontent.com/assets/1638128/15907770/7729f680-2d8c-11e6-9739-abe5155aec17.png">

**Comment by mintplugins** [comment] 2016-06-08 19:33
Above issue resolved by turning SCRIPT_DEBUG on.

**Comment by mintplugins** [comment] 2016-06-08 19:34
Tested Import successfully and it only created 1 Customer. The only issue I notice is that previously the Primary Email was the first one. Now the Primary email is the second one.

**Comment by pippinsplugins** [comment] 2016-06-08 19:37
@mintplugins good catch on the primary email! I'll see if I can find a way to resolve that.

**Comment by pippinsplugins** [comment] 2016-06-09 16:09
@mintplugins This should work properly now. Can you test again please?

**Comment by mintplugins** [comment] 2016-06-09 17:24
Just re-tested this and now I get 2 different customers after import. Also, the payments that were "complete" are listed as "pending" after importing them.

**Comment by mintplugins** [comment] 2016-06-09 17:25
<img width="755" alt="screen shot 2016-06-09 at 1 24 45 pm" src="https://cloud.githubusercontent.com/assets/1638128/15939416/9795af72-2e45-11e6-802b-dc5c969068a1.png">

<img width="759" alt="screen shot 2016-06-09 at 1 25 29 pm" src="https://cloud.githubusercontent.com/assets/1638128/15939431/a8b38be4-2e45-11e6-95e1-2b7b5fd5fe7d.png">

**Comment by pippinsplugins** [comment] 2016-06-09 17:30
screenshot of field mapping?

**Comment by mintplugins** [comment] 2016-06-09 17:45
<img width="1225" alt="screen shot 2016-06-09 at 1 44 45 pm" src="https://cloud.githubusercontent.com/assets/1638128/15940071/5be31a84-2e48-11e6-8ad5-41e1cac0cbcc.png">

**Comment by mintplugins** [comment] 2016-06-09 17:45
It may be worth noting that I deleted the original product and it does not exist before or after the payment import.

**Comment by mintplugins** [comment] 2016-06-09 17:46
<img width="1425" alt="screen shot 2016-06-09 at 1 46 17 pm" src="https://cloud.githubusercontent.com/assets/1638128/15940122/93019b62-2e48-11e6-8d02-68b466d05300.png">

**Comment by pippinsplugins** [comment] 2016-06-09 18:01
Did you test this on `issue/4625` branch?

**Comment by mintplugins** [comment] 2016-06-09 18:04
Yes on 4625

**Comment by pippinsplugins** [comment] 2016-06-09 19:08
@mintplugins I just did it again and it worked properly.

Make sure you completely reset your store before doing the import.

**Comment by mintplugins** [comment] 2016-06-09 19:45
I hooked up a new database altogether and it created a single customer correctly. However, I noticed the payments are set as pending - is that by design?

**Comment by pippinsplugins** [comment] 2016-06-09 19:52
Did you set the status column? What was the value of it?

They will be set to pending unless a different status is supplied with the import.

**Comment by mintplugins** [comment] 2016-06-09 20:05
I didn't map the "status" column no. I didn't realize that mapping was required. Looks good!

**Comment by pippinsplugins** [comment] 2016-06-09 20:10
I'll make `Complete` the default.

**Closed** 2016-06-09 20:19 UTC
Labels: Administration, Needs Testing
