### ISSUE TITLE
Today/Yesterday Reports miscalculate hours to include

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5156] opened 2016-11-05 13:34 UTC
Here: 
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/admin/reporting/graphing.php#L382

and here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/admin/reporting/graphing.php#L58

The hour range is supposed to go from 0-23 to query hour by hour. However, we tell it to start at 1. This means that orders between 00:00 and 01:00 are missing from the reports. 

For example, if you run a report using the "Today" range on the EDD site for earnings, and then run it again using a custom range from Nov 5, 2016 to Nov 5, 2017, you'll notice one order is missing as a result of this bug.

Furthermore,
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/admin/reporting/graphing.php#L392

we tell the date to end on hour +1

If the hour 23 part of the report being run, the second and minute end variables by default get set to 59 and 59 for the [hour end](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/admin/reporting/graphing.php#L387). This causes a bug though when running a Yesterday report (because this bug would also affect Today reports but that'd be in the future sales) both with and without the fix for the above issue because if the hour is 23, then the $hour + 1 being done [here ](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/admin/reporting/graphing.php#L392) means that when $hour = 23, the range goes from 23:00:00 (in hh:mm:ss) to 24:59:59. When $hour is 23, there needs to be a conditional that says not to do the hour increment. Easiest thing would be do add it as the else part of the existing 23 hour condition.

These two related issues lead to Today reports excluding an hours worth of sales, and Yesterday reports including an hour worth of sales from Today.

If you want to see them both in action, run a report of Today on EDD's site, then compare to a custom report of Nov 5 - Nov 5, and subtract $custom_report - $today report. Let's call this $offset

Then run a custom report for Nov 4 - Nov 4 and subtract all orders made in the first hour of Nov 4 and then add $offset. The resulting total will equal the number that's miscalculated on the Yesterday report, and thus you'll see, particularly with the yesterday report, the number is wildly off from what it should be.

Currently, on November 5, the Today report is off by 1, the Yesterday report is off by 7

**Comment by chriscct7** [comment] 2016-11-05 14:31
@easydigitaldownloads/core-devs if anyone wants to test the bug or the fixes, you'll want to do it within the next 12 hours. After that, being able to replicate the issues tomorrow will depend on sales between 11pm and 1am CST.

**Comment by sunnyratilal** [comment] 2016-11-05 16:25
Bug confirmed.

As of `11:22 CST`, we have 11 sales but the Today report only shows 9. 1 sale has been refunded so we're missing 1 sale in the report. That one sale was made at `00:36 CST` so we need to start counting sales from midnight in lieu of `01:00 CST`.

**Comment by sunnyratilal** [comment] 2016-11-05 17:28
We'll need to update unit tests to ensure the queries are returning the expected data. Best way to do this would be to create 24 sales (one with the date set of each hour) and expect 24 sales to be returned.

**Comment by cklosowski** [comment] 2016-11-15 04:22
Seems to be working well on my end. @easydigitaldownloads/core-devs could use someone else to take a look as well.

**Comment by cklosowski** [comment] 2016-11-15 04:22
![screen shot 2016-11-14 at 9 22 02 pm](https://cloud.githubusercontent.com/assets/1390124/20293084/71cc702c-aab0-11e6-8b34-8519d7505346.png)

**Comment by pippinsplugins** [comment] 2016-11-15 14:37
Graph only goes to `23`. Needs to go to `24`.
![screen shot 2016-11-15 at 8 37 15 am](https://cloud.githubusercontent.com/assets/1034109/20309745/c5856bfc-ab0e-11e6-8afc-d1fe92dff256.png)

**Comment by cklosowski** [comment] 2016-11-15 18:32
@pippinsplugins no 24, would be `00:00` which is techicnally on the next day. All sales for Today or Yesterday would be `00:00:00 - 23:59:59`.

**Comment by pippinsplugins** [comment] 2016-11-15 18:44
My point was that 23:59 does not show on the graph, it only goes up to 23. Does `23` contain everything from `22:01` to `23:00` or does it contain everything from `23:01` to `23:59`?

**Comment by sunnyratilal** [comment] 2016-11-15 18:48
It's shown up to `23:59`

**Comment by cklosowski** [comment] 2016-11-15 18:56
This is an hour by hour, so the hours are inclusive, if something was at `23:59:59` it's in the `23` hour.

**Comment by pippinsplugins** [comment] 2016-11-15 20:39
:+1: all good then.

**Comment by sunnyratilal** [comment] 2016-11-15 21:00
Thanks @pippinsplugins - merging now

**Comment by sunnyratilal** [comment] 2016-11-15 21:01
Merged into `master`

**Closed by sunnyratilal** 2016-11-15 21:01 UTC
Labels: Bug, Has PR, Needs Testing, Needs Unit Tests, Priority: High, Reports
