### ISSUE TITLE
Deprecate edd_get_earnings_by_date & edd_get_sales_by_date

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5164] opened 2016-11-05 16:38 UTC
For a long time, edd_get_earnings_by_date & edd_get_sales_by_date which are used on the earnings graph report have been marked as something we'll get around to deprecating for a while. Right now, essentially we're maintaining 2 Stats APIs, the actual API and these two functions along with a ton of inline logic in the earnings report file. The result is the latter is really buggy and doesn't benefit from newer API features. We should actually deprecate (for real) these functions and swap the earnings report over to the Stats API. Doing this will almost certainly prevent a ton of more bugs (we've found 5 or 6 just today alone in the current implementation), so going to tag this as a 2.7 milestone ticket.

**Comment by sunnyratilal** [comment] 2016-12-30 12:52
Initial PR opened at #5328.

We need to merge #1980 in order to migrate the `edd_get_earnings_by_date()` to the new respective counterpart in `EDD_Payment_Stats`.

**Comment by sunnyratilal** [comment] 2017-01-18 21:24
Only place where `edd_get_earnings_by_date()` is now used is in our API.

**Comment by sunnyratilal** [comment] 2017-01-18 21:24
Next commit will have those removed too

**Comment by sunnyratilal** [comment] 2017-01-18 23:24
@easydigitaldownloads/core-devs Ready for testing

**Comment by pippinsplugins** [comment] 2017-01-19 20:57
To test this, please use the /stats/ and /earnings/ endpoint of the REST API and pass in various date ranges. If it's working properly, the numbers reported on `issue/5164` and `master` will be identical.

**Comment by mintplugins** [comment] 2017-01-19 22:51
I tested the following endpoints with various dates on both master and issue/5164 and results were the same:

- stats - For retrieving earnings / sales stats specific dates, date ranges, and specific products.
- products - For retrieving info about store products.
- customers - For retrieving customer stats.
- sales - For retrieving recent sales and info about each sale (items purchased, buyer, amount, etc).
- discounts - For retrieving info about all available discounts.

However, these endpoints did not work on either master or issue/5164. That is likely unrelated though:

- endpoints (This is not listed in the docs, is it an endpoint?)
- download-logs (This returns "Invalid Query")

**Comment by pippinsplugins** [comment] 2017-01-19 22:59
Oops, `/earnings/` is `/stats/?type=earnings` and `/stats/?type=sales`

**Comment by sunnyratilal** [comment] 2017-01-20 01:14
`download-logs` doesn't exist either - it's supposed to be `file-download-logs`

**Comment by mintplugins** [comment] 2017-01-20 01:25
In that case everything looks the same to me on both master and issue/5164 👍

**Comment by sunnyratilal** [comment] 2017-01-20 01:25
Merged into `release/2.7`

**Comment by pippinsplugins** [comment] 2017-01-27 16:32
This appears to have broken date range queries to the EDD_API for earnings.

**Comment by pippinsplugins** [comment] 2017-01-27 16:38
Looks like the date ranges are failing.

Also, if I change `date=this_month` in the earnings stats request, I get an error:

#0 /dom8333/wp-content/plugins/easy-digital-downloads/includes/api/class-edd-api.php(564): EDD_API->get_stats(Array)
#1 /wordpress-4.7.2/wp-includes/class-wp-hook.php(298): EDD_API->process_query(Object(WP))
#2 /wordpress-4.7.2/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#3 /wordpress-4.7.2/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#4 /wordpress-4.7.2/wp-includes/class-wp.php(746): do_action_ref_array('wp', Array)
#5 /wordpress-4.7.2/wp-includes/functions.php(955): WP->main('')
#6 /wordpress-4.7.2/wp-blog-header.php(16): wp()
#7 /wordpress-4.7.2/index.php(17): require('/wordpress-4.7....')
#8 {main}
  thrown in /dom8333/wp-content/plugins/easy-digital-downloads/includes/api/class-edd-api.php on line 1403

**Comment by sunnyratilal** [comment] 2017-01-27 16:52
Fixed in d13020792f930ef0229e79f122c307908eaf39f6.  Incorrect issue referenced in the commit.

**Comment by pippinsplugins** [comment] 2017-01-27 16:53
Fix confirmed.

**Closed by pippinsplugins** 2017-01-27 16:53 UTC
Labels: API, Enhancement, Reports
