### ISSUE TITLE
All query strings are stripped on add-to-cart via URL

### ISSUE THREAD

**Issue by EngageWP** [easydigitaldownloads/easy-digital-downloads#3644] opened 2015-07-25 09:23 UTC
I was doing some work that involved putting together custom add to cart URLs (leading to the checkout page) and I noticed the redirect that occurs after the download is added to the cart. After some digging, I found this:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/8812f896bef70f4441c224b56cb8bf03232752e7/includes/cart/actions.php#L72

I narrowed the issue down to lines 71-72, where it's performing a clean redirect.

First, I'm not sure why `! edd_is_checkout()` is evaluating to true when the URL I'm using leads directly to the checkout page (this page was saved as the checkout page option in the EDD settings). I've tested this on multiple installations, passing args for adding a download to the cart as well as random args to see if they would stick. Each time, the edd_straight_to_cart option was enabled and the add to cart url was formed by retrieving the permalink of the checkout page option. Once entered, the clean redirect would occur and the entire query string was stripped.

It seems to me that the `! edd_is_checkout()` should return false (I'm on the checkout page) and cause the else statement to run, which would result in any custom query arg remaining intact. Not being able to preserve the custom query args is where I'm running into my issue. If I'm missing something (which I admit I may be because I just pulled an all-nighter) and the if/else is operating as intended, perhaps a filter in the if statement's `wp_redirect()` would be of use so that the redirect can be modified.

Sorry if I'm missing something obvious and thanks in advance for any help.

**Comment by pippinsplugins** [comment] 2015-07-27 01:57
Stripping query args is by design. When redirecting to checkout, we want a clean URL without query strings.

I do see where you might want query strings however, so perhaps we should only strip EDD's query strings.

**Comment by EngageWP** [comment] 2015-07-27 02:18
That's what I did to fix it. 

	/**
	 * Process the Add to Cart request
	 *
	 * @since 1.0
	 *
	 * @param $data
	 */
	function edd_process_add_to_cart( $data ) {
		$download_id = absint( $data['download_id'] );
		$options     = isset( $data['edd_options'] ) ? $data['edd_options'] : array();
		$cart        = edd_add_to_cart( $download_id, $options );
		wp_redirect( remove_query_arg( array( 'edd_action', 'download_id', 'edd_options' ) ) ); edd_die();
	}
	add_action( 'edd_add_to_cart', 'edd_process_add_to_cart' );

**Comment by pippinsplugins** [comment] 2015-07-29 00:04
That looks like a good solution.

**Comment by pippinsplugins** [comment] 2016-05-09 02:18
I'm proposing `wontfix` for this. Anyone that wishes to retain the query strings can use this code snippet.

**Closed by pippinsplugins** 2016-05-09 02:18 UTC
Labels: Checkout, Enhancement
