### ISSUE TITLE
If you add multiple-of-the-same items to the cart, it only adds 1.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/Easy-Digital-Downloads#2926] opened 2015-01-05 17:40 UTC
If you have an ajax add-to-cart button and click it several times without refreshing the page with the intention of adding multiples-of-the-same to the cart, ajax appears to add multiples, but when you refresh, there is only 1. 

For example, say I have a t-shirt for sale. As a customer I want to buy 5 t-shirts (all exactly the same). So I click the add to cart button 5 times. The ajax cart widget shows 5 identical t-shirts in the cart. But if I refresh the page, I only have 1 t-shirt in the cart.

**Comment by cklosowski** [comment] 2015-01-07 16:54
I think I'm going to tackle #2931 along side of this one.

**Comment by cklosowski** [comment] 2015-01-12 02:47
@mintplugins Just a quick question, with AJAX on, do you not get the 'Checkout' button when you add an item to the cart?

Currently even with Quantities enabled, you should see something like the following when you click 'Add to Cart'
![image](https://cloud.githubusercontent.com/assets/1390124/5698420/69beff18-99db-11e4-8732-fd5b66236194.png)

**Comment by mintplugins** [comment] 2015-01-12 05:40
I do, but I wrote a script which turns it back into a buy button after 1 second (for a specific project where it makes sense). I know it's not a huge bug for the mass number of users - but just thought I would point it out as I saw it.

https://wordpress.org/plugins/easy-digital-downloads-keep-add-to-cart/

**Comment by mintplugins** [comment] 2015-01-12 05:58
Here's a quick example of how this is in-use:

https://creativeready.com/stack/customize-radio-campaign-stack?customize_post_id=3829#

**Comment by cklosowski** [comment] 2015-01-12 13:55
@mintplugins Do you have quantities enabled?

**Comment by mintplugins** [comment] 2015-01-12 18:06
Yes - quantities are enabled but hidden through css. If the user added the wrong amount of items to their cart, we wanted them to be able to remove/add items at-will without leaving the page.

**Comment by mintplugins** [comment] 2015-01-12 18:10
With the add-to-cart button changing into a "checkout" button permanently, it wasn't possible for them to 'add another' of the same item to their cart without refreshing the page.

**Comment by cklosowski** [comment] 2015-01-12 18:29
Well Add/Remove is supported in Core without refreshing the page...but adding more once it's in the cart is not without removing it, and adding the quantity field.

Currently as it sounds, I'll have to investigate this as a conflict with the way your button change is working and core...it won't make #2931

**Comment by cklosowski** [comment] 2015-01-12 18:29
Will be a separate issue I think.

**Comment by mintplugins** [comment] 2015-01-12 18:31
Okay sounds good. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2931 does appear to be somewhat related to this - so even to get that fixed is great :)

I'll see if I can get some time on my own to dig into this soon too.

**Comment by cklosowski** [comment] 2015-01-12 18:32
Actually #2931 was just an issue with what we consider 'quantity'. My guess is here, that there's a conflict in the add_to_cart action and our method of adding more quantities once an item is in the cart already.

**Comment by mintplugins** [comment] 2015-01-12 18:36
True

**Comment by cklosowski** [comment] 2015-01-14 15:46
FYI @mintplugins you'll want to look at this change set for your plugin. There is an update to show the quantity field when removing an item from the cart:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/a9b4943e1e74d2ba7dd21a7690ddb2be4d04498e

**Comment by cklosowski** [comment] 2015-01-14 19:00
So it is actually adding multiples to the cart, however, our widget doesn't show each quantity as it's own line item. Your plugin appears to add a new line item for each item added, core EDD does not do that.

If you do your plugin, refresh the page, but then go to the checkout, you do have multiples of each item in there, as quantity.

After adding to the cart, a second item:
![image](https://cloud.githubusercontent.com/assets/1390124/5745268/81e0da82-9bf5-11e4-87cd-475deaf6001d.png)

After a page refresh (notice we still have 2 items in the cart, which would have been fixed in the most recent release 2.2.3):
![image](https://cloud.githubusercontent.com/assets/1390124/5745283/91d2ab3c-9bf5-11e4-913b-f30d1f7d88e5.png)

But the actual cart:
![image](https://cloud.githubusercontent.com/assets/1390124/5745295/a3214d30-9bf5-11e4-966d-51cf05e35419.png)

**Comment by pippinsplugins** [comment] 2015-02-10 23:32
Looks like we need to adjust the cart widget to show item quantities.

**Comment by cklosowski** [comment] 2015-02-10 23:51
As in:
```Item Name - X @ $X.XX - remove```?

**Comment by pippinsplugins** [comment] 2015-02-10 23:54
Duplicate of #2931.

**Closed by pippinsplugins** 2015-02-10 23:54 UTC
Labels: Bug, Frontend
