### ISSUE TITLE
Gateway selector not working when AJAX is disabled

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5544] opened 2017-03-06 21:50 UTC
Disable AJAX and try to go through the checkout process:
`add_filter( 'edd_is_ajax_disabled', '__return_true' );`

The `Next` button on the page with the gateway selector does nothing but refresh the page. 

This breaks on version 2.7. Perhaps [this](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4758) is incomplete.

**Comment by ghost1227** [comment] 2017-03-10 16:49
I spent the better part of yesterday trying to track this down with little success. @cklosowski you're still much better than me at the JS related stuff, mind taking a look?

**Comment by pippinsplugins** [comment] 2017-03-13 19:37
This doesn't have anything to do with JS.

It needs a similar fix as #5557. The fields don't show because of the changes made to `edd_show_gateways()` for https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5082.

We'll need to adjust the logic in `edd_checkout_form()` to ensure the `edd_purchase_form` action always fires when `payment-mode` is in the URL and ajax is disabled.

**Comment by ghost1227** [comment] 2017-03-13 20:14
@pippinsplugins Good tip! That made a ton of sense once I read #5557

**Comment by pippinsplugins** [comment] 2017-03-13 21:04
PR works for me! I'd like one more test on it to confirm before merging.

**Comment by sunnyratilal** [comment] 2017-03-17 11:34
Tested and confirmed working - merging...

**Comment by sunnyratilal** [comment] 2017-03-17 11:35
Merged into `master`

**Closed by sunnyratilal** 2017-03-17 11:34 UTC
Labels: Bug, Checkout, Has PR, Needs Testing, Priority: Medium
