### ISSUE TITLE
Custom payment metadata gets cleared sometimes when updating payment 

### ISSUE THREAD

**Issue by Hossein52Hz** [easydigitaldownloads/easy-digital-downloads#5490] opened 2017-02-18 06:58 UTC
Hi,
I was using your code at below link for creating my custom checkout fields,everything was  working since i updated to the new version and now my added fields  code stopped working and goes empty after payment.
http://docs.easydigitaldownloads.com/article/1003-custom-checkout-fields

**Comment by tomasvilda** [comment] 2017-02-28 19:25
Same here, can't reproduce the problem, but after update sometimes custom fields are all empty.
Big problem!

**Comment by pippinsplugins** [comment] 2017-02-28 19:35
@tomasvilda could you please elaborate? Do you mean that custom fields entered on checkout do not save their values or that clicking "Update" on an existing payment record wipes out the value?

**Comment by tomasvilda** [comment] 2017-02-28 19:43
Had second customer whose custom data was not saved (all fields empty)

http://vildos.lt/files/edd_custom_fields.png

Asked first customer to submit one more purchase with the same data and new purchase he made had all data. Tried to make purchase myself with several different fillings all passed OK.

**Comment by tomasvilda** [comment] 2017-03-03 08:15
Find out how to reproduce the problem, changing order state, clears custom values starting from edd version 2.7.

To reproduce the problem, make an order, but don't finish the payment. Custom data is there. Change the order state to finished using wp admin panel and custom data is cleared. The same happens when real customer finished payment. Custom data is cleared.

Rolled back to 2.6.17 until bug is fixed.

**Comment by pippinsplugins** [comment] 2017-03-03 14:47
Aha! There we go. Now I can replicate it. Thanks!

Working on tracking it down now.

**Comment by pippinsplugins** [comment] 2017-03-03 15:03
Problem was introduce in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/0437b0969c6074bf4640d78a657ca235c0dddd0a for https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2714

Specifically, it's this line that broke it: `$merged_meta = apply_filters( 'edd_payment_meta', $merged_meta, $payment_data );`

**Comment by pippinsplugins** [comment] 2017-03-03 15:10
As much as I hate to break existing custom code options, in this case I think we have to fix this by updating our code samples for custom checkout fields. They do not currently take into account the various scenarios where data might be saved. They assume that the data is _only_ saved on the checkout screen.

For anyone experiencing this problem, it can be fixed by updating the function tied to the `edd_payment_meta` filter to only set the field values if the `edd_purchase` action has been done.

For example, if your function looks like this (just like our sample code):

```php
/**
 * Store the custom field data into EDD's payment meta
 */
function sumobi_edd_store_custom_fields( $payment_meta ) {

	$payment_meta['phone'] = isset( $_POST['edd_phone'] ) ? sanitize_text_field( $_POST['edd_phone'] ) : '';

	return $payment_meta;
}
add_filter( 'edd_payment_meta', 'sumobi_edd_store_custom_fields');
```

Update it to this:

```php
/**
 * Store the custom field data into EDD's payment meta
 */
function sumobi_edd_store_custom_fields( $payment_meta ) {

	if( did_action( 'edd_purchase' ) ) {
		$payment_meta['phone'] = isset( $_POST['edd_phone'] ) ? sanitize_text_field( $_POST['edd_phone'] ) : '';
	}

	return $payment_meta;
}
add_filter( 'edd_payment_meta', 'sumobi_edd_store_custom_fields');
```

Note how the field values are only set to the `$_POST` data when the `edd_purchase` action has fired. This ensures the values are only set when processing the checkout form.

**Comment by pippinsplugins** [comment] 2017-03-03 15:11
I have updated the code sample in our docs.

**Closed by pippinsplugins** 2017-03-03 15:10 UTC
Labels: Bug, Payments

**Comment by tomasvilda** [comment] 2017-03-03 15:22
Thank you, updated my custom fields code according to new docs, checked and problem is no gone.

**Comment by timersys** [comment] 2017-03-05 15:52
Hi Guys, I was experiencing the same issue with paypal express and stripe.
I did resolve it by using session data

```
$data = edd_get_purchase_session();
$payment_meta['timer_country'] = isset( $data['post_data']['timer_country'] ) ? sanitize_text_field( $data['post_data']['timer_country'] ) : '';
```
