### ISSUE TITLE
JS for variable pricing option needs to be refined

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5019] opened 2016-10-10 15:42 UTC
Still investigating a different bug related to this, where the JS was doing the reverse for `Enable variable prices` on a new download screen. However, regardless of whether that bug becomes replicatable or not, it showed a flaw in how the JS checks before it does the action. The JS should not have permitted for that behavior to be reversed. If checking that box it should open if and only if not open and unchecking close if and only if not closed.

Bug still in testing showing this reversal: https://www.dropbox.com/s/k28sx6260u6hsp0/2016-10-10_11-27-13.MP4?dl=0

**Comment by chriscct7** [comment] 2016-10-10 15:56
To replicate the bug, open the new download screen and the second the dom starts registering, immediately tick on the variable pricing box while it's still loading. Wait a few seconds for the page to actually finish, and then use the checkbox. And that's how it gets reversed.

**Comment by chriscct7** [comment] 2016-10-10 16:00
This needs to be tested on other pages we use JS based toggle style events like the payment page, for the same type of thing

**Comment by cklosowski** [comment] 2016-10-13 17:36
@chriscct7 so the issue is checking the box and DOM completion can get the toggle code into a mixed up state? If that's the case we can probably just focus on not using `toggle` and being specific about our cases.

**Comment by chriscct7** [comment] 2016-10-14 06:46
Yep. There's s demo of this on the attached video

**Comment by michaelbeil** [comment] 2016-10-19 19:49
I could not replicate the issue that @chriscct7 mentioned, but the functionality that @cklosowski introduced in #5061 works great.

**Comment by chriscct7** [comment] 2016-10-20 06:42
In order to replicate you have to move quickly and do it before the page finishes loading. Adding a plugin that adds more JS like Yoast SEO or something like that might help make it easier to replicate. I know @SDavisMedia replicated it in Slack

**Comment by SDavisMedia** [comment] 2016-10-20 15:08
I can definitely replicate this. Just gotta be fast. I like @cklosowski's solution.

**Comment by michaelbeil** [comment] 2016-10-20 15:42
That explains it since my screen is too short to get down to the meta box fast enough 😄  as I do not have my monitors set up yet.

**Comment by SDavisMedia** [comment] 2016-10-26 17:45
Easily replicated again on `master`. Confirmed fixed on `issue/5019`. :+1:

**Closed** 2016-10-26 22:45 UTC
Labels: Administration, Bug, Priority: Low
