### ISSUE TITLE
If default variable price isn't set, then $_POST[ '_edd_default_price_id' ] isn't set and a notice occurs.

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/Easy-Digital-Downloads#3942] opened 2015-10-24 21:01 UTC
I'm testing with EDD 2.4.9 and WP 4.3.1 I forgot to select a default price option when creating a download with variable prices. I got a notice that the index `_edd_default_price_id` was not set on l138 of `/includes/admin/downloads/metabox.php L138` This caused a PHP notice.

**Comment by pippinsplugins** [comment] 2015-10-25 20:03
Duplicate of #3931

**Closed by pippinsplugins** 2015-10-25 20:03 UTC
Labels: Duplicate
