### ISSUE TITLE
Database migration upgrade routine for 3.0

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6275] opened 2018-01-03 20:45 UTC
3.0 is including a large number of database changes that will necessitate a large upgrade routine.

To help ensure that the upgrade process goes smoothly, we'll have a single large, multi-step upgrade routine that moves everything.

The routine will included upgrades for the following issues:

- #4576 
- #6264 
- #3841 
- #5277 

The upgrade routine will mimic that one that was just built in Software Licensing for its migration to custom tables. See https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/515.

### Upgrade Routines

- [x] Orders
- [x] Customer addresses
- [x] Customer email addresses
- [x] Customer notes
- [x] Logs
- [x] Tax rates
- [x] Discounts
- [x] Order notes

### Order of migration
1. Orders
2. Order notes
3. Discounts
4. Tax rates
5. Customer notes
6. Customer email addresses
7. Customer addresses
8. Logs

**Comment by sunnyratilal** [comment] 2018-07-10 23:57
Merged.

@easydigitaldownloads/core-team Please test this upgrade extensively. Please post any bugs here.

**Comment by SDavisMedia** [comment] 2018-07-11 06:52
I ran my first migration test. It's not a big test and because my brain is fried tonight, my note-taking isn't incredibly thorough. But I'll tell you what I'm experiencing so far.

The migration page itself ran perfectly. Do note, though, that refreshing that page after the automatic migrations ran resulted in the following screenshot:

![screenshot_2018-07-10 migrate3dd1 wordpress](https://user-images.githubusercontent.com/2359131/42554557-3036eb0e-849a-11e8-9ce7-f0f40b6f94d1.png)

I didn't click the buttons again and I don't plan to. But unless this is by design because of some migration detail (which isn't told to me anywhere in the UI), those buttons should be disabled.

Also, if I remember correctly from when Chris introduced this migration UI, the notice at the top should be telling me that the migration is complete. Or perhaps that's not until after I delete legacy data.

-----

All 4,009 of my Payments were moved to Orders and they appear to have maintained their data.

The customers data is off, though. For one, I only have a single page of customers on my customer table (even though the filter links claim I have zero). https://cl.ly/2E1v1Q3Z1H1u

I should actually have 1,029, according to my database. I can look through my payments table UI and see customer names that will not show up on the customers table, not even if I search for them. So something's wrong there.

-----

File download logs appear to have migrated successfully. 

-----

That's all I have at the moment. I will test much more tomorrow.

**Comment by mindctrl** [comment] 2018-07-18 19:31
I'm getting an error during the `Upgrade Order Notes` routine.

```
EDD\Admin\Upgrades\v3\Logs->get_data() /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-base.php:107

[18-Jul-2018 19:05:32 UTC] WordPress database error Unknown column 'id' in 'field list' for query SELECT COUNT(id) AS count FROM wp_comments WHERE comment_type = 'edd_payment_note' made by do_action('wp_ajax_edd_do_ajax_export'), WP_Hook->do_action, WP_Hook->apply_filters, edd_do_ajax_export, EDD\Admin\Upgrades\v3\Order_Notes->get_percentage_complete
```

`id` is not a valid column in `wp_comments`.

**Comment by cklosowski** [comment] 2018-07-18 19:40
The ID column is `comment_ID`

**Comment by cklosowski** [comment] 2018-07-18 19:40
```
 ✝  wp-content/plugins/edd-recurring   issue/991  lando wp db query "describe wp_comments"
+----------------------+---------------------+------+-----+---------------------+----------------+
| Field                | Type                | Null | Key | Default             | Extra          |
+----------------------+---------------------+------+-----+---------------------+----------------+
| comment_ID           | bigint(20) unsigned | NO   | PRI | NULL                | auto_increment |
| comment_post_ID      | bigint(20) unsigned | NO   | MUL | 0                   |                |
| comment_author       | tinytext            | NO   |     | NULL                |                |
| comment_author_email | varchar(100)        | NO   | MUL |                     |                |
| comment_author_url   | varchar(200)        | NO   |     |                     |                |
| comment_author_IP    | varchar(100)        | NO   |     |                     |                |
| comment_date         | datetime            | NO   |     | 0000-00-00 00:00:00 |                |
| comment_date_gmt     | datetime            | NO   | MUL | 0000-00-00 00:00:00 |                |
| comment_content      | text                | NO   |     | NULL                |                |
| comment_karma        | int(11)             | NO   |     | 0                   |                |
| comment_approved     | varchar(20)         | NO   | MUL | 1                   |                |
| comment_agent        | varchar(255)        | NO   |     |                     |                |
| comment_type         | varchar(20)         | NO   |     |                     |                |
| comment_parent       | bigint(20) unsigned | NO   | MUL | 0                   |                |
| user_id              | bigint(20) unsigned | NO   |     | 0                   |                |
+----------------------+---------------------+------+-----+---------------------+----------------+

```

**Comment by mindctrl** [comment] 2018-07-19 14:44
Doing the Order Notes migration for the third time, as I had some issues with it completing yesterday... partly due to my own error.

This is resulting in note duplications in the new table. 

![image](https://user-images.githubusercontent.com/1254870/42949551-faf17b4c-8b3f-11e8-8576-05f56122f42e.png)

The migration is currently running, which is why some of the notes in that screenshot are only showing twice instead of 3 times.

Screenshot from prior to upgrade:
![image](https://user-images.githubusercontent.com/1254870/42949812-a3a90250-8b40-11e8-9e9c-6a896f7ed3a1.png)

Just noticed, it looks like the timestamps are different.

**Comment by mindctrl** [comment] 2018-07-20 14:07
I'm getting PHP notices during the Order upgrade routine.

`PHP Notice:  Undefined index: last_name in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-orders.php on line 137`

Also one for `first_name` when it doesn't exist. Probably should check all those values to make sure they exist before trying to use them.

**Comment by mindctrl** [comment] 2018-07-20 14:31
I have a bunch of orders with a `date_completed` of `0000-00-00 00:00:00`. Not all are that way.

![image](https://user-images.githubusercontent.com/1254870/43008060-0fb6688a-8c08-11e8-9a78-7f71f5b8cb80.png)

**Comment by mindctrl** [comment] 2018-07-20 15:17
Got this notice during log migration:
```
Undefined index: _edd_log_version in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-logs.php on line 93

Undefined index: _edd_log_time in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-logs.php on line 94
```

**Comment by mindctrl** [comment] 2018-07-26 16:18
The `parent` column in the orders table is linking to the `edd_payment` post from the `wp_posts` table, and it should not do that. The old post ID should be stored only in meta.

**Comment by sunnyratilal** [comment] 2018-08-12 11:30
Struggling to track down how the `parent` is being linked to the ID from the `wp_posts` table. I'm not witnessing this behaviour either.

The upgrade routine just uses `post_parent` from the returned `stdClass` from `wpdb`: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-orders.php#L109

**Comment by sunnyratilal** [comment] 2018-08-12 11:56
@mindctrl As customer notes are currently stored in the customer row as one big block of text, we're unable to keep track of what notes have been migrated without running extra queries that check for a like-for-like match.

**Comment by mindctrl** [comment] 2018-08-13 22:14
@sunnyratilal 👍 yeah that would be ugly. :(  Going to try to do some more migration testing in the next two weeks or so. Will circle back and look at this again.

**Comment by chriscct7** [comment] 2018-08-17 07:57
We should also recalculate after everything is done user totals, product totals, and store earnings totals as a step.

**Comment by JJJ** [comment] 2018-08-25 17:03
The upgrade routines are done and working.

Let's close this issue now, and open new ones for bugs we find during testing.

Thanks for the hard work here. This is huge. <3

**Closed by JJJ** 2018-08-25 17:03 UTC
Labels: Administration
