### ISSUE TITLE
Turn edd_get_payment into a caching layer for EDD_Payment, and allow false on no-payment.

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/easy-digital-downloads#4718] opened 2016-06-23 23:09 UTC
When passing a `$payment_id` that isn't a valid payment, `EDD_Payment::setup_payment()` returns false before setting up the payment.

`edd_update_payment_status()` assumes that instantiating `EDD_Payment` returns a valid `EDD_Payment` class, and continues with that assumption, calling `EDD_Payment::save()` no matter the return value.

Related to https://trello.com/c/j7LgHA80/436-gravity-forms-checkout-for-easy-digital-downloads#comment-575edeabeb0ad751c227c4e9

**Comment by pippinsplugins** [comment] 2016-06-24 19:50
Let's definitely do this, but I'm going to milestone it out a bit because there's a very good likelyhood of this causing issues with any one that is doing `if( $payment->ID > 0 )` type checks to determine if a payment was found.

**Comment by SDavisMedia** [comment] 2016-08-31 22:15
Replicated still being able to create a new payment while passing a payment ID that doesn't exist. @zackkatz's PR fixes that. Also confirmed by running `edd_get_payment_gateway( 999 )` and getting no results (`999` is the non-existent payment ID I tried to create).

**Comment by pippinsplugins** [comment] 2016-09-06 03:11
New PR from issue branch set up https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4921

**Comment by cklosowski** [comment] 2016-09-14 20:07
So after some discussion, the expectation here is that if we do something like the following:
```
// Where 123 is not a payment
$payment = new EDD_Payment( 123 );
```
That `$payment` would be `false`. B/C of PHP that's now how object instantiation works, and `__construct` does not return `false`, it returns an empty object. What our goal should be is that `$payment` be equal to `false`...will have to research this a bit.

**Comment by cklosowski** [comment] 2016-11-11 17:52
Ok, researched this more, and you cannot make a class' construct return `false`. In order to do this we'd need a helper function to instantiate `EDD_Payment` that would return `false` after checking the inner data of the instantiated version.

This is a general principal of the PHP Class system. So we either need to reword this and go deeper or close it since it's not possible in it's current state.

**Comment by pippinsplugins** [comment] 2016-11-11 18:07
We could have `edd_get_payment()`, similar to `get_post()`

**Comment by cklosowski** [comment] 2016-11-14 18:50
@pippinsplugins yes, and we could then even go as far as to use the caching method that we're using on the AffiliateWP classes. Would probably actually improve performance quite a bit.

**Comment by cklosowski** [comment] 2017-01-18 17:16
I cannot get this to work properly for the life of me. @sunnyratilal you might taking a further stab at it? Let me know when you do and I can get you what the goals are.

**Comment by sunnyratilal** [comment] 2017-01-25 01:29
@pippinsplugins @cklosowski Good to merge? Unit tests have passed.

**Comment by cklosowski** [comment] 2017-01-25 04:39
@sunnyratilal This isn't right yet. There were some unit tests that weren't updated to use the new wrapper class, which shows it's not working exactly as we'd expect.

Mind taking a look? Guessing it's in the way that updating the information on a payment object doesn't update it's self when `save` is run.

**Comment by sunnyratilal** [comment] 2017-01-25 07:14
@cklosowski I'll update the unit tests

**Comment by sunnyratilal** [comment] 2017-01-25 07:15
Ok - looks like something really went wrong in the latest commit - all the unit tests failed.

**Comment by sunnyratilal** [comment] 2017-01-25 08:35
Weird that all the unit tests all pass locally but when failed on Travis 🤔

**Comment by cklosowski** [comment] 2017-01-25 15:47
@sunnyratilal nothing is wrong with the last commit, this is just showing that the code isn't working right.

The unit tests before were just seeing if the caching method was working to load a payment, it wasn't trying to save data on the payment and then use the payment again.

Essentially, what's happening is there is a fault in the `EDD_Payment` class that isn't saving changes to the instantiated version stored in the WP Cache.

**Comment by sunnyratilal** [comment] 2017-01-26 07:47
It seems what is actually stored in the object cache is an instance of `EDD_Payment` but without all the class variables set up (i.e. running `setup_payment()` but stopping 75% of the way through).

I'm still at odds as to why this doesn't work whereas Software Licensing uses the same code for `EDD_SL_License`.

**Comment by sunnyratilal** [comment] 2017-01-26 07:48
At the end of `EDD_Payment`, changing to return to: `return new EDD_Payment( $payment->ID );` fixes the issues we seem to have but it's defeating the purpose of the object caching.

**Comment by sunnyratilal** [comment] 2017-01-26 10:33
Changing the test from:
```php
public function test_modifying_address() {
	$payment_id = EDD_Helper_Payment::create_simple_payment();
	$payment    = edd_get_payment( $payment_id );

	$payment->address = array(
		'line1'   => '123 Main St',
		'line2'   => '',
		'city'    => 'New York City',
		'state'   => 'New York',
		'zip'     => '10010',
		'country' => 'US',
	);
	$payment->save();

	$payment_2 = edd_get_payment( $payment_id );
	$this->assertEquals( $payment_2->address, $payment_2->user_info['address'] );
}
```

to:
```php
public function test_modifying_address() {
	$payment_id = EDD_Helper_Payment::create_simple_payment();
	$payment    = new EDD_Payment( $payment_id );

	$payment->address = array(
		'line1'   => '123 Main St',
		'line2'   => '',
		'city'    => 'New York City',
		'state'   => 'New York',
		'zip'     => '10010',
		'country' => 'US',
	);
	$payment->save();

	$payment_2 = edd_get_payment( $payment_id );
	$this->assertEquals( $payment_2->address, $payment_2->user_info['address'] );
}
```

Works as well.

**Comment by sunnyratilal** [comment] 2017-01-26 10:39
@cklosowski Think I've fixed it - the `EDD_Payment` object stored in the object cache wasn't being updated when `save()` was called.

The unit tests pass locally so will now wait for Travis to run them.

**Comment by cklosowski** [comment] 2017-01-26 14:36
Testing out, and just refreshed with `release/2.7`

**Comment by cklosowski** [comment] 2017-01-26 14:54
Seems to be working fine. I used some fees, edited payments by adding items, tested out payment resuming (#2714)

@easydigitaldownloads/core-devs If some people could just use this for a few purchases and normal user interactions I'm pretty comfortable with it.

**Comment by pippinsplugins** [comment] 2017-01-26 15:28
This looks good to me.

**Comment by sunnyratilal** [comment] 2017-01-26 15:30
Merged!

**Closed** 2017-01-26 15:29 UTC
Labels: Bug, Payments, Priority: High
