### ISSUE TITLE
Filtering Discount Codes

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#3198] opened 2015-02-25 20:02 UTC
Having enabled several extensions now that auto generate one time use codes such as social discounts, purchase rewards etc my discount code screen is litterally un navigable. Adding tags & categories would allow extensions to tag their codes for instance and then I could filter them out easily.

**Comment by pippinsplugins** [comment] 2015-02-25 20:14
I like this idea.

The EDD site, for example, has over 32,000 discount codes it. Clearly that gets unmanageable if we can't filter them in any way.

**Comment by danieliser** [comment] 2015-02-25 22:55
@pippinsplugins Great, got a few things ahead of this, but this one should be relatively easy and shouldn't require to much testing since it will not modify anything existing ( no codes would have tax/cat already ).

TODO
- New Taxonomies
- New fields on discount editor to manage them

The Discount Table should show the Tag & Cat options automatically or are the tables not built using standard CPT?

**Comment by pippinsplugins** [comment] 2015-02-26 18:32
I wonder if we should look at changing our discount screen to use the standard post edit screen instead of the custom one. It'd allow us to get rid of a decent chunk of code (rendering + actions) and would natively add support for taxonomies and tags.

**Comment by chriscct7** [comment] 2015-02-26 18:56
I don't think we should. I think it will make the interface really confusing for users

**Comment by pippinsplugins** [comment] 2015-02-26 19:03
Why confusing? Just as an example, WooCommerce uses the default edit screen
with a custom meta box and it's very nicely done.

**Comment by chriscct7** [comment] 2015-02-26 19:08
Well let's start with tags & categories. The idea proposed here might confuse people. For example, if we show a tags and categories UI, many people are going to expect that is used the way Discounts Pro uses it: to do discounts for products with a specific category or tag. In terms of usability, the standard edit post page is alot more involved looking than what we have right now, where users can just go straight down and be done. Also, we'd have to be really careful not to break extensions that hook into our current page design for the edit discount page. I think if you ask alot of WordPress users who are just starting out, you'll probably find the standard add new post view is confusing. If we go down the route of a complete redesign, we'll need to extensively usability test it.

**Comment by chriscct7** [comment] 2015-02-26 19:10
Also I'm really wary of the code reduction argument. We're going to have to add alot of code as well to support backwards compatibility, and things like removing metaboxes that appear on all post types (like Yoast SEO) because they don't make sense in a discount context.

**Comment by pippinsplugins** [comment] 2015-02-26 19:18
The potential confusion is definitely the biggest issue I see. I love the idea of organizing discounts, but you're absolutely right that it will be confusing if not presented really well.

**Comment by chriscct7** [comment] 2015-02-26 19:20
I think the better solution to organizing discounts is to hide 1 time use discounts from the main discounts view and put them on their own tab.

**Comment by chriscct7** [comment] 2015-02-26 19:20
If you remove all 1 time discounts from that view, 99.99999% of sites will not have that many discounts. Maybe we should just add a "1 time" use tab

**Comment by chriscct7** [comment] 2015-02-26 19:25
This is kinda similar to what we did with pending orders for buy it now buttons. Just a simple de-cluttering.

**Comment by danieliser** [comment] 2015-02-26 20:33
I disagree, if you make 2 new taxonomies, Calling them Discount Category & Discount Tags, that is not the same as showing a list of download tags and download categories. I see your point there but the confusion is offset simply by choosing the right verbiage.

From a UI/UX perspective moving to the standard Meta Panel is the right move. You can pretty easily strip it down to the bare minimum and only add back what is absolutely needed. On top of that using screen options users can decide what they need and what they don't simplifying and customizing their own interface.

The argument for reducing code base is both valid, as well as @chriscct7 comment about having to add backward compatibility. But the catch here is that in a future version down the line the backward compatibility code can be removed once all extensions have been updated and a sufficient time has passed allowing users to update.

That said I like the option of a few extra meta values as well such as one time use for filtering. But I think coupling that with tags & categories makes it even more efficient.

That said you could easily delete used codes automatically after say 180 days. That way you can start housekeeping discount codes as well. But that would best work with tags & meta data together not just meta data by itself.

**Comment by danieliser** [comment] 2015-02-26 20:36
@pippinsplugins @chriscct7 I do however like the idea that you could apply discounts to products based on download_category & download_tag. And actually the argument could be made that having both download tags/cats & discount tags/cats there would actually act to lessen confusion. Hard to get confused if both are there and described properly.

**Comment by chriscct7** [comment] 2015-02-26 21:06
Housekeeping used discount codes is likely out of the question. There's too many things that could go wrong there (people re-activating them) or needed to run reporting etc. There's an extension for tags and categories already, and its not something most people will use, just based on the fact the extension has only been downloaded a couple dozen times in the last 6 months. Heck, even the Attach Accounts to Orders extension, which serves a really limited subset of a really limited subset of users on EDD has 25x that download count.

I really think the better idea is filtering out 1 time discount codes in terms of organization. Even if we let people tag them, there's going to be alot of manual effort for people to only see the ones they really care about.

The vast majority of people are going to be completely confused where there is any tag or category interface there, regardless of how you name it. 

We should treat each new dropdown or filter we add as a setting, since that essentially is what they are. Is this really making our user's experiences easier, or can the entire problem be avoided by a simple UI change (like the proposed hiding of 1 time use codes). If you want a picture of how this can confuse people, imagine if we had categories and tags for orders, which could be based on things like how they checked out, where they are from, etc. Does that actually help you find the recent orders faster? Does it make hiding pending orders from buy it now buttons easier? No, it would just confuse people. That's why the simple UI change is better.

Now as for the argument of code reduction, what code are we actually removing? We'd only be able, at most, to remove about 500 lines of code (the edit/add discount view, and the if/else template). Now consider the implications here. We're going to add almost exactly the same amount of code removing unneeded metaboxes registered on every post type by WP core and plugins, adding back discount options, registering metaboxes and supporting backwards compatibility. There's nothing that we're removing that we wouldn't somehow have to not incorporate in the new view. We're actually probably just going to gain code not reduce. I'd like to better understand where this code reduction is. So far, it looks like we'd just be adding code.

And finally, what is the *user experience* gain? It seems like we move to metaboxes, add more code, and what is the added benefit? How does it make EDD easier for our users to use? I mean, if you think about this issue, why does adding tags/categories to the type of discount make the discounts any easier to find? Let's say we filter to a category called "tracking discount" on EDD's site. There's thousands of those. How does the filter make it any easier to find? At the end of the day, most users, when trying to find a discount code will either search for the specific name or ID of the discount, because they know it. If we're talking about 1 time use codes, most people won't wade through every single social discount made to find the one they are looking for. If they're looking for it, 99/100 they know the code they are looking for. If we just remove the one time use codes from the discounts default view, all you are left is the ones that apply to everyone or more than once. That's way easier to sort through and solves the actual problem. Instead of needlessly sorting one time discounts using filters that users will just directly search for anyway, regardless of any filtering tool we put there, let's make it easier to find the discounts that aren't one time. That's making the UI simpler for people to use.

**Comment by danieliser** [comment] 2015-02-27 03:19
Valid points, but not changing the UI based on extra code is not a valid point. The fact remains that as a WP plugin, it is generally best to use as much built in functionality as possible. This includes using the built in CPT interfaces, as any future updates to those could cause the need for major rewrites of these custom interfaces that EDD currently uses.

I won't disagree that the simplest option is to just remove those one time use codes from the view by default but consider the following. Maybe I want to see the success and run a report on discount code usage of social shareing coupons. This could only be done if they were tagged some how. The simplest way to do this would be the built in taxonomy system since it would easily allow any plugin that generates discounts to tag them with its own signature.

Otherwise your points are all valid. But there are usages of discount code taxonomies that you are purely overlooking. There currently is no way to run any type of reporting on the success of those types of things without being able to segment them properly.

**Comment by pippinsplugins** [comment] 2015-02-27 17:40
Using the standard UI would definitely be less code, at least I'm pretty sure.

@danieliser I don't think anyone is disagreeing with the usefulness of categories (I really need them). Chris is just saying (and I agree) that we have to be very careful and deliberate with how the category options are presented because it would be very easy for users to jump to the conclusion that assigning a category to a discount in some way affects the purchase conditions required to use the discount.

**Comment by danieliser** [comment] 2015-02-27 17:59
@pippinsplugins I completely understood his argument. And don't disagree, though I would absolutely love to see that as a functionality anyways. I would like to be able to apply discounts based on download_category & download_tags. But that could be as simple as creating dropdowns in the discount options sections and adding well written descriptions for those fields. They would look nothing like the standard tag/cat UI/UX that appears on the right sidebar. They could be the same UI/UX that is being used for AJAX User search, but for cat/tags in that case.

The only question is how do we properly label the discount_tag/discount_category that in an instant tells you they are classifications not discount settings.

That said I firmly believe that if you put in options for download cat/tags inside the meta panel for discount settings it would be self clarifying. All settings representing how the discount functions would be in that one box, a simple notice to that effect would suffice for most users.

**Comment by pippinsplugins** [comment] 2015-03-03 01:16
Oh don't get me wrong, I'd really love to see it :)

I haven't thought too much about it yet so I don't have any more feedback for you yet, sorry.

**Comment by chriscct7** [comment] 2015-03-04 05:30
Note: I've made a ticket for the using post edit screen here to keep this issue focused: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3222

I completely disagree with the usefulness of categorizing discounts. 

What problem are we actually specifically solving by doing that?

I think that the whole issue we're trying to solve has been completely forgotten. The problem is:

>> Having enabled several extensions now that auto generate one time use codes such as social discounts, purchase rewards etc my discount code screen is litterally unnavigable. 

The root issue is there are alot of plugins that register 1 time use codes, like social discount, and those thousands of discounts quickly clog up the discounts page. 

The solution isn't to try to make users and plugins filter and categorize their discounts so that we justify why the default view is just as cluttered as it was before.

The solution is just as easy as it sounds. Move all single use discounts, by default, to a new view called "1 time use codes".

This is literally the same exact problem we had with pending payments. Users were complaining they had too many pending payments. The solution? Just as simple as it sounds, move the pending payments to a new view for buy it now button purchases. Simple, elegant, and requiring zero thought or additional effort by either users or extension authors. It would only require about 10 lines of code to do that, completely solving the problem we're trying to solve without requiring the users or extensions to do anything.

I have yet to hear a problem that categorizing or tagging discounts actually solves, that simply hiding 1 time use codes does not. What specific added benefit does that provide?

**Comment by chriscct7** [comment] 2015-03-04 05:33
To take @pippinsplugins's example:
> The EDD site, for example, has over 32,000 discount codes it. Clearly that gets unmanageable if we can't filter them in any way.

How many discount codes would be in the default view tab if all 1 time use codes were not there? Maybe 20 tops?

**Comment by danieliser** [comment] 2015-03-04 09:05
@chriscct7 - Although that was the use case I originally stated, it was definately not the only one I had in mind when creating this issue. I think you are focused specifically on that one use case, and as such overlooking the many others.

If that was my only purpose I would agree with you. But my initial creation of this issue wasn't only tied to that. That was just one argument for the creation of this functionality.

As I stated before, currently there is no way to determine the overall usage of a codes usefulness. Tagging them would make it simple to pull a report on how many codes generated by social sharing were used, how many left unused. From there you could even eventually extrapolate total purchase values etc down the line.

I created this issue to move to a simpler way of determining the true value of such codes in general as well as making it simpler to find non 1 time use codes.

Currently as it stands I cannot tell whether social discounts is worth keeping or whether its just one more thing cluttering up my pages for little to no reason.

Tagging would make for better discount code reporting in general. Which is something that currently is non existent.

I do like the idea of a view for non 1 time use codes, but that could also be achieved by tagging a discount both one-time-use and social-share.

**Comment by pippinsplugins** [comment] 2015-03-04 15:03
Tagging "social" discounts is a great example.

**Comment by chriscct7** [comment] 2015-03-04 21:00
> I think you are focused specifically on that one use case, and as such overlooking the many others.

I'm focused on the one that was mentioned in this entire GitHub ticket.

I like the idea of reporting on discount codes, but that being said, if we do reporting on discount codes, we'd need to give enough time for the extension authors to update their code with an update routine that goes back and marks already implemented discount codes with the right tags (else we'll get tickets like, "my social login coupon report is missing coupons").

The non-1 time view is literally a single line of code. We'd just use the 2 parameters in the view function on the already existing table class.

I think that what we could do is let extensions use categories and users use tags, so we'd only need to show a tag selection box.

**Comment by danieliser** [comment] 2015-03-04 23:13
@chriscct7 - I did actually make reference to other usages in a comment right after your first long comment.

I like your suggestion for extensions using categories and users using tags. You could take it a step further and make it so that setting a constant EDD_DISABLE_DISCOUNT_CATS can be set by users to override that easily if they wanted/needed.

As for backward reporting for extensions, I'm not sure that is an option at this point, because I cant find a difference between social discount one time codes and one created with purchase rewards. It may be there but I didn't see extra post_meta so I'm not sure how they could detect their own code from another.

But moving forward you could build stats off of newly created ones. I don't see lack of backward reporting as a reason to not move forward though. Would be nice but not necessarily a requirement for this feature to move forward.

**Comment by chriscct7** [comment] 2015-03-05 01:29
I don't think its a blocker issue its just something we should aim for. A mistake in reports (like omitting stuff) has major legal implications for some people and also would lead to large spike in tickets. As for back converting, I think we can distinguish most of them by looking at the code's name structure. The advantage to them being auto generated is they have to follow a pattern in naming. We just use that pattern to identify them.

**Comment by danieliser** [comment] 2015-03-05 06:05
Im not sure I see any distinguishable pattern to their naming. for instance can you tell me what generated these 2 35ffc21141ce8c4, 56a9d2e20050f99. I can't.

If they had a prefix maybe then that could work. But from what I can tell most are generated using a random hash.

Reporting for discount code usage to me would not be a legal matter, not something that could be used in court for instance. It is more of a marketing tool, seeing whether strategy A works better than strategy B. Financial reporting would be unaffected by these changes.

**Comment by cklosowski** [comment] 2015-03-22 03:00
As someone who's built plugins for people using the default post edit screen, with almost none of the default post screen UI...it's a lot of code just to get it to do what you want, and most of the time is just a bit off. I don't think it's the right move and takes quite a bit of code (some a bit hackish) to get it to work right.

I do love the idea of allowing a taxonomy to the discounts though, and moving to a standard post edit screen isn't necessary for that.

**Comment by danieliser** [comment] 2015-03-23 01:23
@cklosowski Not sure I followed the first part, seems like your saying that you've built plugins both ways, but not sure what your final oppinion on the matter was. Am unclear as to whether your saying default UI is better option than custom UI or not. 

> it's a lot of code just to get it to do what you want, and most of the time is just a bit off. I don't think it's the right move and takes quite a bit of code (some a bit hackish) to get it to work right.

**Comment by cklosowski** [comment] 2015-09-25 23:05
Something else to possibly throw in the ring here...what if we had a discount `status` field. We could take ones that have reached their maximum usage or are expired and put them in an `Archived` post status, that doesn't show with the `Live` discount codes (ones that have uses left or are still active.

**Comment by pippinsplugins** [comment] 2015-09-28 00:06
@cklosowski I like that idea.

**Comment by cklosowski** [comment] 2015-09-29 04:21
Punting to 2.6, now that with #3835 merged into `release/2.5` that should help a little.

**Comment by cklosowski** [comment] 2016-06-01 20:30
One of the things that we have that's causing an issue here as well is that a license is not moved to the 'expired' status until it's validity is checked. For instance, right now EDD has over 75k active discounts, but if you start viewing the pages of discounts into the ones that are already expired, simply loading their information is causing them to be moved to `expired` and therefore they no longer show in the `Active` view.

**Comment by cklosowski** [comment] 2016-06-01 20:36
I'm going to code up a few changes here:
1) Introduce a daily cron that simply looks for all discount codes whose expiration post meta is smaller than 'now' and run a query to set all of those post_status records as 'expired'.
2) I'm going to make it so when we increase (or decrease) a discount code's usage, we check it's max usage and if it's at it's max we mark it as `inactive`, or if decreasing it's usage would bring it below the max, it sets the status to `active`
3) In the Tools section, introduce a batch processor to 'update discount statuses' that will go through an run the above checks on existing discounts to clean things up.

Thoughts on that @pippinsplugins and @danieliser I think this will clear things up a bit. And help mitigate the greater issue of if we should introduce something like a new post edit screen and taxonomies.

**Comment by pippinsplugins** [comment] 2016-06-01 20:47
I don't think a batch processing tool is needed at this time. Cron should be more than sufficient.

**Comment by cklosowski** [comment] 2016-06-01 20:49
@pippinsplugins The problem with a cron is that the first one that runs could completely kill a site. In the case of the EDD site, the first time this runs as a cron it's going to have to pull over 75k discounts and check their expiration and/or their usage max in order to update their status.

**Comment by pippinsplugins** [comment] 2016-06-01 20:52
Limit the cron to 100 discounts. That will eventually get them all and will cover the _vast_ majority of websites.

**Comment by cklosowski** [comment] 2016-06-01 20:53
:+1: sounds good.

**Comment by danieliser** [comment] 2016-06-01 21:31
Here is the code I used to auto prune my expired codes.

https://gist.github.com/danieliser/e3d4f02171e665d6d8c35ab88b8b4ad4

**Comment by pippinsplugins** [comment] 2016-06-17 20:06
Quick test on local showed this worked fine! I'm going to test further on EDD staging.

**Comment by pippinsplugins** [comment] 2016-06-17 20:10
Looks good!

**Closed** 2016-06-17 20:10 UTC
Labels: Discounts, Enhancement
