### ISSUE TITLE
Update edd_get_users_purchases() to pull all payments from payment_ids column

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3031] opened 2015-01-29 23:22 UTC
The `edd_get_users_purchases()` function pulls all payments that match a user ID or email.

Sometimes a customer purchases while logged in, sometimes they purchase while logged out. With the current iteration, `edd_get_users_purchases()` will only pull payments made while logged in (if searching on user ID).

To ensure that all payment records get queried for a customer, we should pull both the payment IDs from `payment_ids` column of the customers table and also search by the email and then merge the results.

**Comment by pippinsplugins** [comment] 2015-01-29 23:23
I'm going to take this one.

**Comment by pippinsplugins** [comment] 2015-01-30 22:35
I think the changes in #3038 fixes this but we need to be careful with it. When we first pulled payment IDs from the customer table, we had issues with some payment records not having the proper customer ID attached to them. It was a big problem before because there was no good way to attach a payment to a customer ID. With the introduction of the new customer UI in #2548 , this is much more negligible.

**Comment by pippinsplugins** [comment] 2015-01-30 22:37
Unit tests are failing for this so proceed with caution.

**Comment by pippinsplugins** [comment] 2015-01-30 22:37
https://travis-ci.org/easydigitaldownloads/Easy-Digital-Downloads/jobs/48956983

**Comment by pippinsplugins** [comment] 2015-02-28 18:06
Related #3209

**Comment by cklosowski** [comment] 2015-03-03 02:29
Closing this for now, if we need to we can re-open for discussion.

**Closed by cklosowski** 2015-03-03 02:29 UTC
Labels: Enhancement, Needs Testing, Payments

**Comment by ineagu** [comment] 2015-05-25 08:27
@cklosowski @pippinsplugins I have some issues with this thing, here is what they are : 

1. Here are the customer details : http://www.awesomescreenshot.com/image/258394/2d3a1d9e6c097733c2109233fbd09365 ( 4 payments , 1st is complete )

2.After that in code I do : $purchases = edd_get_users_purchases( get_current_user_id(), 30, true, 'any' );

However what this is listing is only the 1st payment ( showed as pending ) - 

Array ( [0] => WP_Post Object ( [ID] => 2711366 [post_author] => 34448 [post_date] => 2015-05-18 18:35:49 [post_date_gmt] => 0000-00-00 00:00:00 [post_content] => [post_title] => xxx [post_excerpt] => [post_status] => pending [comment_status] => open [ping_status] => open [post_password] => [post_name] => [to_ping] => [pinged] => [post_modified] => 2015-05-18 18:35:49 [post_modified_gmt] => 0000-00-00 00:00:00 [post_content_filtered] => [post_parent] => 0 [guid] => [menu_order] => 0 [post_type] => edd_payment [post_mime_type] => [comment_count] => 0 [filter] => raw ) )

I see this pattern more and more after the customers upgrade ( which finished finally ) and obviously the issue is huge since people can't access their payments and refunds and angry customers increased a lot in past days.

**Comment by ineagu** [comment] 2015-05-25 08:36
However changing it to : edd_get_users_purchases( $current_user->user_email, 30, true, 'any' );  works properly, any possible reason ?
