### ISSUE TITLE
Consider adjusting `EDD_Product_Details_Widget`

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/Easy-Digital-Downloads#4217] opened 2016-01-19 19:01 UTC
In the `form()` method of the widget `EDD_Product_Details_Widget` a query for all downloads is being made.

It might be an edge-case, but I have a client site where there are a lot of downloads, and this query breaks the site there because of a memory limit issue. I actually don't need this widget there, so I simply unregistered it, but I wonder if it would be possible to bypass this query. Maybe we could replace the select field by an autocompletion field where it will only load up to ~50 results (with AJAX) that match the entered search term - or at least make it optional by first showing a dropdown/checkbox to choose whether to show the current download (default) or a specific one. If you choose 'a specific one', we could then make the query via AJAX. This would at least ensure that the widgets page does not break as long as you don't use this functionality.

Like I said this might be considered an edge-case, and it's okay for me to unregister the widget. I just wanted to bring this up as there's always a limit of how much `posts_per_page => -1` can handle.

**Comment by pippinsplugins** [comment] 2016-01-20 07:18
Duplicate of #3177

**Closed by pippinsplugins** 2016-01-20 07:18 UTC
