### ISSUE TITLE
Option to Disable Pagination in the Shortcode

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/Easy-Digital-Downloads#3894] opened 2015-10-08 17:27 UTC
Right now you can pass `pagination` as `false`, but that will still show the actual pagination links (since its not disabling pagination, it's disabling the query limit). What if you want to only display 5 downloads but no pagination, and can't pass the individual IDs? 

`[downloads pagination=false number=10]`

Should not show the pagination links below results.

`[downloads number=10]`

Should.

**Comment by pippinsplugins** [comment] 2015-10-08 20:00
@spencerfinnell I believe this is duplicate of #3522. Is that not working properly?

**Comment by spencerfinnell** [comment] 2015-10-08 20:06
That's disabling pagination by fetching all results. I want to fetch a set/limited number and not output the HTML pagination links.

**Comment by spencerfinnell** [comment] 2015-10-08 20:09
Basically the issue is you can't combine the number and pagination attributes. Setting pagination to false overrides it and doesn't affect the pagination output below if.

**Comment by pippinsplugins** [comment] 2015-10-09 01:28
Ah, makes sense.

**Closed** 2016-01-31 15:35 UTC
Labels: Bug
