### ISSUE TITLE
Add action to cart item title column

### ISSUE THREAD

**Issue by wpweb101** [easydigitaldownloads/Easy-Digital-Downloads#3152] opened 2015-02-16 14:46 UTC
I am working on a feature like to allow users to send pdf voucher as gift to other users. where I am in need of 2 actions/filters where I need your help :

I added this validation from JS :
http://awesomescreenshot.com/0244f0vt49

but there no action for this in the plugin so I can add server side validation.

live page URL: http://project.worldwebtechnology.in/edd/downloads/test/

Problem 2:
when we add a product to cart attirbutes displyed like this as of now:

http://awesomescreenshot.com/0d04f0ws19

while we wanted to display it like this , for that we just need 1 do action.
http://awesomescreenshot.com/0fd4f11966

please let me know your thoughts.

**Comment by danieliser** [comment] 2015-02-21 17:06
Your best bet wpweb101 is to submit a PR with this to show how you see it being added. Then others can make suggestions on those changes rather than the idea itself.

**Comment by pippinsplugins** [comment] 2015-02-22 16:28
@wpweb101 Did you see Daniel and I's answer on Trello? There is a way to do this with the `the_title` filter.

**Comment by wpweb101** [comment] 2015-02-22 18:57
Thanks for the suggestion, but that is also not that much helpfull because if you see my screenshot, you can see I need to use bold tag and <br > tag which is not working because you have called esc_html function so as I said if you guys can simply add 1 do action that will be very much helpfull. and even other developers can also use it.

@danieliser I dont understand what you mean with PR, is this information enough? 

can you please add a do_action on page
easy-digital-downloads\templates\checkout_cart.php
Line : 35
echo '' . esc_html( $item_title ) . '';

after this line I want do_action so in my extension pdf voucher I can disply gift data like this :

http://awesomescreenshot.com/0fd4f11966

**Comment by danieliser** [comment] 2015-02-22 23:51
PR ( Pull Request ). Fork the EDD repo to your own github account, create a new branch "issue/3152" and make your suggested changes there. Then you can make a pull request which can be reviewed and eventually merged.

**Comment by danieliser** [comment] 2015-02-22 23:54
Since you have an open issue on this already, if you feel git is tough to figure out let me know, I can submit your proposed changes if needed, Just send me the modifications your proposing exactly as you see them. Then others here can review them, such as is the action appropriately named for where it is located and its expected usage.

Once approved it will be merged into the core code and pushed out in a future update.

**Comment by wpweb101** [comment] 2015-02-23 09:48
sorry I am not much aware with git.

easy-digital-downloads\templates\checkout_cart.php
Line : 35
echo '' . esc_html( $item_title ) . '';

we called get_the_title on line 33 where I do all what you asked but after that when we actually display that title on shopping cart page it uses above line.

so my html not working.

here the screenshot to explain the problem.
http://awesomescreenshot.com/07d4gmt040

is this information enough?

**Comment by wpweb101** [comment] 2015-02-23 09:49
I need 1 action though, should I create separate issue for that?

**Comment by danieliser** [comment] 2015-02-23 19:42
I'll see what I can come up with

**Comment by wpweb101** [comment] 2015-02-24 06:17
okay, but at-lease let me know should I create new issue for other action I need or start trying to explain it here?

**Comment by danieliser** [comment] 2015-02-24 06:29
New issue. They are unrelated so it needs to be tracked separately.

**Comment by wpweb101** [comment] 2015-02-26 18:08
@danieliser  when should I expect the action I asked get added so I can use it in my plugin?

**Comment by pippinsplugins** [comment] 2015-02-26 18:29
No earlier than 2.3.2

**Comment by danieliser** [comment] 2015-02-26 20:45
@wpweb101, Pippin is correct, even if I add it now, it won't be released to public for usage in an extension for a few cycles at least. Pippin has it slated for 2.3.3 point release, but we may be able to squeak it into 2.3.2

**Comment by chriscct7** [comment] 2015-02-26 21:09
None of the items slated for 2.3.3 will be in 2.3.2. 2.3.2 is reserved for bug fixes only, not enhancements

**Comment by danieliser** [comment] 2015-02-27 03:27
Couldn't the same be said for all point releases. There is really no difference between 2.3.3 and 2.3.2. In terms of development nearly all point releases are for bug fixes and patches only rather than feature development.

**Comment by chriscct7** [comment] 2015-02-27 11:10
The EDD core team has elected for 2.3.2 to be a bug fix only release. If it
doesn't directly fix a bug, its 2.3.3 or later. That includes all
enhancements, feature requests and even filters.

**Comment by danieliser** [comment] 2015-02-27 17:54
@chriscct7 - Thanks for the clarification.

**Comment by wpweb101** [comment] 2015-03-20 12:32
is this action added in 2.3.3, I cant find it.

**Comment by wpweb101** [comment] 2015-03-20 12:33
it just a 1 line change, I was hoping it should be added quite quicker, instead of waiting from customers to open support ticket and then we put this thing in priority, as of now I feel my extension is buggy I have done all my code also I am just waiting for the action get added in main plugin.

**Comment by chriscct7** [comment] 2015-03-20 12:35
No, this action was punted to the 2.4 release, as indicated in the milestone.  We're focusing on getting bugfixes for the 2.3 release out the door. If someone submits a PR to master we'll be happy to consider inclusion in the next point release

**Comment by wpweb101** [comment] 2015-03-20 15:03
okay I dont know about how to submit PR, I will do some r & d on it and will try to do that so I can get this action added soon.

**Comment by wpweb101** [comment] 2015-04-01 08:59
I have tried to create a commit and pull request, can you please If I did correct, so next time I can follow this process?

**Comment by pippinsplugins** [comment] 2015-04-01 15:44
@wpweb101 Looks like your branch needs to be updated with `upstream/master` in order for it to merge cleanly.

Take a look at this guide for help on doing that: https://help.github.com/articles/syncing-a-fork/

**Comment by danieliser** [comment] 2015-04-01 19:14
@wpweb101 What is the extra commit for? The filter on sanitize function?

**Comment by wpweb101** [comment] 2015-04-01 19:19
@danieliser  all i am trying here to add 1 simple do_action. which I explained you a while ago. now I am not much aware with fork doc which pippin sent so I need to go through it.

**Comment by danieliser** [comment] 2015-04-01 19:35
@wpweb101 - Sorry, your pull request included this https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3323/files#diff-0fc4cfad82ef0e4a14720904d33c326cR1280.

Not sure if thats mean't to be there. I can make a PR for the other if you feel you can't get it figured out. But it would definately be worth the time to learn how to do properly for future use.

**Comment by wpweb101** [comment] 2015-04-02 11:48
@danieliser okay I understand what you mean, it was old code which get committed accidentally. sorry for that. 
please only consider changes to templates/checkout_cart.php so this is the only mistake I did? then I got it the process and I can do that for future. 

so

**Comment by danieliser** [comment] 2015-04-04 03:18
@wpweb101 the problem is though that if they merge your PR as is those changes will also get merged in, they can't pick and choose which parts will get merged. I'm a git expert by no means so I may not be the best person to explain your best course of action, but it either requires a new PR or your branch being reset and then recommitted, or possibly undoing that commit. Not sure best option.

**Comment by wpweb101** [comment] 2015-04-06 07:14
@danieliser can you do 1 favor? please add this one line of code for me . I dont have time to understand this whole flow for now. or I have to wait for 2.4 release? I also need 1 more do action. should I explain by creating new issue?

**Comment by chriscct7** [comment] 2015-04-06 09:59
@danieliser is a contributor, but not a core team member. If you can explain where you want each of the hooks, I can add them for you in the 2.4 release, but I'd highly recommend learning git at some point, as most large WordPress plugins are being developed on GitHub now to make it easier to third parties to contribute to the project. Even WordPress core will at some point start accepting pull requests from GitHub.

**Comment by danieliser** [comment] 2015-04-07 21:33
@chriscct7 - I think he was simply taking me up on my offer to submit the PR for this since he was having trouble with git. But if you wanna do it even better :+1:

**Comment by pippinsplugins** [comment] 2015-04-10 19:05
@wpweb101 I will manually apply the changes for the next release. I would _highly_ recommend that you do take some time to learn git and include it in your development workflow. It's a tremendously powerful tool.

**Comment by wpweb101** [comment] 2015-04-18 09:14
okay I will check it out, please update me when you added 1 line of code in main pulgin.

**Comment by pippinsplugins** [comment] 2015-05-04 00:57
It will be in 2.4

**Closed** 2015-06-13 15:44 UTC
Labels: Enhancement
