### ISSUE TITLE
Special characters in email addresses do not allow 'Make Primary' link to work

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/easy-digital-downloads#4682] opened 2016-06-14 20:26 UTC
Just tested the new multiple customer email features in EDD 2.6 beta 2 on a staging site.

For me the "Make Primary" link doesn't work. It simply refreshes the page with the old primary email still set.

**Comment by cklosowski** [comment] 2016-06-14 20:27
@pderksen are you using `WP_DEBUG`? I'm curious if the JS didn't get minfied.

**Comment by cklosowski** [comment] 2016-06-14 20:28
Also, what interface were you using? The Admin interface or the Customer facing 'profile editor' interface.

**Comment by pderksen** [comment] 2016-06-14 20:31
Nope. Just a simple staging copy of my live site on WP engine.

Using the admin interface.

![image](https://cloud.githubusercontent.com/assets/79667/16058630/3917e080-3234-11e6-9d5d-f55c4173db0c.png)

**Comment by cklosowski** [comment] 2016-06-14 20:33
Ok I've just tried this out. It's working locally, I'm having no issues promoting an email address to primary within the admin. Are you seeing any errors in PHP error logs? Is this email address somehow attached to a different account or user somewhere?

**Comment by pderksen** [comment] 2016-06-14 20:38
Looked at the link URL. It's the plus sign in the email that's causing it not to work. I use them a lot for testing.

Tried a dot instead of plus and the make primary link worked fine.

![image](https://cloud.githubusercontent.com/assets/79667/16058849/369b3bb2-3235-11e6-99fb-fd949f3206a4.png)

FWIW, when adding a new email, using a plus sign seemed to still work when checking the box "Make primary".

**Comment by cklosowski** [comment] 2016-06-14 20:39
@pderksen I use them too in the initial testing of this. I see it's now breaking it for some reason. I use them too all the time. I'll get that fixed up.

**Comment by cklosowski** [comment] 2016-06-14 20:40
Renamed to show the specific issue.

**Comment by cklosowski** [comment] 2016-06-14 20:42
Ok, verified that `%2B` instead of `+` makes this work. I'll work up a fix for this somewhoe.

**Comment by pderksen** [comment] 2016-06-14 20:47
rawurlencode?

**Comment by cklosowski** [comment] 2016-06-14 20:48
Well, the problem is that part of the data is already being encoded (see the `@`) symbol by wp core functions. We'll just have to be careful not to 'double encode'

**Comment by cklosowski** [comment] 2016-06-14 21:20
@pderksen yep `rawurlencode` on the email prior to sending it over to the `wp_nonce_url` works, verified that we don't end up with any double encoding that breaks things.

**Closed** 2016-06-14 21:58 UTC
Labels: Administration, Bug
