### ISSUE TITLE
Bug with quantities when AJAX is disabled

### ISSUE THREAD

**Issue by wpweb101** [easydigitaldownloads/Easy-Digital-Downloads#3804] opened 2015-09-17 11:16 UTC
Hi

I have uncheck the Enable AJAX from the global setting page.
http://www.awesomescreenshot.com/06958vl1af

now on front-side, I am trying to add download with quantity more then 1. let say for example I tried to add a product with quantity 3. please see below screenshot :

http://www.awesomescreenshot.com/0f058vml45

but now when I click on add to cart button, it only add 1 product into the cart instead of adding 3.

http://www.awesomescreenshot.com/0e358vlt27

Thanks
Jigar Shah

**Comment by pippinsplugins** [comment] 2015-09-17 13:57
@wpweb101 Is it working fine when ajax is enabled?

**Comment by mindctrl** [comment] 2015-09-17 14:01
Confirmed locally that with AJAX disabled the correct quantity does not get added to the cart.

**Comment by wpweb101** [comment] 2015-09-17 14:08
Yes when AJAX is enabled all works great.

**Comment by pippinsplugins** [comment] 2015-09-17 14:36
:+1: We'll get it fixed!

**Comment by wpweb101** [comment] 2015-09-23 10:20
Hi 

There is still issues.

I have disabled AJAX from the global setting page.

See this Screenshot : http://awesomescreenshot.com/06958vl1af

Now on front-side, In Variable Download with multiple purchase option, I selected two different quantiites as per screen shot below :

http://awesomescreenshot.com/0da59cgu2c

But now when I click on add to cart button, it only add 1 product into the cart of both Variable Download Options.

See this Screenshot : http://awesomescreenshot.com/0e559chk28

**Comment by pippinsplugins** [comment] 2015-09-23 13:42
Opened new issue: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3826

**Comment by pippinsplugins** [comment] 2015-09-23 13:42
Wait, nevermind, I thought we had already released this.

**Comment by pippinsplugins** [comment] 2015-09-28 20:06
Turns out this is actually a bigger change than expected. It's also a pretty small edge case. I'm going to close this one as fixed and then re-open  #3826 and tag for 2.5.

**Closed by pippinsplugins** 2015-09-28 20:06 UTC
Labels: Bug, Frontend
