### ISSUE TITLE
The HTML class's product_dropdown should support variable prices

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3175] opened 2015-02-20 00:36 UTC
We should add a variable key to the product_dropdown so that if variable=true it also shows the individual keys for the variable products, similar to how Discounts Pro shows them on it's dropdown. Maybe even offer the ability to pass in a product ID and if so, show the variable options for that product in the dropdown

**Comment by pippinsplugins** [comment] 2015-02-20 02:20
:+1:

**Comment by pippinsplugins** [comment] 2015-06-09 16:32
Punting this to 2.5. It's great but not greatly necessary yet.

**Comment by cklosowski** [comment] 2015-11-02 21:24
I'm going to punt this to 2.6, to coincide with #3972

**Comment by chriscct7** [comment] 2016-08-22 02:31
This is also a major blocker for Discounts Pro. It's the only field blocking it from moving to using entirely EDD HTML functions which would solve 90% of the issues it has as an extension.

**Comment by chriscct7** [comment] 2016-08-22 02:31
This also blocks a pair of FES features that require variable prices in the inputs as well.

**Comment by chriscct7** [comment] 2016-08-22 03:53
See https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4895

**Comment by cklosowski** [comment] 2016-09-26 21:54
@easydigitaldownloads/core-devs Hey guys, so we've got quite a few extensions that could really benefit from this addition. What do you guys feel about getting into something prior to 2.7. I know it's a big change, so it _might_ need to go into a major release, but the sooner the better.

**Comment by SDavisMedia** [comment] 2016-09-26 22:12
I personally want to see it in there as quickly as possible. I've got two users I can update for two different extensions (once they're updated, based on this).

**Comment by chriscct7** [comment] 2016-09-26 22:22
So what we urgently need for discounts pro is just the html-elements file
changes. The other files changed are to add discounts by variations which
we don't need for Discounts Pro's fixes or for my other extensions. I'd
recommend splitting that file's changes out and doing it in hte next point
release and then we can add discounts by variations as a feature later if
we want

**Comment by pippinsplugins** [comment] 2016-09-27 21:48
I'm fine with moving it up to pre 2.7.

**Comment by SDavisMedia** [comment] 2016-10-12 20:12
I can verify that it's implemented like so: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5024#issuecomment-253064753 But there's not much left to test at the moment.

**Comment by pippinsplugins** [comment] 2016-10-13 02:30
@cklosowski could you please put together a quick sample plugin (or update Discounts Pro for it) to demonstrate it to make it easier to test this?

**Comment by chriscct7** [comment] 2016-10-13 07:28
Discounts Pro already works using the proposed two dropdowns

**Comment by cklosowski** [comment] 2016-10-13 16:31
I'll cook up something quickly. the problem is that Discounts Pro requires both this PR and the PR for #5034 to work otherwise you get a fatal error in an undefined function. Give me 10 minutes.

**Comment by cklosowski** [comment] 2016-10-13 16:49
Here is a sample plugin. You can either drop this in the normal plugins directory as a single file and activate, or drop it into a mu-plugins single file plugin and it'll just be activated on it's own.

It adds a single Chosen field to the bottom of the Add and Edit discount view (no labels or anything) and saves into the post meta of the discount Id with a meta key of `ck_test_product_dropdown`.

![screen shot 2016-10-13 at 9 48 47 am](https://cloud.githubusercontent.com/assets/1390124/19358310/43d203ac-912a-11e6-9f90-bc2ccb2b6a5d.png)


```
<?php
/**
 * Plugin Name: Test Variable Price Product Dropdown
 * Plugin URI:  https://easydigitaldownloads.com
 * Description: A plugin for testing variable pricing with product dropdown
 * Version:     0.0.3
 * Author:      Chris Klosowski
 * Author URI:  https://easydigitaldownloads.com.com
 * License:     GPL-2.0+
 */

function ck_add_discount_test() {
	echo EDD()->html->product_dropdown( array(
		'name'        => 'product-dropdown-test[]',
		'id'          => 'product-dropdown-test',
		'selected'    => array(),
		'multiple'    => true,
		'chosen'      => true,
		'variations'  => true,
		'placeholder' => sprintf( __( 'Select one or more %s', 'easy-digital-downloads' ), edd_get_label_plural() ),
	) );
}
add_action( 'edd_add_discount_form_bottom', 'ck_add_discount_test' );

function ck_edit_discount_test( $discount_id, $discount ) {
	$selected = get_post_meta( $discount_id, 'ck_test_product_dropdown', true );

	if ( empty( $selected ) ) {
		$selected = array();
	}

	echo EDD()->html->product_dropdown( array(
		'name'        => 'product-dropdown-test[]',
		'id'          => 'product-dropdown-test',
		'selected'    => $selected,
		'multiple'    => true,
		'chosen'      => true,
		'variations'  => true,
		'placeholder' => sprintf( __( 'Select one or more %s', 'easy-digital-downloads' ), edd_get_label_plural() ),
	) );
}
add_action( 'edd_edit_discount_form_bottom', 'ck_edit_discount_test', 10, 2 );

function ck_test_save_discount( $discount_details, $discount_id ) {
	$values = ( ! empty( $_POST['product-dropdown-test'] ) ) ? $_POST['product-dropdown-test'] : array();
	update_post_meta( $discount_id, 'ck_test_product_dropdown', $values );
}
add_action( 'edd_post_update_discount', 'ck_test_save_discount', 10, 2 );
add_action( 'edd_post_insert_discount', 'ck_test_save_discount', 10, 2 );
```

**Comment by SDavisMedia** [comment] 2016-10-13 18:04
@cklosowski It's saving postmeta for the discount when I add one as well as when I edit one. :+1: 

<img width="423" alt="screen shot 2016-10-13 at 11 01 55 am" src="https://cloud.githubusercontent.com/assets/2359131/19360788/d44c4fd2-9134-11e6-9a1e-f82535e433cb.png">

**Comment by cklosowski** [comment] 2016-10-13 18:12
Thanks @SDavisMedia as long as you're good with it @pippinsplugins just go ahead and approve the PR and I'll get this merged in.

**Comment by SDavisMedia** [comment] 2016-10-13 19:09
Tested again with the recent changes and everything is still working as expected for me. :+1:

**Comment by cklosowski** [comment] 2016-10-13 19:11
Awesome!

**Comment by pippinsplugins** [comment] 2016-10-13 19:53
Merged!

**Comment by pippinsplugins** [comment] 2016-10-14 15:17
@cklosowski Could you show why we can't use strict comparisons? Any side effects of not?

**Comment by cklosowski** [comment] 2016-10-14 16:21
@pippinsplugins I've not found a side affect to not using it so long as we cast the value we're searching for as a `string`. This heeds back to that odd `array_key_exists` and `in_array` behavior we saw in PHP.

The reason we cannot is because our keys can either be strings or ints depending on when the product data was stored and if it contains a price_id which will have a `_` in the key. Since using an `int` to search an array key resulted in an odd `true` response, if we cast the needle to a `string` (just for the search), then it matches correctly as it will compare `string 155` to `int 155`, however it will not match `string 155_1`, where as if we use an `int 155` as the needle, PHP for some reason finds a match on `155_1` AND `155`.

**Comment by cklosowski** [comment] 2016-10-14 16:24
In the case I saw with Discounts Pro, the value saved was an `int` (the download id), by casting to a `string` and then searching with strict, it created a false. Because of the following oddity in the PHP `in_array` we cannot strict this when the values may be of mixed types:

```
Testing int to string search:$arr1
/app/public/wp-content/mu-plugins/test-hacks.php:13:
array (size=1)
  0 => string '155_1' (length=5)
in_array( 155, $arr1 )
/app/public/wp-content/mu-plugins/test-hacks.php:15:boolean true
in_array( 155, $arr1, true )
/app/public/wp-content/mu-plugins/test-hacks.php:18:boolean false
in_array( 1, $arr1 )
/app/public/wp-content/mu-plugins/test-hacks.php:21:boolean false
in_array( '155', $arr1 )
/app/public/wp-content/mu-plugins/test-hacks.php:24:boolean false
Testing string to int search:$arr2
/app/public/wp-content/mu-plugins/test-hacks.php:32:
array (size=1)
  0 => int 155
in_array( '155', $arr2 )
/app/public/wp-content/mu-plugins/test-hacks.php:34:boolean true
```

**Comment by pippinsplugins** [comment] 2016-10-14 20:24
:+1:

**Comment by SDavisMedia** [comment] 2016-10-18 23:21
Here's what I'm facing on EDD `issue/3175` and Discounts Pro `release/1.5` when I try to save a Discounts Pro discount:

```
Notice: Undefined index: users in /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-discounts/classes/class-admin.php on line 405

Warning: array_map(): Argument #2 should be an array in /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-discounts/classes/class-admin.php on line 405

Warning: array_map(): Argument #2 should be an array in /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-discounts/classes/class-admin.php on line 405

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-discounts/classes/class-admin.php:405) in /Applications/MAMP/htdocs/edd/wp-includes/pluggable.php on line 1174
```

@chriscct7 If I'm on the wrong branch, please let me know.

Everything's working as expected with @cklosowski's sample plugin still.

**Comment by cklosowski** [comment] 2016-10-18 23:23
That's a bug in Discounts Pro. @chriscct7 looks like it needs a small check on the incoming new fields you've added.

**Comment by cklosowski** [comment] 2016-10-19 16:26
I've pushed an update to Discounts Pro `release/1.5` that fixes the undefined index part.

**Comment by SDavisMedia** [comment] 2016-10-19 19:41
Definitely not working correctly for me on EDD `issue/3175` and Discounts Pro `release/1.5`. Trying to save one variable price selection in the **Products** field of a discount and upon saving, all price variations of that product, including the base, end up showing/saving.

**Comment by SDavisMedia** [comment] 2016-10-19 20:08
^^^ Seems as if that's an issue for Discounts Pro, @chriscct7. All good on EDD's side with @cklosowski's test plugin.

**Comment by chriscct7** [comment] 2016-10-20 13:23
I think I just corrected that issue. Was absinting all of the products on save which won't work. Can you try that again?

**Comment by SDavisMedia** [comment] 2016-10-20 14:34
@chriscct7 Just tested. There's one issue. Everything's good here, though. So I'm gonna take the conversation over to Discounts Pro.

**Closed** 2016-10-20 17:20 UTC
Labels: Enhancement
