### ISSUE TITLE
Item fees can apply to same item multiple times if it's the same product

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6205] opened 2017-11-25 15:50 UTC
Edge case scenario but:
1) Turn off cart quantities
2) Use custom add to cart links to add a single item to the cart multiple times, alternatively you could open the same download on multiple windows/tabs, and click to add to cart on all the windows/tabs.
3) Use discounts pro to apply a fee that is for when there are 3 items in the cart and is a 50% discount
4) Add the item above 3 times to the cart

You'll end up with a $0 cart because our cart contents details looks for fees related to the download ID, of which, there are now 3 (because we added the item to the cart 3 times). Then it loops through and applies all 3 discounts 3 times.

**Comment by chriscct7** [comment] 2017-11-25 16:17
Duplicate of #5459

**Closed** 2017-11-27 22:16 UTC
Labels: Bug
