### ISSUE TITLE
WP Health Check failes loopback request when EDD active

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#7989] opened 2020-06-07 23:27 UTC
### Expected behavior
Health Checks all pass.

### Actual behavior
With only EDD + Health Check plugin enabled (to use Troubleshooting mode) I find that the following issue comes up still.

![image](https://user-images.githubusercontent.com/847818/83982315-e6262400-a8f3-11ea-8bb0-139ec9a49b84.png)

To be clear we are in the process of a migration from WP Engine to an AWS server and I see this same failed check on both servers, so if this is hosting related its unclear exactly how that might be.

### Steps to reproduce the behavior
1) With EDD latest v2 version active
2) View Tools -> Health Check screen.

### Information (if a specific version is affected):
PHP Version: 7.3+

EDD Version (or branch): 2.9.* latest.

WordPress Version: 5.4.1

Any other relevant information:
```
### Begin System Info (Generated 2020-06-07 23:18:23) ###

-- Site Info

Site URL:                 https://new.example.com
Home URL:                 https://new.example.com
Multisite:                No

-- Hosting Provider

Host:                     DBH: 127.0.0.1, SRV: new.example.com

-- User Browser

Platform:                 Windows 
Browser Name:             Chrome  
Browser Version:          83.0.4103.61 
User Agent String:        Mozilla/5.0 (Windows NT 10.0; Wi 
			  n64; x64) AppleWebKit/537.36 (KH
                          TML, like Gecko) Chrome/83.0.410
                          3.61 Safari/537.36
                          
-- WordPress Configuration

Version:                  5.4.1
Language:                 en_US
Permalink Structure:      /%category%/%postname%/
Active Theme:             PUM - Beaver Builder Child Theme 1.0
Parent Theme:             Beaver Builder Theme 1.7.6.3
Show On Front:            page
Page On Front:            The easiest and most versatile WordPress Popup plugin! (#2479)
Page For Posts:           Latest News + Conversion & Marketing Tips (#64817)
ABSPATH:                  /mnt/data/home/330792.cloudwaysapps.com/kxjbebgrrq/public_html/
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 3   Status: Acceptable
WP_DEBUG:                 Disabled
Memory Limit:             512M

-- EDD Configuration

Version:                  2.9.23
Upgraded From:            2.8.11
Test Mode:                Disabled
AJAX:                     Enabled
Guest Checkout:           Disabled
Symlinks:                 Disabled

-- Must-Use Plugins

Health Check Troubleshooting Mode: 1.7.1

-- WordPress Active Plugins

Easy Digital Downloads: 2.9.23
Health Check & Troubleshooting: 1.4.4

__ Custom Reporting Tools: 

-- Webserver Configuration

PHP Version:              7.3.18-1+0~20200515.59+debian8~1.gbp12fa4f
MySQL Version:            5.7.30
Webserver Info:           Apache/2.4.10 (Debian)

-- PHP Configuration

Memory Limit:             512M
Upload Max Size:          50M
Post Max Size:            64M
Upload Max Filesize:      50M
Time Limit:               300
Max Input Vars:           10000
Display Errors:           N/A
PHP Arg Separator:        &

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Disabled

### End System Info ###
```

**Comment by matt70** [comment] 2020-06-08 06:45
Same here! Nevertheless EDD is running fine.
But would be great, when this issue could be solved...

**Comment by cklosowski** [comment] 2020-06-08 23:35
Very curious how this is trying to loop back and what it is trying to execute in the process. We’ll have to look into this further.

**Comment by danieliser** [comment] 2020-06-09 04:03
@cklosowski Appreciate you checking in on it. I've noticed it for some time, but it doesn't seem to actually break anything (that I'm aware of) except that test. But then again those tests I assume are meant to find hidden issues like this, so better safe than sorry.

**Comment by ashleyfae** [comment] 2020-06-09 08:48
I did a super quick test the other day and wasn't able to reproduce the problem, so I wonder if there's another component here we're missing.

**Comment by danieliser** [comment] 2020-06-10 07:13
@ashleyfae I wonder if its related to having some specific setting or maybe even just having populated data, assuming you just installed both plugins to test. I can try to set up a test site this week on our server and duplicate it. If that doesn't work I'll clone our live site and remove everything except those 2 plugins so its still occurring and you can play around with it that way.

**Comment by ashleyfae** [comment] 2020-06-10 08:08
@danieliser That would be helpful - thank you!

**Comment by danieliser** [comment] 2020-06-11 02:20
Update, could not duplicate with fresh install on the same server, so I cloned the app with the issue and added a disable emails plugin, the issue still presents. Sent @cklosowski access token to get in for your team.

Feel free to disable things whatever, I can clone it again or delete it whenever your done.

**Comment by ashleyfae** [comment] 2020-06-16 11:30
@danieliser Got it - thank you!

**Comment by ashleyfae** [comment] 2020-06-17 07:43
Closing this, as we've determined this was caused by another plugin - "EDD gravity forms license check".

**Closed by ashleyfae** 2020-06-17 07:43 UTC
Labels: type-bug, wordpress.org, workflow-needs-replication
