### ISSUE TITLE
need 1 do action in shopping cart page

### ISSUE THREAD

**Issue by wpweb101** [easydigitaldownloads/Easy-Digital-Downloads#3176] opened 2015-02-21 08:55 UTC
Hello

can you please add a do_action on page 
easy-digital-downloads\templates\checkout_cart.php
Line : 35
echo '<span class="edd_checkout_cart_item_title">' . esc_html( $item_title ) . '</span>';

after this line I want do_action so in my extension pdf voucher I can disply gift data like this :

http://awesomescreenshot.com/0fd4f11966

**Comment by mindctrl** [comment] 2015-02-21 14:33
Duplicate of #3152

**Closed** 2015-02-22 16:28 UTC
