### ISSUE TITLE
Rebuild Session Handling

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#5418] opened 2017-01-27 14:39 UTC
Our current session handler needs to be reevaluated and re-built.  We've had issues with cookies in the past (#4284) that have to be fixed as sessions are a fundamental requirement for every EDD store.

A proposal to rebuild sessions (similar to how WooCommerce handle theirs):
- Store one cookie which stores a hash
- Create an `edd_sessions` table which holds session data
- The table holds a hash which correlates to the hash stores in the cookie
- Rebuild `EDD_Session` to store session data  in the database in lieu of cookies
- Utilise object caching for the session data
- Setup cron jobs to clear the session data
- When a user logs out, the session is automatically cleared out

**Comment by pderksen** [comment] 2017-12-11 18:08
Hoping this might be helpful to work out between EDD, Give, Ninja Forms & WP Simple Pay. Possibly others I don't know about. Reposting this in existing related issues on each repo to discuss.

- EDD: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5418
- Give: https://github.com/WordImpress/Give/issues/1630
- Ninja Forms: https://github.com/wpninjas/ninja-forms/issues/3175
- WP Simple Pay Lite: https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/issues/38

Up until now we've been the core of [WP Session Manager](https://github.com/ericmann/wp-session-manager) plugin to manage sessions within WP Simple Pay ([Lite](https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe) & Pro).

However, more recently this hasn't been working on some hosts such as Flywheel & Patheon. After doing some digging & testing, we're now beta testing the core of Patheon's [WP Native PHP Sessions](https://github.com/pantheon-systems/wp-native-php-sessions) plugin. So far beta tests on various hosts are working out great.

Any reason not to go this direction and include WP Native PHP Sessions like this? Is there an easier more straightforward way to handle sessions across modern managed hosting in our plugins?

Related: #4198

**Comment by pderksen** [comment] 2018-01-05 21:05
Update: We're back to using WP Session Manager because of conflicts with other plugins using `session_start()`.

We're also using WP Session Manager's latest version, which now stores session data in a custom table. We're also defaulting to this, but allowing override by using a constant _or_ if Pantheon's session plugin is detected.

Details at https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/issues/38#issuecomment-355664226

Suggestions, discussion, etc always welcome.

**Comment by DevinWalker** [comment] 2018-08-27 19:03
Just want to chime in here and say we'd really _love_ to see EDD make this a higher priority. We've resolved this in our plugin using very similarly to the steps outlined above. 

After years of delay I think it's time sessions are refactored in EDD:

## Hosting and Customer Complaints

![2018-08-27_11-56-38](https://user-images.githubusercontent.com/1571635/44679678-7aa9e580-a9f0-11e8-9b0d-36c41c74dbb7.png)

Also, this has been marked as high priority for more than a year and a half:

![2018-08-27_12-00-17](https://user-images.githubusercontent.com/1571635/44679824-d4aaab00-a9f0-11e8-93ea-d547bc5b9937.png)

See various PRs for additional 

## Code Reference

You're more than welcome to see how it has been done and rolled out with much fanfare and success. Until then, EDD is essentially creating cache-misses and slowing down websites unnecessarily. 

### Session Refactor Task List for Give 

https://github.com/WordImpress/Give/issues/3386

### PR and New Session DB Handler Class

https://github.com/WordImpress/Give/pull/3387/

https://github.com/WordImpress/Give/pull/3387/files#diff-09982cdb8782353cd462be577e3729a7

**Comment by pippinsplugins** [comment] 2018-08-28 02:00
Thanks @DevinWalker! I know we haven't succeeded in giving this the priority it deserves.

We're getting close to wrapping up 3.0 and will see if we can get attention on it immediately following.

**Comment by chriscct7** [comment] 2018-09-03 13:32
> When a user logs out, the session is automatically cleared out

I just wanted to point out, this probably (pending further thinking) should not happen, the sessions should be cleared only when session is stopped programically or if the expiration hits, or if the objective for having a session is completed.

A person logged in getting to checkout and then realizing they need to switch accounts for whatever reason (someone else is logged in, wrong account, etc) probably shouldn't clear the cart.

**Comment by pippinsplugins** [comment] 2018-11-07 01:11
Closing as duplicate of #6894

**Closed by pippinsplugins** 2018-11-07 01:11 UTC
Labels: Enhancement, Priority: High
