### ISSUE TITLE
WP user first and last name changes based on checkout info

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6122] opened 2017-10-28 19:50 UTC
Replicate this while logged into an account. Your admin account is fine.

Add a product to the cart and proceed to checkout. At checkout, enter a different email address, a different first name, and a different last name. Since you're logged in, you're editing values that are most likely already there.

As expected, entering a different email address will result in that email address being added to your customer record as a secondary email. The different first and last names do not change anything about the customer record, though. Honestly, I think that's fine.

However, the first name and last name that you entered at checkout will change the First Name and Last Name fields on the WP user profile associated with that customer record. That, I believe, is wrong. At the very least, it's unexpected and inconsistent.

I think standard personal information entered at checkout should only affect customer records.

**Comment by pippinsplugins** [comment] 2017-10-30 15:56
Duplicate of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6043

**Closed by pippinsplugins** 2017-10-30 15:56 UTC
Labels: Bug, Checkout
