### ISSUE TITLE
Inclusion of jquery-ui breaks some plugins on edd_is_admin_page() pages

### ISSUE THREAD

**Issue by maimairel** [easydigitaldownloads/Easy-Digital-Downloads#2760] opened 2014-11-08 07:00 UTC
Hello, 

The jQuery-ui styles loaded on all admin pages by EED breaks many plugin styling that uses jQuery-ui.
So far I've already encountered a couple of plugins that broke because of this. Is there anyway this can be fixed soon?

Thank you :)

**Comment by cklosowski** [comment] 2015-02-09 15:48
@pippinsplugins When you reworked the ```edd_is_admin_page()``` function just recently, did it help this case at all? Just curious.

**Comment by pippinsplugins** [comment] 2015-02-09 16:58
No.

**Comment by pippinsplugins** [comment] 2015-02-10 23:34
Duplicate of #3033

**Closed by pippinsplugins** 2015-02-10 23:34 UTC
Labels: Administration, Plugin Compatibility
