### ISSUE TITLE
Add Earnings by Category report

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2519] opened 2014-08-16 16:10 UTC
There needs to be a way to view the aggregated earnings per category.

Something like this:
![image](https://cloud.githubusercontent.com/assets/1034109/3942309/cc5fc026-255f-11e4-92e4-49d7140d0945.png)

**Comment by cklosowski** [comment] 2015-06-10 23:57
This could use some pretty heavy testing. But I've got a flot.js pie graph showing for the earnings and sales totals as well.

**Comment by cklosowski** [comment] 2015-06-11 00:00
![screen shot 2015-06-10 at 4 58 09 pm](https://cloud.githubusercontent.com/assets/1390124/8096977/eab37fd2-0f91-11e5-96c6-125be672a081.png)

Some notes on this:
1) The parent categories contain the sales/earnings/averages of all their children as well (uniquely of course) so you cannot just add `Child 1 + Child 2 = Parent`.
2) The graph is filtered out to show only items with `> 1%` input into the charts

**Comment by cklosowski** [comment] 2015-06-11 00:01
Oh
3) The Averages are calculated by adding up all of their average monthly sales and earnings of the downloads in the category, and then dividing by the number of downloads in the category

**Comment by boluda** [comment] 2015-06-11 03:32
Wow, it looks great!

**Comment by chriscct7** [comment] 2015-06-11 03:49
@cklosowski we could/should consider doing a key instead of labels. If you have 50 categories that each take up 2%, we're in trouble. Even 20 at 5% each looks messy. I'd say just do a key with all values over 1%.

**Comment by chriscct7** [comment] 2015-06-11 03:50
That or a hover label thing. Where label is shown as you hover over it. Would be cool down the road for someone to write a little plugin that when you click on a slice it shows more details about it and maybe shows a pie breakdown for products in the selected category slice. Would be really slick if it was all js animated.

**Comment by chriscct7** [comment] 2015-06-11 03:51
Hover doesn't work on mobile though. Grr. Key is probably better

**Comment by pippinsplugins** [comment] 2015-06-11 14:53
Such an awesome improvement.

**Comment by cklosowski** [comment] 2015-06-11 15:02
@Christoff. Still getting into query.flot's options. Have a bit of ways to go

**Comment by chriscct7** [comment] 2015-06-11 16:33
@cklosowski it's @chriscct7. @christoff is another developer.

**Comment by cklosowski** [comment] 2015-06-11 16:37
@chriscct7 Yeah stupid mobile app didn't auto complete for me.

**Comment by cklosowski** [comment] 2015-06-11 17:08
![image](https://cloud.githubusercontent.com/assets/1390124/8113283/c87cbf10-1021-11e5-9ebc-de2b47695e28.png)

Updated to show data in the legends.

**Comment by chriscct7** [comment] 2015-06-11 17:52
@cklosowski +1

**Comment by chriscct7** [comment] 2015-06-11 17:54
The other thing we might want to do is group all the ones that don't have over 2% together and call them other and just do 1 solid grey color with an other %.

**Comment by cklosowski** [comment] 2015-06-11 17:55
@chriscct7 That's what I still have to figure out. With jQuery.flot, you don't know %'s exactly. You pass it the raw values, and it builds the graph and determines % of the total data set. Still digging into their option set to see what we can optimize with, but at this point. I'm going to focus on making it reusable.

**Comment by cklosowski** [comment] 2015-06-11 17:56
I know we can calculate the raw %, but I'd be concerned of having an odd rounding error causing the library to freak out on a sub 100% or over 100% calculation by a small %.

**Comment by chriscct7** [comment] 2015-06-11 18:30
I think it would be useful for us to pass in percentages. I could see extensions wanting access to those percentages

**Comment by cklosowski** [comment] 2015-06-11 18:50
We'll see where we end up with the abstraction, again, most calculations of the graph % is done by the Graphing libraries based off totals, not given %'s.

**Comment by cklosowski** [comment] 2015-06-16 23:40
@pippinsplugins There are a few things about moving it to the `EDD_Graph` class that will make this a bit difficult. Right now it's VERY bias to line graphs...as in, it only does line graphs. We'll have to refactor this entire graph, and I'm really concerned about backwards compat on that.

**Comment by pippinsplugins** [comment] 2015-06-17 14:58
This looks magnificent.

@sumobi @mindctrl @SDavisMedia could each of you test this just to give it some extra eyes?

**Comment by pippinsplugins** [comment] 2015-06-17 15:09
Feedback provided via Twitter: https://twitter.com/addendio/status/611188280084819969

**Comment by cklosowski** [comment] 2015-06-17 15:37
What I'm getting from the information is that Pie Graphs are just used poorly and the UX is difficult. One major point I've found in research of this (after reading the article) is that sorting the pie graph can prove to make things slightly easier. I've got a few ideas, I'll see what I can come up with to make this a better UX and not 'Just Another Pie Graph'

**Comment by cklosowski** [comment] 2015-06-17 15:42
The benefit we have over what the paper talks about is that our graphs can be interactive...not just static works, so it helps us refine the definitions and provide valuable feedback.

**Comment by cklosowski** [comment] 2015-06-17 16:45
Ok to tackle some issues with the readability, i've crated a hover state by default, that when a section of the pie graph is hovered, it highlights the corresponding data in the legend:
![image](https://cloud.githubusercontent.com/assets/1390124/8213249/82244d90-14d5-11e5-9911-10e879d8a613.png)
Currently just using a background of `#f0f0f0` seems to be working pretty well and doesn't alter the graph enough to really mess with the overall Design

**Comment by cklosowski** [comment] 2015-06-17 16:45
Next, ordering by value.

**Comment by mindctrl** [comment] 2015-06-17 18:07
Do we need the double dropdowns?

![screenshot](http://f.cl.ly/items/3D2s0J1d0i272J3P0z3l/Image%202015-06-17%20at%202.06.16%20PM.png)

**Comment by cklosowski** [comment] 2015-06-17 18:11
@mindctrl That's part of our general list table reports. Where it becomes useful is if you have a ton of categories or are on a smaller screen where the table makes you scrol

**Comment by mindctrl** [comment] 2015-06-17 18:16
Ah, gotcha. Thanks.

A couple other things:
- What period does the report include? All sales forever? Year to date? We might need to indicate that somewhere. In the future it might be nice to have ways to specify periods, but that's probably another ticket?
- The monthly sales avg is all 0 on my demo site. Any idea why that might be? I'll test another site, but just bringing it up in case.
![screenshot](http://f.cl.ly/items/3j3m2F1B2W2W0z3U300O/Image%202015-06-17%20at%202.13.47%20PM.png)

**Comment by cklosowski** [comment] 2015-06-17 18:17
This is alltime data, so the avg montys sales are going to take all dates the product is live and bring in the avg...so with 3 sales it'll show 0

**Comment by cklosowski** [comment] 2015-06-17 18:18
My plan is on the 2.5 release, to have all items by time. The issue is in the perofmrance. We'll end up domgin something like the Batch Exporter, but for report data. So it'll show a bar of % copmlete while it loads the report data and then when all queries and data is found, will give the graph.

**Comment by cklosowski** [comment] 2015-06-17 18:19
At least that's my vision for it, @pippinsplugins might have a different idea.

**Comment by mindctrl** [comment] 2015-06-17 18:21
Category 1 has 30 sales. Here's one item from Category 1, note the dates:
![screenshot](http://f.cl.ly/items/3Y1v2i3i2t2A1x2Q2e29/Image%202015-06-17%20at%202.18.29%20PM.png)

This might be a test mode thing or some bum data or something. I'll do some more testing if you want. Also I'm cool with this thing rocking even more in 2.5. Just wanted to make sure the data is right. We're getting dinged about various inaccurate reports/stats in support.

**Comment by pippinsplugins** [comment] 2015-06-17 18:22
@mindctrl if those sales are from pre-2.4 branch, they won't show in test mode.

**Comment by mindctrl** [comment] 2015-06-17 18:32
I wondered that, but why would all columns have data except the one? If we don't show monthly sales avg from test mode sales, why do we show their monthly earnings avg? That's confusing. Or I'm confused. :laughing:

**Comment by mindctrl** [comment] 2015-06-17 18:44
Not seeing 0 sales avg data on another install, so might be limited to that one install.

**Comment by pippinsplugins** [comment] 2015-06-22 14:00
If there are a large number of categories, there's an overflow problem:
![screen shot 2015-06-22 at 8 59 42 am](https://cloud.githubusercontent.com/assets/1034109/8283450/123e6c90-18bd-11e5-8a8e-f7860fea4de8.png)

**Comment by pippinsplugins** [comment] 2015-06-22 14:00
@cklosowski How about ordering the legend from high to low?

**Comment by pippinsplugins** [comment] 2015-06-22 14:01
Or alphabetical.

**Comment by cklosowski** [comment] 2015-06-22 14:03
It is high to low based off value. Not %

**Comment by pippinsplugins** [comment] 2015-06-22 14:22
Ah yes, I see that now.

**Comment by cklosowski** [comment] 2015-06-23 02:57
Going to see if I can come up with a solution for the legends here.

**Comment by cklosowski** [comment] 2015-06-23 17:53
Been working on the legend with a lot of data:
![screen shot 2015-06-23 at 10 48 14 am](https://cloud.githubusercontent.com/assets/1390124/8313186/11c7b968-1996-11e5-9acd-ce4591d96806.png)

**Comment by cklosowski** [comment] 2015-06-23 22:57
Ok, so i've gone away from the flot legends:
![image](https://cloud.githubusercontent.com/assets/1390124/8319148/6f3f8380-19c0-11e5-8dab-8681c8c9d421.png)

This is a bit of a hack, I'm telling it to generate a legend, so it can format and be targetable, adding divs to my own legend via jquery, hiding their legend with a `display: none`, and then displaying ours and tkaing over the hover targets. I want some good testing, but this way we can be more flexible on the number of categories and we do'nt get overlaps

**Comment by cklosowski** [comment] 2015-06-23 23:15
Ok, @pippinsplugins @mindctrl @chriscct7 could you guys poke at this again? Should be much better with categories now.

**Comment by pippinsplugins** [comment] 2015-06-24 14:49
Looks good.

Only issue I notice is when the graphs stack (we need spacing between them):
![screen shot 2015-06-24 at 9 49 32 am](https://cloud.githubusercontent.com/assets/1034109/8332968/5f9ee24a-1a56-11e5-8e63-d2e4b79c5702.png)

**Comment by mindctrl** [comment] 2015-06-26 00:24
Some wrapping issues with the legends. Seems like if cat names aren't fairly short, they get pushed down and in some cases run into the one below. Makes a scrollbar too.
![shot](http://f.cl.ly/items/3x3V3e3e0s0F2S3z0l1b/Image%202015-06-25%20at%208.07.17%20PM.png)

I think switching from a 3 column display to a 2 column display, using percentage-based width instead of a fixed 180px, will help. Example (would need some spacing adjustments for better separation):
![shot](http://f.cl.ly/items/3c3e1H3t3q1L0E2q0c0A/Image%202015-06-25%20at%208.20.58%20PM.png)

Would need some adjustments for smaller screens too. If you agree I can work up some styles for it.

**Comment by cklosowski** [comment] 2015-06-26 06:51
@mindctrl yeah if you want to work up some styles. I played with 2 columns as well, but we need to make sure the whole thing is centered or spaced differently. With 2 columns, the side-by-side get's difficult to tell what legend ends and the next begins.

**Comment by pippinsplugins** [comment] 2015-06-29 18:22
We've decided to leave as is and then improve down the road if necessary.

**Comment by pippinsplugins** [comment] 2015-06-30 22:08
Display issue just showed up: https://cloudup.com/caqSJY-HtRR

**Closed** 2015-06-30 22:17 UTC
Labels: Administration, Enhancement, Reports, Welcome Page
