### ISSUE TITLE
MIME types extension bug

### ISSUE THREAD

**Issue by No3x** [easydigitaldownloads/easy-digital-downloads#6694] opened 2018-06-26 09:46 UTC
### Expected behavior
When I upload a file of type exe, I expect a successful upload to happen.

### Actual behavior
When I do upload a file of type exe, "Sorry, this file type is not permitted for security reasons." is printed and the upload fails.

### Steps to reproduce the behavior
1) Edit a download
2) Try to upload any file of type exe
3) Find the error message `myfile.exe Sorry, this file type is not permitted for security reasons.` 
![bildschirmfoto 2018-06-26 um 11 33 35](https://user-images.githubusercontent.com/2690708/41903024-1f618110-7935-11e8-8875-0c450de5b482.png)

### Information (if a specific version is affected):
PHP Version: PHP 7.2.6-1+ubuntu14.04.1+deb.sury.org+1

EDD Version (or branch): 2.9.3

WordPress Version: 4.9.6

Any other relevant information: 
- This bug was successfully reproduced on a fresh server with same WordPress and edd versions.
- the config `define('ALLOW_UNFILTERED_UPLOADS', true);` is a workaround

**Comment by cklosowski** [comment] 2018-09-04 19:08
This is a WordPress core protection, not an EDD Protection. WordPress core only allows the following file extensions to be uploaded without the constant you list above:
https://codex.wordpress.org/Uploading_Files

Closing as this isn't EDD but WP Core stopping it.

**Closed by cklosowski** 2018-09-04 19:08 UTC

**Comment by No3x** [comment] 2018-09-04 19:37
But edd extends this list with the [upload_mimes filter](https://codex.wordpress.org/Plugin_API/Filter_Reference/upload_mimes) . And in particular it attempts to allow zip.https://github.com/easydigitaldownloads/easy-digital-downloads/blob/b3b09b718d04ded5611b8b34194cbb77190a2c47/includes/mime-types.php#L24
Or what is this module for?

**Comment by spencerfinnell** [comment] 2018-09-04 19:40
It is generally regarded as unsafe to upload `.exe` files. You should archive (`.zip`) your `.exe` and upload that instead; which is allowed due to the filter you linked to.

**Comment by No3x** [comment] 2018-09-04 19:43
@spencerfinnell 
> You should archive (.zip) your .exe and upload that instead; which is allowed due to the filter you linked to.

Following your argumentation exe should work too because it is also in the allowed types added by edd:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/b3b09b718d04ded5611b8b34194cbb77190a2c47/includes/mime-types.php#L31
Or what I'm missing?

**Comment by spencerfinnell** [comment] 2018-09-04 19:46
Your file might not be a true `application/octet-stream` MIME then. If you `.zip` it does it allow you to upload it?

**Comment by No3x** [comment] 2018-09-04 20:26
Your right, that must be the problem. I have checked and the exe has `application/x-dosexec`. I did not assume this.

But do you want to allow exe or is there a reason to allow `application/octet-stream` only?

**Comment by spencerfinnell** [comment] 2018-09-04 20:30
The issue is that octet-stream is just a generic handler for binary files. Certain binaries will have different mime types (like yours) and it’s impossible to cover them all. This is why it’s easier to just .zip the file since that will have a consistent type. Otherwise you can extend the list to include your specific type using the same technique that EDD uses.

**Comment by No3x** [comment] 2018-09-04 20:39
> Certain binaries will have different mime types (like yours) and it’s impossible to cover them all.

Yes, I don't see a possiblity to add multiple mimetypes for the same extension.

>you can extend the list to include your specific type using the same technique that EDD uses.
Yes, but I would need to overwrite 

`'exe'  = 'application/octet-stream'` with `'exe'  = 'application/x-dosexec'`
Seems a bit hacky.

> This is why it’s easier to just .zip the file

I usually do whenever possible but I recently had the requirement to provide this exe for download and at the first glance it appeared as a bug.

Thanks for your help!
