### ISSUE TITLE
Can't validate discount against arbitrary list of downloads 

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/easy-digital-downloads#5645] opened 2017-04-07 16:48 UTC
The `EDD_Discount` class is strongly coupled to cart, so there is no way to use it to check if a discount matches an arbitrary list of requirements. Which would be useful when developing a REST API route to check a discount for use in our EDD Integration.

This is what I'm doing on my site: https://pastebin.com/kRhhz6VT This sucks as its 70% copypasta, and I worry about forward-compatibility. I wish that `is_product_requirements_met` method accepted an array of download ids, with default fallback to cart contents. Or even better, a separate class with the single responsibility of checking validity of discounts.

**Comment by cklosowski** [comment] 2017-04-07 16:49
This seems like a great idea. @sunnyratilal thoughts here?

**Comment by pippinsplugins** [comment] 2017-04-07 16:53
Duplicate of: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5618

I 100% support this enhancement though.

**Closed by pippinsplugins** 2017-04-07 16:53 UTC
