### ISSUE TITLE
Settings sanitization for subsections unsets tax rates when a subsection is registered under taxes

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/easy-digital-downloads#4715] opened 2016-06-23 14:14 UTC
I used 2.6 beta and it seemed to work.  However today I've seen a problem that seems similar to a issue that was a problem with 2.5 until 2.5.3.  You can read about this in #4156.

The issue is that if an extension implements a settings section page (by registering a section using the filter 'edd_settings_sections_xxx') then the settings on the main page are lost when options on the section page are changed.  In my case, if I make a change to an option on a section for my VAT plugin then the tax rates are removed.

 I'm submitting this now so you are aware of it.  I will try to work up a very simple plugin to try to emulate the issue.

**Comment by cklosowski** [comment] 2016-06-23 14:19
We've tested this pretty heavily is it only with the taxes tab? Does the
same thing happen if you emulate this behavior on another tab?

-- 
Chris Klosowski
Sent with Airmail

**Comment by pippinsplugins** [comment] 2016-06-23 14:22
Testing now to see if I can replicate.

**Comment by pippinsplugins** [comment] 2016-06-23 14:23
@bseddon which beta version did you test? 1, 2, or latest `release/2.6` branch?

**Comment by pippinsplugins** [comment] 2016-06-23 14:27
@bseddon we had some other extensions have this same problem but it was an issue with the extension and not in core. The problem in those cases were that the extensions did not have an `isset()` or `! empty()` check in the settings sanitization callback, so it attempted to sanitize its settings on every save, regardless of which tab was being saved.

Can you confirm that your sanitization callbacks only run on your tab/section?

**Comment by bseddon** [comment] 2016-06-23 14:49
The version of EDD I'm using reports 

 * Version: 2.6-beta2

In the header of easy-digital-download.php.  As I recall, I downloaded it from the 'release/2.6' branch.

I am able to replicate the behavior I see using a trivial plugin.  The attached file contains a file called 'plugin-proxy.php'.  Drop this into your themes folder and load it in functions.php.

All it does is add a section to the Taxes settings page (Chris, I'll test other pages when I finish writing this message).  In my tests, at this time my plugin is deactivated so it cannot be influencing the outcome.

The process go through to replicate the issue is to add some tax rates on the default section and save.  I am able to verify that just going to other pages or making changes on other page does not cause the issue.  For example, if I change the shop country on the 'General' page the tax rates remain.

However, if I go to the example section and press the save button and then go to the default taxes page, the rates have gone.  You will see there are no controls defined on the example section and there are values to save or sanitize.

Pippin, I take your point about plugins not being implemented correctly but in the case I am able to see, I'm not using a plugin of any sophistication.

[plugin-proxy.zip](https://github.com/easydigitaldownloads/easy-digital-downloads/files/330186/plugin-proxy.zip)

**Comment by pippinsplugins** [comment] 2016-06-23 14:54
@bseddon testing it now.

FYI, the example plugin throws a notice:
```
NOTICE: wp-content/plugins/plugin-proxy.php:33 - Undefined variable: example_settings
```

I'm guessing that notice is not present in the real plugin?

**Comment by pippinsplugins** [comment] 2016-06-23 14:56
Ok yep, it definitely wipes out the tax rate settings.

I _think_ this is only affecting the tax rates and is likely due to them using a custom save routine. Digging.

**Comment by pippinsplugins** [comment] 2016-06-23 14:59
@bseddon I've confirmed the behavior and fixed it. Updated the issue title to reflect the issue. PR incoming.

**Comment by bseddon** [comment] 2016-06-23 15:00
I agree.  I've tried a similar section on the styles tab and settings there do not seem to be affected.  I also agree its only the tax rates which seem to be lost.

Sorry about the notice.  Trying to get an example to you I forgot to rename a variable I'd copied from the VAT plugin.  As you've seen, it's not a material issue.

**Comment by pippinsplugins** [comment] 2016-06-23 15:02
PR that fixes it: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4716

**Comment by cklosowski** [comment] 2016-06-23 15:06
@pippinsplugins confirmed that fixes it.

**Comment by pippinsplugins** [comment] 2016-06-23 15:08
Closing as fixed.

Thanks @bseddon!

**Closed by pippinsplugins** 2016-06-23 15:08 UTC
Labels: Administration, Bug, Taxes
