### ISSUE TITLE
Store Location Base State Issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5200] opened 2016-11-12 21:24 UTC
Under the "Store Location" sub section within EDD settings, when I change the Country to UK the state field disappears as it should. However the empty field returns when I leave the page and return.

See the following screenshot for reference:

![screenshot 2016-11-12 21 20 45](https://cloud.githubusercontent.com/assets/22668877/20240952/2f3a9e34-a91e-11e6-8f9f-1b7692ed095f.png)

I experimented with other state exempt countries and the same issue appears.

**Comment by pippinsplugins** [comment] 2016-11-14 03:39
Thanks for the headsup!

**Comment by sunnyratilal** [comment] 2017-09-27 13:22
@davidsherlock You opened a duplicate of this issue on #5905 so I'm closing this one out.

**Closed by sunnyratilal** 2017-09-27 13:22 UTC
Labels: Administration, Bug, Priority: Low
