### ISSUE TITLE
Fetch discounted price to show in Theme Template

### ISSUE THREAD

**Issue by hiddenpearls** [easydigitaldownloads/easy-digital-downloads#5893] opened 2017-07-26 13:21 UTC
Hi @pippinsplugins  and Team 💯 

I am using `edd_price( 10, true, 0 );` to fetch the price of a variation. It displays it like that `39.00` Can I make it appear like `39`?

Another question is, 

I want to show a discounted price like If I give a discount code URL  e.g

http://mysite.com/pricing/?discount=gopro10

So, I could cut the original price and show the discount price on my pricing page. Although discount code gets applied on the Checkout page.

Cheers!
Adnan

**Comment by cklosowski** [comment] 2017-08-21 21:02
@hiddenpearls 

You could use `edd_sanitize_amount` instead...and supply a filter for `edd_sanitize_amount_decimals` that returns `0` for the price. This could pose a problem though if you end up doing discount code display since it will likely contain decimal places.

Displaying the price as discounted however will require #5618, since right now getting the discounted amount of a price is coupled to the cart.

**Comment by cklosowski** [comment] 2017-08-21 21:03
I'm going to mark this as a duplicate of #5618, since it's the closest thing I can think of to label it as, and that will likely allow what you want.

**Closed by cklosowski** 2017-08-21 21:03 UTC

**Comment by hiddenpearls** [comment] 2017-08-27 13:39
@cklosowski So, I should use the custom code mention in #5618 to make this thing working, right?
