### ISSUE TITLE
Empty checking error

### ISSUE THREAD

**Issue by debjyati** [easydigitaldownloads/Easy-Digital-Downloads#4065] opened 2015-12-09 12:17 UTC
File path: /includes/download-functions.php
Function name: edd_get_download_file_url()
Line no.: 988
Bug: Firstly, in "if ( ! empty( $payment->ID ) )"
“$payment->ID” is protected member of “EDD_Payment” class. It should be accessed through “__get()” method.

In PHP 5.5.9, “$payment->ID” should be kept in a variable then the variable should be passed in empty() method. The way it is done now is returning “false” as result and the “$download_url” becomes “<SITE URL>/index.php”.

**Comment by mindctrl** [comment] 2015-12-09 14:46
@debjyati are you seeing this in the latest `release/2.5` branch?

**Comment by pippinsplugins** [comment] 2015-12-09 14:47
@debjyati Please see my response to your comment on the beta blog post: https://easydigitaldownloads.com/development/2015/12/03/version-2-5-beta-1/#comment-4

**Comment by pippinsplugins** [comment] 2015-12-09 14:48
Duplicate of #4060

**Closed by pippinsplugins** 2015-12-09 14:47 UTC
