### ISSUE TITLE
Introduce logs database and migrate existing logs

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6238] opened 2017-12-18 21:58 UTC
Our current logs (sales, file downloads, api and requests) are stored as a post type of `edd_log` in the `wp_posts` table. This has had a number of negative consequences and it is time we move them to a sane storage location.

Related:

- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3841
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5277
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4576

**Comment by sunnyratilal** [comment] 2018-01-04 17:48
Just realised that is a duplicate of #3841. I'll close this issue as I've already started committing on the `issue/3841` branch.

**Closed by sunnyratilal** 2018-01-04 17:48 UTC
Labels: Enhancement
