### ISSUE TITLE
Introduce global notes table

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6278] opened 2018-01-04 17:42 UTC
Introduce a global notes table which will handle payment and discount notes.

Two new tables will be introduced: `wp_edd_notes` and `wp_edd_notemeta`.

**Comment by pippinsplugins** [comment] 2018-01-05 05:05
What's the use case for note meta?

**Comment by pippinsplugins** [comment] 2018-01-05 05:16
The notes table should also be used for customer and subscription notes, though those can be migrated later on.

**Comment by sunnyratilal** [comment] 2018-01-05 07:52
@JJJ said that we should have note meta for future third party opportunities.

**Comment by pippinsplugins** [comment] 2018-01-05 08:09
I can think of a few potential use cases so works for me!

**Comment by pippinsplugins** [comment] 2018-01-05 08:15
@sunnyratilal let's get payment notes and discount notes connected to this. Once that's done the upgrade routine can be worked on.

We should also then consider whether it's worthwhile putting customer notes in during 3.0. Unsure yet.

**Comment by sunnyratilal** [comment] 2018-01-05 08:25
@pippinsplugins Not quite sure I follow when you say "connected".  It would be better to link up discounts in #5794 once #5277 and this is merged to allow us to work with the updated version of `EDD_Discount`.

I can go ahead and rewrite the implementation for `edd_*_payment_note` to fetch from the custom table and set up the BC layers if that's what you mean?

**Comment by sunnyratilal** [comment] 2018-01-05 08:28
And also add helper methods to get/insert/delete discount notes

**Comment by pippinsplugins** [comment] 2018-01-05 08:32
Ah yes, doing it in the other issues is better, sorry :)

Let's do payments once that migration is done too.

**Comment by sunnyratilal** [comment] 2018-01-14 21:26
Once #6277 is merged, we need to update the `EDD_Note` object as the column has been renamed from `note` to `content`, which makes more sense as a column name.

**Comment by JJJ** [comment] 2018-05-21 22:44
Notes tables are in, and Customers/Discounts/Payments are setup to use them now.

Let's close this issue, and open new ones for any regressions.

If something is majorly fubar, pleas reopen and blame @sunnyratilal ❤️

**Closed by JJJ** 2018-05-21 22:44 UTC
Labels: Administration, Enhancement, Priority: High
