### ISSUE TITLE
Earnings report - show earnings excluding taxes

### ISSUE THREAD

**Issue by vpratfr** [easydigitaldownloads/Easy-Digital-Downloads#3340] opened 2015-04-10 10:53 UTC
The graph for earnings is great but does not give an accurate idea of the actual money earned in the period if that is shown with taxes.

Eg. I sell plugins from european union. As a consequence, I must charge VAT for EU countries, not for other countries, and rate varies according to the country.

At the end of the month, what matters to me is the real earning because VAT will be given back to the state.

Would be great to have an earnings graph that shows the actual earnings (subtract taxes from the total amount)

**Comment by chriscct7** [comment] 2015-04-10 11:55
Duplicate of #2988

**Closed by chriscct7** 2015-04-10 11:55 UTC
