### ISSUE TITLE
<legend> output in forms

### ISSUE THREAD

**Issue by justintadlock** [easydigitaldownloads/easy-digital-downloads#3568] opened 2015-07-05 23:45 UTC
It is my understanding that a `<fieldset>` should only have one `<legend>` and that should be the first child element.  Legends are currently wrapped in a `<span>`, so they're not the first child.

The fieldset and legend form a pair.  The legend is the "caption" for a particular fieldset.  You can have multiple `<fieldset>` elements, each with their `<legend>`, within a single `<form>` (e.g., would do this in the profile editor form).

I'm just bringing this up because how the `<legend>` element is done in the plugin messes up the design in every one of my themes.

I see two good options:

* Remove the `<span>` wrapped on `<legend>` elements and create extra `<fieldset>` elements in forms with multiple `<legend>` elements.
* Drop the `<legend>` element altogether and opt for an `<h2>` or something like that.

I tried to do a little research on this because I've never seen legends handled like this before. Here's some specs:

* http://www.w3.org/TR/html5/forms.html#the-legend-element
* http://www.w3.org/TR/html5/forms.html#the-fieldset-element
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

**Comment by pippinsplugins** [comment] 2015-07-09 18:29
Thanks for the report @justintadlock!

Tagged for 2.4.3.

**Comment by pippinsplugins** [comment] 2015-07-09 18:30
I vote we drop the span tags as that will have the least impact on existing styles.

**Comment by pippinsplugins** [comment] 2015-08-12 18:45
@SDavisMedia could you give this a quick test in your themes to make sure no styling is broken?

**Comment by SDavisMedia** [comment] 2015-08-12 19:27
It's definitely making a difference. Gonna look at some CSS now to see what it'll take to correct.

**Comment by pippinsplugins** [comment] 2015-08-12 19:29
I didn't see any differences in Twenty Fifteen. Also confirmed that EDD core doesn't style off of the `span` tags.

**Comment by SDavisMedia** [comment] 2015-08-12 19:56
I'm seeing Twenty Fifteen changes, the same changes I see in Vendd. I don't style off the `span` either. There's something going on here. What does the "Personal Info" legend text look like for you? Like this? http://glui.me/?i=85aki7ys6m7ktyl/2015-08-12_at_2.54_PM.png/

**Comment by pippinsplugins** [comment] 2015-08-13 20:19
Maybe it's coming from theme styles.

I'll check again.

**Comment by pippinsplugins** [comment] 2015-08-16 00:50
Punting to 2.5 since there are apparent style changes. Can't make style changes in a point release.

**Comment by SDavisMedia** [comment] 2015-08-28 05:43
I'll study this again this weekend.

**Comment by pippinsplugins** [comment] 2015-08-28 14:46
:+1:

**Comment by spencerfinnell** [comment] 2015-09-30 12:47
Would definitely break Marketify.

**Comment by pippinsplugins** [comment] 2015-09-30 15:09
@spencerfinnell so that we have more to go off of, could you show me how it breaks?

**Comment by spencerfinnell** [comment] 2015-09-30 15:39
Just styles, but would definitely require an update. 

http://www.screensnapr.com/qs4v0jn0xpnb

vs

http://www.screensnapr.com/3ur8ybbpxivz

That being said, the extra element definitely helps our styling. Switching the spans to the inside would help us, but would still require an update. 

Depending on timing we could make any changes for Marketify 2.0.0. Is there a timeline for 2.6?

**Comment by pippinsplugins** [comment] 2015-09-30 15:42
@spencerfinnell 2.6 is months out. Maybe Jan or Feb of 2016. If you could do an update before hand to help us make the transition, that'd probably be best.

**Comment by spencerfinnell** [comment] 2015-09-30 15:48
Yep, I'll add some compatibility to 2.0.0 that assumes the outer `spans` will be removed eventually.

**Comment by cklosowski** [comment] 2016-05-12 20:17
@SDavisMedia @pippinsplugins looks like @spencerfinnell got this done anticipated us making changes, can we get this going to so we can make the 'breaking' change in 2.6? I'd hate to put this off for another major version.

**Comment by pippinsplugins** [comment] 2016-05-12 20:20
Let's get the pull request up to date (if not already) and then start testing our own themes. @SDavisMedia could you do a round of testing? We'll need to do this ASAP so we can announce it and give a heads up through the dev blog.

**Comment by SDavisMedia** [comment] 2016-05-12 21:01
Got it.

**Comment by cklosowski** [comment] 2016-05-17 21:14
@SDavisMedia I've updated the branch `issue/3568` with the latest from `release/2.6` so go ahead and test out.

**Comment by SDavisMedia** [comment] 2016-05-17 21:37
okay will do

**Comment by topher1kenobe** [comment] 2016-05-18 16:50
I see the spans on master, see them removed properly on issue/3568 and in Vendd they still look good. 
![selection_417](https://cloud.githubusercontent.com/assets/341412/15367440/05669a76-1cf7-11e6-8c95-226988f821ac.png)

**Comment by pippinsplugins** [comment] 2016-05-18 16:52
We'll need to test with all of the major themes:

- Vendd
- Shoppette
- Marketify
- SquareCode
- Stocky
- Digital Store (discontinued but still used)

**Comment by topher1kenobe** [comment] 2016-05-18 16:54
Rock on, away I go

**Comment by topher1kenobe** [comment] 2016-05-18 16:59
In **Shopette**, without the span the legend moves up and straddles the div edge.

With span:
![selection_418](https://cloud.githubusercontent.com/assets/341412/15367709/416bfed4-1cf8-11e6-822a-8d107b971a39.png)

Without span:
![selection_419](https://cloud.githubusercontent.com/assets/341412/15367724/4dcda77c-1cf8-11e6-82fb-1ea85a87f0e4.png)

**Comment by pippinsplugins** [comment] 2016-05-18 17:04
@SDavisMedia Could you take care of that in Shoppette?

**Comment by topher1kenobe** [comment] 2016-05-18 17:04
Marketify keeps its spans, even on issue branch 3568, and looks fine.
![selection_420](https://cloud.githubusercontent.com/assets/341412/15367901/0ab14f38-1cf9-11e6-8ecd-c968075d7296.png)

**Comment by topher1kenobe** [comment] 2016-05-18 17:13
**Digital Store** moves the legend up to straddle the border when the spans are removed.

With:
![selection_422](https://cloud.githubusercontent.com/assets/341412/15368107/370ef80e-1cfa-11e6-9380-6fdfc33efb3a.png)

Without:
![selection_423](https://cloud.githubusercontent.com/assets/341412/15368117/3c2effd2-1cfa-11e6-8156-f09ef579927d.png)

Honestly I don't think it's a problem with this theme, I'd leave it.

**Comment by SDavisMedia** [comment] 2016-05-18 17:17
@topher1kenobe make issues and assign me on the repos of the themes you have problems please.

**Comment by topher1kenobe** [comment] 2016-05-18 17:19
**SquareCode** looks exactly the same with and without spans.

![selection_424](https://cloud.githubusercontent.com/assets/341412/15368268/f1794104-1cfa-11e6-82c2-dc5d12fa1ec8.png)

![selection_426](https://cloud.githubusercontent.com/assets/341412/15368313/29c1bb4a-1cfb-11e6-8852-ebf022aefc2c.png)

**Comment by topher1kenobe** [comment] 2016-05-18 17:26
**Stocky** makes the legend move up to straddle the border when there's no span.

![selection_427](https://cloud.githubusercontent.com/assets/341412/15368505/1beb25c8-1cfc-11e6-9cc6-c44cd37d029e.png)

![selection_428](https://cloud.githubusercontent.com/assets/341412/15368512/1fba7dac-1cfc-11e6-90d6-b36fe1133f80.png)

**Comment by pippinsplugins** [comment] 2016-05-18 17:29
Excellent. Let's also go ahead and do a round of tests on the last three default WP themes please.

**Comment by justintadlock** [comment] 2016-05-18 18:55
I just wanted to confirm that the changes have fixed my original issue posted. Nice work!  Now, I need to get back to work on the EDD theme I'm building. :)

**Comment by pippinsplugins** [comment] 2016-05-18 18:56
:)

**Comment by pippinsplugins** [comment] 2016-05-20 19:57
There are still a few themes that need to be updated (that we know of) but I'm going to go ahead and merge this into `release/2.6` to ensure it gets as much testing as possible.

**Comment by pippinsplugins** [comment] 2016-05-20 20:12
Merged into `release/2.6` but leaving open with `Needs Testing` for additional testing.

**Comment by chriscct7** [comment] 2016-05-24 20:25
There should be a dev blog post about this

**Comment by mindctrl** [comment] 2016-05-24 20:38
@chriscct7 https://easydigitaldownloads.com/development/2016/05/20/markup-changes-on-checkout-in-version-2-6/

**Comment by SDavisMedia** [comment] 2016-05-25 17:37
I've made adjustments to Vendd, Shoppete, Lattice, and Digital Store. Quota already controlled these styles. All of the theme updates will go out before EDD 2.6. All changes are backwards compatible.

**Comment by pippinsplugins** [comment] 2016-05-25 17:47
Stripe has to be deployed at the same time as this: https://github.com/easydigitaldownloads/edd-stripe/issues/108

**Comment by SDavisMedia** [comment] 2016-06-01 16:00
I'm gonna go ahead and push an update to all of the themes. They will all be fine with both the old markup and the new markup.

**Comment by topher1kenobe** [comment] 2016-06-01 16:30
2014 looks fine in my opinion.
![selection_439](https://cloud.githubusercontent.com/assets/341412/15717351/9dc11672-27f4-11e6-801e-90cad14a518b.png)

**Comment by topher1kenobe** [comment] 2016-06-01 16:31
2015 looks fine.
![selection_440](https://cloud.githubusercontent.com/assets/341412/15717380/c003441c-27f4-11e6-875d-ffdd0b52f32e.png)

**Comment by topher1kenobe** [comment] 2016-06-01 16:32
2016 is good.

![selection_441](https://cloud.githubusercontent.com/assets/341412/15717420/f24ff41a-27f4-11e6-859e-8ea42c9500b0.png)

**Comment by topher1kenobe** [comment] 2016-06-01 16:40
@justintadlock started this ticket because he's working on a new EDD theme, I'm talking to him about testing that as well.

**Comment by topher1kenobe** [comment] 2016-06-01 16:51
2013 is good.
![selection_443](https://cloud.githubusercontent.com/assets/341412/15718049/8f1828f6-27f7-11e6-8b63-d4e1812b9442.png)

**Comment by topher1kenobe** [comment] 2016-06-01 16:52
2012 is good.

![selection_444](https://cloud.githubusercontent.com/assets/341412/15718077/a863c270-27f7-11e6-90c1-b2c1d8f98355.png)

**Comment by topher1kenobe** [comment] 2016-06-01 16:56
2011 is good.
![selection_445](https://cloud.githubusercontent.com/assets/341412/15718193/3cd9bb62-27f8-11e6-9e3a-c6b5fc978462.png)

**Comment by topher1kenobe** [comment] 2016-06-01 16:57
2010 is good.
![selection_446](https://cloud.githubusercontent.com/assets/341412/15718221/5fcbdcea-27f8-11e6-8c8a-14c3ecb90702.png)

**Comment by topher1kenobe** [comment] 2016-06-01 17:16
Basically it looks great on all themes that leave default styling.  I'm going to call this one tested and done.

**Comment by SDavisMedia** [comment] 2016-06-01 17:28
All EDD themes are updated.

**Comment by pippinsplugins** [comment] 2016-06-01 20:33
I think we go ahead and close this :)

**Closed by pippinsplugins** 2016-06-01 20:33 UTC
Labels: Bug, Frontend, Needs Testing
