### ISSUE TITLE
Error for the @charset at css

### ISSUE THREAD

**Issue by silverhoopedge** [easydigitaldownloads/easy-digital-downloads#6395] opened 2018-02-20 01:44 UTC
The validator.w3.org gives this error for the  '@charset' at the begining of edd.min.css: 

Error: CSS: The '@charset' rule may only occur at the start of the style sheet. Please check that there are no spaces before it..

At line 33, column 17

charset "UTF-8";#edd_checkout_

source of issue: [WordPress.org](https://wordpress.org/support/topic/error-for-the-charset-at-css/)

**Comment by SDavisMedia** [comment] 2018-02-20 16:18
@silverhoopedge could you share a public link to the validation results please? I'd like to take a closer look. Right now, I can't reproduce this validation error.

**Comment by SDavisMedia** [comment] 2018-03-10 18:41
@easydigitaldownloads/core-team can anyone reproduce this validation error? If not, I'm going to close the issue.

**Comment by pippinsplugins** [comment] 2018-03-12 16:08
Just checked with a validator and it tells me the charset is valid and proper. Closing as invalid.

**Closed by pippinsplugins** 2018-03-12 16:08 UTC
Labels: Bug
