### ISSUE TITLE
3.0 - Subtotal contains discounts with Discounts Pro

### ISSUE THREAD

**Issue by LisaCee** [easydigitaldownloads/easy-digital-downloads#8601] opened 2021-05-04 20:59 UTC
### Expected behavior
After `issue/8578` becomes core, I expect the order subtotal to only contain the products.
### Actual behavior
The Discounts Pro discount (negative fees) are included in the list of products and the subtotal.
![image](https://user-images.githubusercontent.com/18077352/117068865-a83aa700-ace0-11eb-9439-f3f5655331be.png)

### Steps to reproduce the behavior
1) Enable DP and create an applicable discount
2) Add item(s) to your cart
3) Look at the subtotal in your cart

### Information (if a specific version is affected):
PHP Version: 7.4.1

EDD Version (or branch): 3.0

WordPress Version: 5.7.1

Any other relevant information: Discounts Pro Version 1.5.0

**Comment by ashleyfae** [comment] 2021-05-05 10:02
Closing this as a duplicate of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7621

There's inconsistency in `master` branch too, so this is probably a post-3.0 project.

**Closed by ashleyfae** 2021-05-05 10:02 UTC
Labels: component-checkout, integration-extension
