### ISSUE TITLE
Download Log reports no longer contain "Downloaded By" data

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#6643] opened 2018-06-07 19:13 UTC
### Expected behavior
When you export your download logs under "Dashboard" > "Reports" > "Export" > "Export Download History in CSV", I expect the "Downloaded By" column to contain the data about the person who downloaded the file. 

### Actual behavior
The "Downloaded By" column is. blank. This is likely because of the removal of Personal data from Download Logs for GDPR reasons here:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6548

![34846281_10160605205325077_6384922412575621120_n](https://user-images.githubusercontent.com/1638128/41121030-51ce405e-6a65-11e8-8711-3bc8233e8dd9.jpg)

**Comment by misulicus** [comment] 2018-06-10 09:37
Looks like this will be fixed in 3.0 here : https://github.com/easydigitaldownloads/easy-digital-downloads/commit/deb0337eef10bcd7ebd82d3bce94ec059aaf8db4

**Comment by cklosowski** [comment] 2018-06-12 17:15
For a quick fix, we just need to update the exporter to use the new method of getting data by customer ID, not from the meta. That would suffice until 3.0 is out.

**Comment by SDavisMedia** [comment] 2018-06-21 05:09
Replicated on `master`. Confirmed that the `Downloaded by` column is populated on `issue/6643`. 

However, based on the PR, I believe the column should be populated with the customer email address if there's no name for the customer. I altered one of my customers at the DB level to not have a name. A new export is not displaying the email address instead, though. 

@cklosowski can you check that to make sure I'm not testing incorrectly?

**Comment by cklosowski** [comment] 2018-07-02 21:54
@SDavisMedia that hasn't been our fallback in the past, however we can quickly update it to use the email if the name is blank.

**Comment by cklosowski** [comment] 2018-07-03 19:02
@SDavisMedia Fixed up for you, ready for testing.

**Comment by SDavisMedia** [comment] 2018-07-03 19:29
@cklosowski yep, that worked. All goody here. :+1:

**Closed** 2018-07-03 21:58 UTC
Labels: Bug, Has PR, Needs Testing
