### ISSUE TITLE
EDD Slug change and pagination problem

### ISSUE THREAD

**Issue by ottobyte** [easydigitaldownloads/easy-digital-downloads#5598] opened 2017-03-24 14:34 UTC
When the EDD_SLUG is defined, and a number of downloads are set per page [downloads number="3"]  the pagination outputs subsequent pages as 404.

**Comment by ottobyte** [comment] 2017-03-24 15:18
On further investigation I see that the reason is that the EDD_SLUG name clashes with a page name. Surely there's a way to make the downloads a parent page and have all downloads children ie:
downloads/childname/

**Comment by pippinsplugins** [comment] 2017-03-27 18:48
@ottobyte What did you change the slug to and what is the name of the page the [downloads] shortcode is placed on?

**Comment by ottobyte** [comment] 2017-03-27 19:08
@pippinsplugins The page with the shortcode [downloads] is "sounds", the products themselves are at the moment using the default "downloads". However if I change the slug in the functions to match "sounds", then re-save the permalinks page I get the 404 errors on any subsequent paginated page.

**Comment by pippinsplugins** [comment] 2017-03-29 14:40
Ah, okay. That's actually a WordPress core issue and not something that can be resolved in EDD.

I would recommend setting the page name to `sounds` and the downloads slug to `sound`.

**Comment by pippinsplugins** [comment] 2017-03-29 14:40
Closing as invalid since this is not a bug in EDD.

**Closed by pippinsplugins** 2017-03-29 14:40 UTC
